SerenityOS/jakt

samples/classes/static_method_called_on_object_instance.error, samples/classes/static_method_called_on_object_instance.jakt, src/typechecker.rs
Previously, this would error with `wrong number of arguments`. While this is correct, calling a static method through an object instance doesn't make sense, so let's be more specific as to what is actually wrong with the call.
```
class Foo {
function bar() {
println("I am missing a this parameter")
}
}
let foo = Foo()
foo.bar() // TypecheckError "wrong number of arguments"
}
```
=> Improve error message when calling static methods like instance methods

README.md
This pull request updates a missed occurance of `anon` in the readme, not changed in e15a4eabcb34c6f911320bbafb22057879671c92.
=> README: Use `anonymous` instead of `anon` in Function calls section

src/parser.rs
Closes #107 
Prior to this patch, there was a one-off error for the end span, as well as inconsistent span capturing for method calls compared to function calls. This patch fixes this, making it more consistent.
By the way, huge fan of SerenityOS and @jntrnr's NuShell project. I hope my contribution is one of many to this project -  been on the lookout for a project like this for a while :)
=> Parser: Fix method call capturing spans incorrectly

README.md, runtime/AK/Variant.h, runtime/lib.h, samples/enums/simple_match.jakt, src/codegen.rs, src/parser.rs, src/typechecker.rs
- Clean up `parse_typename()`'s will-maybe-consume-all-the-type mess (play "yaaaaaaaay" soundtrack in your head please)
- Add codegen & ctor for `enum Foo { A { foo: i32 } }` plus support for it in `match`.
- Fix the weirdo windows failure
=> src: Implement struct-like enum variants / misc parsing stuff

src/lexer.rs, tests/main.rs, tests/parser/dot-followed-by-eof-crash.error, tests/parser/dot-followed-by-eof-crash.jakt
When the lexer sees the dot, it increments the index into the `bytes`
array and then use the incremented index to check for another dot.
However, it did not check if this was out-of-bounds, meaning if a dot
is followed by EOF, the lexer would panic with an array OOB.
=> Check if lexer index is out of bounds before checking for DotDot

samples/apps/cat.jakt, samples/apps/crc32.jakt, src/typechecker.rs
- Change the sample apps to use explicit `c_int` comparisons instead of relying on an implicit cast which is not implemented at the moment
- Add support for `c_int` types in numeric compare expressions
- Make `make_lookup_table` throws (see #137)
Closes #131
=> Convert the sample apps to explicit int comparisons

runtime/AK/Array.h, runtime/IO/File.cpp, runtime/IO/File.h, runtime/lib.h, runtime/prelude.jakt
Here's something a little bit nicer than using the standard C library.
Note that we're limited by what's supported on all of macOS, Linux and Windows.
=> runtime: Add a simple File class for basic I/O

vscode/syntaxes/jakt.tmLanguage
- highlight `mutable this` and `this`
- allow comments inside enums
- fixup function declarations without bodies (to actually highlight
types as types and not constants)
- make `anonymous` require word boundaries
=> Fix some more vscode syntax highlighting bugs

.vscode/launch.json
This launch configuration utilizes the CodeLLDB extension, the default debugging extension for Rust in VSCode. It will debug the jakt compiler running on the open file. So to debug any given file that has bugs in its compilation, simply open it and start the launch configuration from the "Run/Debug" window.
=> Create a VSCode launch configuration to debug current file compilation

editors/vim/README.md, editors/vim/ftdetect/jakt.vim, editors/vim/indent/jakt.vim, editors/vim/syntax/jakt.vim
Currently vim plugin is in the `editors` directory, but vscode one is not. I think in the end vscode plugin should also be moved to `editors`, but it was somewhat out side of the scope of this PR.
=> Add syntax highlighting for vim

README.md, samples/namespaces/hello_namespace.jakt, samples/namespaces/hello_namespace.out, samples/namespaces/namespace_struct.jakt, samples/namespaces/namespace_struct.out, src/codegen.rs, src/compiler.rs, src/parser.rs, src/typechecker.rs, tests/main.rs
This adds support for simple namespaces:
```
namespace Greeters {
struct Person {
name: String
age: i64
function greet(this) {
println("I am {} and my age is {}", name, age)
}
}
}
let p = Greeters::Person(name: "Jane", age: 100)
p.greet()
}
```
and
```
namespace Greeters {
function greet() {
println("Well, hello friends")
}
}
Greeters::greet()
}
```
This PR also makes the names for data structures for the parsing stage more clearly marked so in later stages it's obvious what has been parsed but not yet typechecked.
=> Add support for namespaces

runtime/AK/Dictionary.h, runtime/prelude.jakt
Previously Dictionary::set and Dictionary::ensure_capacity did not
propagate errors back up, this patch makes it so that we now use
the fallible versions
=> Make Dictionary methods use fallible versions

src/parser.rs, tests/parser/unclosed-paren-in-function.error, tests/parser/unclosed-paren-in-function.jakt
When the parser tries to parse an expression from "}" (for the second argument of the function), it errors out and doesn't increment the token index. But because the inner loop that repeatedly parses function parameter expressions never considered errors, it would get stuck in an infinite loop failing to parse "}".
The solution is simply to check for errors and bail out of the loop if there is one. A regression test has been added to the parser tests.
Fixes #155
=> Fix infinite loop while parsing illegal function call arguments

.github/workflows/discord.yml
This is directly based on [Serenity's discord.yml file](https://github.com/SerenityOS/serenity/blob/master/.github/workflows/discord.yml).
The main missing thing is the "JAKT_DISCORD_WEBHOOK" secret that needs to be added to the organization and need to point to the right channel in Discord, but that's not something I can do much about!
=> Add Discord notifications on new commits and PRs

samples/dictionaries/reference_semantics.jakt, src/codegen.rs
=> codegen: Emit empty return at the end of throwing void functions

editors/vscode/syntaxes/jakt.tmLanguage
- Underscores in numeric literals
- Set syntax (types & expressions)
- Namespaces
- Couple more operators and keywords (`..`, `in`, `::`, `raw`)
Thanks for the painful set type notation, it hurt to support.
Also, _please_ just update the definitions when adding keywords and stuff, maintaining this alone forever is not something I want to do :sweat_smile:
=> Update the syntax highlighter with moar new syntax

samples/classes/static_method.jakt, src/codegen.rs, src/typechecker.rs
All class constructors perform a heap allocation, and since those can fail, all constructors can throw.
=> typechecker: Mark all class constructors as throwing

src/typechecker.rs, tests/typechecker/function_call_generic_type.error, tests/typechecker/function_call_generic_type.jakt
Resolves an Issue, where calling a non-generic function with a type crashes the typechecker
resolves #180
=> Bounds check generic parameters before accessing

samples/math/number_types.jakt, samples/math/too_large_literal.error, samples/math/too_large_literal.jakt, samples/math/too_small_literal.error, samples/math/too_small_literal.jakt, src/lexer.rs, src/typechecker.rs
If I'm not mistaken, this should handle all out-of-range literals with errors instead of silent truncation or overflow/underflow.
=> Handle out-of-range literals correctly

samples/apps/cat_std.jakt, src/codegen.rs, src/typechecker.rs
Adds a new cat sample, built only from the standard library
Also adds `print` builtin as a companion to `println`
=> Samples: Add 'cat' that uses jakt standard libary

src/lexer.rs, tests/parser/invalid-digits-in-binary-number.error, tests/parser/invalid-digits-in-binary-number.jakt, tests/parser/invalid-digits-in-octal-number.error, tests/parser/invalid-digits-in-octal-number.jakt
Currently there is a bug when lexer tries to lex an invalid bin/oct number.
This (note the `56` in binary number)
```
let s = 0b0156
}
```
results in this
```cpp
const i64 s = static_cast<i64>(1LL);
static_cast<i64>(56LL);
```
Same fix applies to octal. Hex numbers are fine, since all digits get eaten anyways.
=> lexer: Fix to lexing bin/oct number invalid digits

samples/arrays/prefill.jakt, samples/arrays/reference_semantics.jakt, samples/basics/bubble_sort.jakt, samples/math/incompatible_literal.error, samples/math/incompatible_literal.jakt, src/typechecker.rs, tests/main.rs
Add typechecking for:
- Comparison operators (left and right have to be the same type)
- Logical and and or (left and right have to be booleans)
- +, -, *, /, % (left and right have to be the same type)
The mathematical binary operators (+, -, *, /, ...) are still somewhat explicit as casts have to be inserted in some places. While this makes it more explicit, especially when working with multiple different integer types, this might not be desired.
Right now it is not possible to do the following:
```jakt
let x: i64 = array.size() + 12;
```
A cast would be needed to cast the `usize` to an `i64`.
Closes #217
=> Typechecker: add typechecking for binary operations

src/typechecker.rs, tests/typechecker/array_with_void_values.error, tests/typechecker/array_with_void_values.jakt, tests/typechecker/dict_with_void_keys.error, tests/typechecker/dict_with_void_keys.jakt, tests/typechecker/dict_with_void_values.error, tests/typechecker/dict_with_void_values.jakt, tests/typechecker/set_with_void_values.error, tests/typechecker/set_with_void_values.jakt, tests/typechecker/tuple_with_void_values.error, tests/typechecker/tuple_with_void_values.jakt
Since you cannot form a reference to void, attempting to use a `void` type in any of the storage types is invalid and will not compile.
=> typechecker: Disallow storing void types in storage types

Cargo.lock, Cargo.toml, src/main.rs
pico-args is a zero-dependency minimal argument parsing library that just handles the bare basics of argument parsing. We use it here to provide a basic CLI that's a little more ergonomic than before, plus some help output. This is mainly preparatory work for subcommands, specifying output files, etc. which require more sophistication than manual argsparsing.
The main two reasons for choosing pico-args is (1) it's super tiny and fast, keeping the development cycle snappy even with full builds, and (2) most argparsing things are handled in our own code, making it easier to port to jakt later on. We'd just have to replicate the low-level parsing facilities of pico-args, which are not too complex in comparison to things that structopt or clap would handle.
CC @ADKaster, can you rebase your …
=> main: Use pico-args for better CLI

samples/enums/parse.jakt, samples/enums/simple_match.jakt, src/parser.rs
This moves us to the new enum syntax, based on the discord discussion.
With this, we now have a uniform syntax between the match and the enum.
```jakt
enum Foo {
Int(i64)
Struct(x: i64, y: i64)
}
...
match foo {
Int(x) => { println("{}", x) }
Struct(x: x, y: y) => { println!("{} and {}", x, y) }
}
```
=> Parser: Switch to the new enum syntax

src/codegen.rs, src/parser.rs, src/typechecker.rs
From today's video:
> "ty" is used throughout the codebase because type is a reserved word in Rust
How about we don't :^)
=> Everywhere: Stop using 'ty' for type-related variable names

.github/workflows/lintcommits.yml, .pre-commit-config.yaml, meta/lint-commit.sh
Copied from serenity with some light modifications :^)
Also add a pre-commit config to use the lint commits script and run cargo fmt.
=> Meta: Add lint-commits script and lintcommits Github Actions workflows

src/lexer.rs, src/main.rs
This changes the error reporter to:
* print out only nearby lines rather than the whole file
* print line numbers for each line
* print a label on the error
This PR also cleans up the missing quote error message.
Example:
=> errors: Make error reporting nicer

src/main.rs
Had a bit of bad math for where to put the pointer in the error message. Corrected.
Before:
```
Error: Forced unwrap only works on Optional
-----
20 |                 Operation::Add => {
21 |                     return eval(lhs!) + eval(rhs!)
return i
^- Forced unwrap only works on Optional
22 |                 }
-----
```
after:
```
Error: Forced unwrap only works on Optional
-----
20 |                 Operation::Add => {
21 |                     return eval(lhs!) + eval(rhs)
^- Forced unwrap only works on Optional
22 |                 }
-----
```
=> errors: Fix the pointer on the improve error reporter

README.md
Feel free to disagree. Related: #220
=> Meta: Document (intended) behavior of `as`

src/typechecker.rs, tests/typechecker/increment_integer_types.jakt
Previously it was not possible to use `x++` on `usize`, `c_int`, `c_char` primitives.
=> typechecker: Allow unary increment/decrement on all integer types

README.md, samples/classes/class.jakt, samples/classes/method.jakt, samples/classes/static_method.jakt, samples/weak/reassign.jakt, src/parser.rs, src/typechecker.rs, tests/typechecker/class_private_default.error, tests/typechecker/class_private_field_default.error, tests/typechecker/class_private_field_default.jakt, tests/typechecker/class_private_static.error, tests/typechecker/struct_private.error, tests/typechecker/struct_private_field.error, tests/typechecker/struct_private_field.jakt
Now with 100% more JoJo references in tests, this PR brings you visibility modifiers on fields + some refactoring niceties to avoid rightwards drift. Visibility can now be considered fully implemented, unless we want `protected` once inheritance lands.
=> parser+typechecker: Visibility round two, electric boogaloo

samples/classes/class_with_move_only_enum_member.jakt, src/codegen.rs
Previously it was not possible to create a class that had an enum
member, since the generated constructor would try to default-construct
the enum.
The generated C++ now has both a private constructor that uses move()
to slide everything into members, and a public factory function (the
same create() as before that wraps the constructor.)
=> codegen: Use move semantics in generated class constructors

README.md, editors/vim/README.md, runtime/AK/Dictionary.h, samples/strings/string_append.jakt, samples/strings/string_append.out
This pull request capitalizes all occurances of "jakt", execept for
- The file extension and references to it in code
- The cargo crate and npm package name
- Identifiers in the parser / syntax highlighters / codegen output
- The name of the compiler binary and other file paths
- The language of markdown code blocks
- The repository name and its occurances in code / documentation
as well as updates all uses of the word "Jakt" in the readme to use bold formatting
Resolves #258
=> Everywhere: More uniform formatting of the word "Jakt"

runtime/IO/File.cpp
This ensures the bytes written are not modified, i.e. `\n` being replaced by `\r\n` on Windows.
Since the current File API only supports reading and writing raw bytes it feels like a sensible default.
=> runtime: Open files as binary

runtime/prelude.jakt, src/typechecker.rs, tests/typechecker/throw_no_error.error, tests/typechecker/throw_no_error.jakt
A throw statement requires the type of its
expression to be the Error struct.
Other types of expression will be rejected
by the typechecker.
Add a test to check for this behaviour.
Resolves  #147
=> typechecker: Make throw statement expect Error

samples/functions/call_with_bad_args.error, samples/math/incompatible_literal.error, src/typechecker.rs, tests/typechecker/assign_incompatible_to_optional.error, tests/typechecker/assign_incompatible_to_optional.jakt, tests/typechecker/assign_integer_to_weak.error, tests/typechecker/assign_integer_to_weak.jakt, tests/typechecker/generic_late_type_check_bad.error, tests/typechecker/return-value-type-mismatch.error, tests/typechecker/vardecl-type-mismatch.error
- Fix a couple of situations where we were showing numeric type IDs in build errors instead of type names.
- Use `T?` shorthand for `Optional<T>` in diagnostics
- Use `weak T?` shorthand for `WeakPtr<T>` in diagnostics
=> typechecker: Show nicer type names in compiler diagnostics

src/typechecker.rs, tests/typechecker/return_if_missing_else_prong.jakt
The typechecker will now detect blocks containing if statements with
literal boolean conditions as definitely returning if the respective
branch definitely returns.
We could probably check Variables, Unary- and BinaryOps as well, but that might be overkill.
=> typechecker: Support for basic definite returns

CONTRIBUTING.md, documentation/coding-style.md
This is largely based on the SerenityOS CodingStyle.md, with many
sections removed, with examples converted to Rust, and an additional
section on error messages. I barely understand Rust at all so there are
very likely to be some areas I have overlooked, or some issues with my
code examples, but this should be a good start. :^)
=> documentation: Add coding-style document

src/lexer.rs, tests/parser/multi-line-string-with-double-quotes.error, tests/parser/multi-line-string-with-double-quotes.jakt
Previously we allowed string spanning multiple line such as
let x="Hello
world"
These strings miscompiled since they were copy-pasted as is in C++,
which does not allow strings like these
=> lexer: Error out on compiling strings spanning multiple lines

samples/arrays/array_bad.error, src/codegen.rs, src/error.rs, src/main.rs, src/typechecker.rs, tests/typechecker/dictionary_mismatching_key_types.error, tests/typechecker/dictionary_mismatching_key_types.jakt, tests/typechecker/dictionary_mismatching_value_types.error, tests/typechecker/dictionary_mismatching_value_types.jakt, tests/typechecker/set_mismatching_value_types.error, tests/typechecker/set_mismatching_value_types.jakt
This allows you to show a hint on how to fix an error, for example:
```
Error: type 'String' does not match type 'i64' of previous values in array
----
2 | function foo() throws {
3 |     let p = [1, 2, "foo"]
^- type 'String' does not match type 'i64' of previous values in array
4 | }
----
Hint: array was inferred to store type 'i64' here
----
2 | function foo() throws {
3 |     let p = [1, 2, "foo"]
^- array was inferred to store type 'i64' here
4 | }
----
```
```
Error: redefinition of function foo
----
3 |  
4 | function foo() { 
^- redefinition of function foo
5 |      
----
Hint: function foo was first defined here
----
0 | function foo() { 
^- function foo was first defined here
1 |  
----
```
```
Error: redefinition of variable a
----
1 |     let a = 1; 
2 |     let a = 2; 
^- …
```
=> typechecker: Introduce the ability to add a hint to a typechecker error and start making use of it

samples/basics/escape_sequence.jakt, samples/basics/escape_sequence.out, src/codegen.rs, src/parser.rs, src/typechecker.rs
CharacterLiteral instead of storing a char it stores a string.
This way we can now store an escape sequence.
Solves #276
=> Everywhere: fix compiler transpiling incorrect c_char value

src/parser.rs, tests/parser/multiple-expressions-in-array.error, tests/parser/multiple-expressions-in-array.jakt
This fix makes the parser not go into an infinite loop after
encountering an array item with multiple expressions.
Fixes #300
=> Parser: Fix infinite loop on arrays with multiple expressions

src/codegen.rs, src/parser.rs, src/typechecker.rs
External class constructor calls will now be codegened as calling the
class' static ::create method. This mirrors how we do implicit
constructors for regular Jakt classes, and also meshes well with how
many ref-counted Serenity classes work.
=> typechecker+codegen: Call ::create on external class constructor

README.md
Indexing into a dictionary does not return an optional value, so
having an `!` to unwrap it is incorrect.
=> docs: Fix dictionary example in README

samples/arrays/shorthand_optional.jakt, samples/arrays/shorthand_optional.out, src/parser.rs
Previously, we would exit early from `parse_typename` as soon as
we finished parsing a valid shorthand type. This commit makes it
so that we always run the remaining code checking for the post-fix
`?` indicating an optional.
Closes #311
=> parser: Properly handle shorthand in parse_typename

samples/optional/assignment.jakt, samples/optional/assignment.out, src/typechecker.rs
Allows the assignment to `Optional`s. 
Supports both assignments of `T` and `None` to `Optional<T>`.
=> typechecker+tests: Assignment to optionals

samples/control_flow/defer_return_error.error, samples/control_flow/defer_return_error.jakt, src/parser.rs, src/typechecker.rs
Closes #216
This is my first attempt at Rust so there's probably a smarter way of doing this!
=> typechecker: Reject `return` inside a `defer` as an error

runtime/AK/StringBuilder.cpp, runtime/Builtins/Array.h
By casting void we tell the compiler that we are willingly discarding the value.
fixes #320
=> Runtime: Supress Clang warning on Array resize call

src/codegen.rs, src/parser.rs, src/typechecker.rs, tests/codegen/extern_generic_function.jakt
This should make generic extern functions work in all circumstances. And now they don't generate any code, because that doesn't make any sense with templates.
=> parser+typechecker+codegen: Make generic extern functions actually work

src/main.rs
This warning can happen for functions like fopen which Windows has deprecated but others not. Specifically, it will happen if clang uses the MSVC runtime and/or linker.
=> main: Silence "deprecated functions" warning on Windows

samples/strings/string_builder.jakt, src/typechecker.rs
Extern classes and structs should not have any generated methods for
them, including constructors. This commit prevents implicit constructors
from being generated for them.
Depends on #302
=> typechecker: Do not generate an implicit constructor for extern classes

editors/vim/syntax/jakt.vim
This is a duplicate of my earlier PR because I messed up there. Can @jntrnr have a look? :)
Add syntax highlighting for single quote character/byte literals. Highlight is similar to String type with double quotes.
=> editor: Add single quote highlight for Vim

src/typechecker.rs
This makes us avoid repeatedly searching in the project's structs for
internally used structs by caching their IDs the first time they're seen
in the global namespace.
=> typechecker: Cache struct IDs for internally used classes

src/codegen.rs
Currently the code below is a valid jakt statement, but produces
invalid C++. This patch makes it produce valid C++ as well.
```jakt
try foo() catch {
}
```
=> codegen: Make try-catch without catch variable valid

src/main.rs
This patch adds the flags -p (--prettify-cpp-source) and
-F (--clang-format-path) to make formatting emitted C++ code slightly
more convenient. Formatting emitted code is off by default as a measure
to relieve headaches since clang-format may change the meaning of some
code.
=> main: Add option to prettify emitted C++ source

src/main.rs, src/parser.rs
Add the missing token index increment in the default cases of the extern parsing match statements.
Resolves #231.
=> Parser: Fix an extern keyword followed by EOF entering an infinite loop

editors/vim/syntax/jakt.vim
* Added missing keywords and operators.
* Added highlighting for function calls and declarations.
* Added highlighting for enum, struct and class declarations.
* Changed highlight group for variable declaration keywords.
Was `Function`, now `Define`.
* Removed builtin function highlighting. Builtin functions now
highlighted same as regular functions.
=> Editors: updates to vim syntax highlighting

runtime/AK/NonnullRefPtr.h, runtime/AK/String.h, runtime/AK/StringBuilder.h, src/codegen.rs, tests/codegen/type_pretty_printers.jakt, tests/codegen/type_pretty_printers.out
This PR adds code generation of `AK::Formatter` specializations for every emitted Jakt `class`/`struct`/`enum`.
This means you can now pretty-print Jakt objects by doing:
```
class Size {
width: i64
height: i64
}
class Point {
x: i64
y: i64
}
class Rect {
location: Point
size: Size
}
let rect = Rect(location: Point(x: 0, y: 0), size: Size(width: 15, height: 30))
println("{}", rect)
}
```
The program above prints this:
```
Rect(location: Point(x: 0, y: 0), size: Size(width: 15, height: 30))
```
=> Add type formatters for pretty-printing Jakt objects

src/parser.rs, src/typechecker.rs, tests/parser/fat-arrow-with-type-specifier.jakt, tests/parser/fat-arrow-with-type-specifier.out, tests/typechecker/function-return-type-with-fat-arrow.error, tests/typechecker/function-return-type-with-fat-arrow.jakt
Now Jakt accepts specifying a return type explicitly for functions using a fat arrow to declare their block as a single expression with
a return, and makes sure that the type of the expression matches with the explicit type:
```jakt
class S {
function get_secret() -> i32 => "World"
}
```
would result in a `Type mismatch` error with `i32` and `String`, but
```jakt
function secret() -> i32 => 42
```
won't throw any errors.
Works for both methods and standalone functions.
Will close #331.
=> parser+typechecker: Accept fat arrow with explicit return type

samples/classes/restricted_method.jakt, samples/classes/restricted_method.out, samples/classes/restricted_method_inaccessible.error, samples/classes/restricted_method_inaccessible.jakt, src/parser.rs, src/typechecker.rs, tests/typechecker/class_private_default.error, tests/typechecker/class_private_field_default.error, tests/typechecker/class_private_static.error, tests/typechecker/struct_private.error, tests/typechecker/struct_private_field.error
This corresponds to the `Badge<Foo>` pattern in Serenity. A `restricted` method or field is only accessible to the types listed, allowing more granular access control than `public` and `private`.
As implemented, a `restricted(Foo, Bar) function hello() {}` is only accessible to `Foo` and `Bar`. Their subclasses cannot access it, and nor can the class where `hello()` was defined, unless it's listed. Neither of those can be done with Serenity's `Badge` either, but it might be nice to support them.
=> parser+typechecker: Implement `restricted(Foo,Bar,Baz)` visibility qualifier

runtime/AK/Format.cpp
Including math.h ends up pulling in a bunch of the C++ STL.
We were only using it for `isinf()` and `isnan()`, so let's replace
those calls with `__builtin_isinf()` and `__builtin_isnan()`.
This makes `cargo test` complete in 16.5 secs on my machine,
down from 20 secs.
=> runtime: Remove heavy math.h include

samples/namespaces/bogus_namespace1.error, samples/namespaces/bogus_namespace1.jakt, samples/namespaces/bogus_namespace2.error, samples/namespaces/bogus_namespace2.jakt, samples/namespaces/call_functions_in_nested_namespaces.jakt, samples/namespaces/call_functions_in_nested_namespaces.out, src/typechecker.rs
This patch adds support for calling functions (including constructors) within nested namespaces.
Call resolution now starts by walking the qualifiers from left-to-right, recursing into each namespace as it goes.
Note that generics still need some work here, so I've left a FIXME.
=> typechecker: Resolve calls into nested namespaces

samples/basics/format.jakt, samples/basics/format.out, src/codegen.rs, src/typechecker.rs
Let's give ourselves the ability to create formatted strings as well.
This is a hard-coded hack in the compiler, same as println() and co.
=> codegen+typechecker: Expose String::formatted() as format() for now

editors/vscode/README.md
Specifies that in order to call `vsce` from terminal on windows, you have to install it globally. If you don't install it globally, you can only reference it via package.json scripts, which isn't done currently.
=> editors/vscode: Specify global vsce installation needed

src/main.rs
The purpose of this is to avoid having to rename executable files all the time.
=> main: Add ".exe" to the executable file name on Windows

README.md, samples/basics/this_dot_shorthand.jakt, src/parser.rs
This moves the member shorthand from `$foo` to `.foo`.
=> Parser: Move member shorthand from dollar to dot

runtime/AK/StringBuilder.h
```
$ cat test.jakt
let arr = [1, 2, 3]
let set = {1, 2, 3}
let dict = [1: ("hello", "world"), 2: ("from", "jakt")]
println("arr: {}", arr)
println("set: {}", set)
println("dict: {}", dict)
}
$ cargo run test.jakt && ./build/test
arr: [1, 2, 3]
set: {2, 3, 1}
dict: [1: ("hello", "world"), 2: ("from", "jakt")]
```
=> runtime: Add formatters for remaining builtins

src/main.rs
This silences warnings about trying to turn off bleeding-edge warnings.
Fixes #359
=> main: Pass `-Wno-unknown-warning-option` to Clang

samples/control_flow/defer_in_defer.jakt, samples/control_flow/defer_in_defer.out
Our current implementation of defer gives us this feature for free.
Since defer is block-scoped, there is no ambiguity as to what the
behavior of this is. Therefore, this commit adds a sample that tests
if this feature works correctly.
=> samples/control_flow: Test defer in defer

README.md
Since the build steps were updated in PR #358, it is not immediately apparent that `clang` is a dependency. We make sure to add
that in the docs. The build process otherwise creates confusion within users as it spits errors without `clang`. For example, Discord user _Smiley1000_ faced these errors today. 
```
---- test_classes stdout ----
Error: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
thread 'test_classes' panicked at 'assertion failed: `(left == right)`
left: `1`,
right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/test/src/lib.rs:186:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> docs: Update readme to describe clang as a dependency

src/parser.rs, tests/parser/non_parameter_1.error, tests/parser/non_parameter_1.jakt, tests/parser/non_parameter_2.error, tests/parser/non_parameter_2.jakt, tests/parser/non_parameter_3.error, tests/parser/non_parameter_3.jakt
Previously, the compiler would get stuck in an infinite loop when
trying to compile a function parameter list and encountering
something that's not a parameter due to the parser being stuck in the
loop once the error was encountered. An example of this would be
trying to use default parameters, which are not a part of the language
yet. This commit fixes that by breaking out of the loop once the error
is encountered and introduces appropriate test cases.
=> Parser: Fix infinite loop while parsing illegal function parameters

editors/vscode/syntaxes/jakt.tmLanguage.json
I'm no TextMate grammar expert but this seems to fix the issue.
=> editors/vscode: Fix comment highlighting

src/typechecker.rs, tests/typechecker/nonexistent_type.error, tests/typechecker/nonexistent_type.jakt
**Typechecker: Don't discard typechecking errors in variable declarations**
Previously, we would sometimes discard typechecking errors of the
typename in variable declarations. This commit fixes that and adds a
test for it.
**Typechecker: Always use err() to handle return of add_var_to_scope()**
Fixes #403.
=> Typechecker: Don't discard typechecking errors in variable declarations & Always use err() to handle return of add_var_to_scope()

runtime/prelude.jakt
This was refactored to return ErrorOr in a previous commit, but currently is broken since Jakt doesn't know about it.
=> runtime: Mark Dictionary<K, V>::keys() with `throws`

src/compiler.rs, src/main.rs, tests/main.rs
You can now specify include paths with `-I path/to/dir`, similar to gcc/clang
I'm not quite sure how to add tests for this without reworking a bunch of the stuff in the current testing infrastructure to allow adding custom command line arguments, if anyone's got any ideas I'm all ears.
=> main: Add ability to specify include paths through CLI

src/typechecker.rs
This patch adds "did you mean" hints for misspelled namespaces,
structs, classes, functions, enums and variables.
Before, we'd get an error stating the variable, type, etc does not
exist. Now it checks for a similarly named item and hints at the
misspelling.
```
Error: Unknown type
----- test.jakt:5:19
3  |
4  | function foo() -> NispeeledTypaad {
^- Unknown type
5  |     return MisspelledType()
-----
Hint: Did you mean 'MisspelledType'?
----- test.jakt:5:19
3  |
4  | function foo() -> NispeeledTypaad {
^- Did you mean 'MisspelledType'?
5  |     return MisspelledType()
-----
```
=> typechecker: Add "did you mean" hints

samples/apps/cat.jakt, samples/apps/crc32.jakt
characters() function in the runtime has been renamed to c_string() now.
=> samples: Change .characters() to .c_string()

src/compiler.rs, src/typechecker.rs, tests/typechecker/throw_without_throws_function.error, tests/typechecker/throw_without_throws_function.jakt, tests/typechecker/throws_function_called_without_throws_function.error, tests/typechecker/throws_function_called_without_throws_function.jakt
Keeps track of which scopes will handle throws. I.e. scopes in a try block and scopes in functions that are marked as throws.
If a throw happens in a scope that doesn't handle it, we show this message:
```
Throw statement needs to be in a try statement or a function marked as throws
```
If a function marked as throws is called in a scope that doesn't handle it, we have this:
```
Call to function that may throw needs to be in a try statement or a function marked as throws
```
~~Happy to undo the test changes when #392 get merged.~~
Fixes #153
=> typechecker: Detect missing throws annotations

Cargo.lock, Cargo.toml, tests/main.rs
I noticed that for the test suite, clang spent almost 30% of its runtime parsing lib.h over and over again. By using a precompiled header, the compiler only needs to do that work once.
This reduces the test suite's runtime from 60 seconds to under 40 seconds on my computer.
We want to store each PCH file in a unique directory to prevent issues when multiple test suites are running in parallel. The way this temporary directory is created is a bit hacky. The proper way to do it is to use the `tempfile` crate, but it wants to pull in a bunch of dependencies.
This commit adds `lazy_static` as a dev dependency, which is needed because the various `test_foo` functions are run in parallel, so we need a thread-safe way to generate the PCH.
=> tests: Speed up test suite using precompiled headers

src/compiler.rs, src/typechecker.rs, tests/typechecker/missing_type_in_namespace.error, tests/typechecker/missing_type_in_namespace.jakt
Previously, we did a full typecheck of child namespaces before we checked any definitions in the parent scope. This meant we were prematurely trying to figure out things like function bodies before we even know what all functions and types were available.
With this PR, we now do typecheck of the namespace in two phases:
* Phase 1: the "predecl" phase. This establishes what declarations will be available in the namespace before they're actually fully checked.
* Phase 2: the "full" check phase. Here we finish checking the bodies of the definitions
With this, we now at least have the knowledge of what is in scope. This prevents an internal compiler panic when we mix namespaces, externs, and functions together in the same sample (as shown by the new test)
=> compiler+typechecker: Improve name resolution around namespaces

src/parser.rs
We don't need to spell out that we want a ParsedExpression::Operator in
every case. This also revealed that
BinaryOperator::NoneCoalescingAssign was missing in this list, so this
patch also adds a precedence for it.
=> Parser: Don't spell out outer enum every time in precedence()

editors/sublime/README.md, editors/sublime/sublime-for-yakt.sublime-syntax
Add syntax highlighting for Sublime Text. It should cover most of the 
syntax and any that might be introduced in the future. 
Instructions included in README.
=> editor: Add syntax highlighting for Sublime Text

runtime/Builtins/Array.h, runtime/Builtins/Dictionary.h, runtime/Builtins/Set.h
Currently using any iterator outside `main` generates invalid cpp since the `...Iterator` classes are in the `JaktInternal` namespace which `main` is also in but other functions are not. 
This change exposes them in the global namespace.
The problem was not detected by the tests since they all use `main` only. One way we could prevent such issues in the future is moving `main` from `JaktInternal` to a separate namespace. Does that sound like a good option?
=> runtime: Expose Iterator classes globally

README.md, src/codegen.rs, src/typechecker.rs, tests/typechecker/match_struct_like_enum_with_variable.jakt
Doing so just binds the named field with the field name into the match
scope.
=> typechecker: Allow omitting bound variable name on struct-like matches

selfhost/README.md, selfhost/main.jakt, tests/main.rs
This adds the `selfhost` compiler, the jakt compiler written in jakt. This lets us keep up with the latest main and ensure that main doesn't break the self-hosted compiler as both mature.
=> selfhost: Add the selfhost compiler and enable testing

runtime/lib.h, src/codegen.rs
This ensures main has the same access to identifiers as other functions.
This serves to prevent cases where generated code is incorrect when something is used outside of main and prevent bugs like the one #427 fixed.
=> runtime: Move main to a separate namespace

src/codegen.rs, tests/codegen/ns_level_circular_dependency.jakt
Now we can have multiple namespaces referencing each others' types and
functions without causing explosions on the C++ side.
=> codegen: Try really hard to resolve inter-namespace dependencies

samples/namespaces/namespace_struct.jakt, src/typechecker.rs
This changes the typechecker to return errors in more cases where they previously were being ignored. This uncovered an issue with one of the tests which wasn't properly using the correct shorthand and another test that assumed a different order to the typecheck.
I've also corrected the typechecker to check types first when it comes into a namespace, allowing inner namespaces to see those types.
=> typechecker: Bubble up errors in more cases

samples/enums/simple_constructor.jakt, selfhost/main.jakt, src/typechecker.rs, tests/typechecker/bad_simple_enum_constructor.jakt
`Enum::Variant` will parse to a NamespacedVar expression, but when we
don't find a variable, we'll now also look for an enum constructor
with the same name in the specified scope.
=> typechecker: Allow `Enum::Variant` as alias for `Enum::Variant()`

runtime/AK/Error.h, runtime/AK/Variant.h
This brings the compile time of the selfhosted impl from an average of
7.5s down to 4.7s, we should probably skip generating Variants for enums
in the near future as most of the compilation is spent instantiating the
58 (!) different function calls needed to visit these enum cases.
=> runtime: Remove some unused chunks of Variant to help compilation times

selfhost/main.jakt, src/parser.rs, tests/parser/match_bare_literals.jakt
parser: Allow bare literal match cases
Before:
match x {
(1) => ...
(2) => ...
else => ...
}
After:
match x {
1 => ...
2 => ...
else => ...
}
=> parser: Allow bare literal match cases

samples/enums/empty_enum.jakt, src/typechecker.rs
After parsing something like:
`enum Foo { }`
a C++ error was visible. Now we check if an enum is empty and show a Jakt error with a hint.
Also add a test for this behaviour.
=> parser+tests: Show an error if an enum is empty

README.md, editors/vim/syntax/jakt.vim, editors/vscode/syntaxes/jakt.tmLanguage.json, samples/match/match_block_yield.jakt, samples/match/match_pattern_or.jakt, src/codegen.rs, src/parser.rs, src/typechecker.rs, tests/typechecker/block_yield_type_mismatch.jakt, tests/typechecker/block_yield_unobservable_if.jakt, tests/typechecker/block_yield_unobservable_stmt.jakt, tests/typechecker/yield_inside_defer.jakt
```rs
match cut(.life) {
Into | Pieces => this is MyLastResort
Suffocation | No(breathing) => {
if .cut(.arm) and .bleeding { return not give("a fuck") }
yield this is MyLastResort
}
// I got bored
}
```
=> Everywhere: Allow yielding values from blocks in select places / parser: Allow specifying multiple patterns before '=>' in match cases

editors/vscode/.eslintignore, editors/vscode/.eslintrc.js, editors/vscode/.vscode/extensions.json, editors/vscode/.vscode/launch.json, editors/vscode/.vscode/settings.json, editors/vscode/.vscode/tasks.json, editors/vscode/client/package-lock.json, editors/vscode/client/package.json, editors/vscode/client/src/extension.ts, editors/vscode/client/src/test/completion.test.ts, editors/vscode/client/src/test/diagnostics.test.ts, editors/vscode/client/src/test/helper.ts, editors/vscode/client/src/test/index.ts, editors/vscode/client/src/test/runTest.ts, editors/vscode/client/testFixture/diagnostics.txt, editors/vscode/client/tsconfig.json, editors/vscode/package.json, editors/vscode/scripts/e2e.sh, editors/vscode/server/package-lock.json, editors/vscode/server/package.json, editors/vscode/server/src/server.ts, editors/vscode/server/tsconfig.json, editors/vscode/tsconfig.json
This adds a basic error reporting pass that calls out to `jakt` and parses the errors the compiler gives back.
It doesn't yet give proper spans, and only highlights the first character of the span.
=> vscode: Add error reporting to vscode extension

editors/vscode/syntaxes/jakt.tmLanguage.json
"ref" keyword is now replaced with "boxed" in the Jakt source code.
=> editors: Update vscode syntax from ref to boxed enum

editors/vscode/package-lock.json, editors/vscode/server/package.json, editors/vscode/server/src/server.ts, src/compiler.rs, src/lib.rs, src/main.rs
Improves error reporting for VSCode (and improves experience for other editors):
* Adds a `check-only` mode to the compiler, so we aren't generated C++ we don't need if we only care about type errors
* Adds a JSON error mode to make parsing errors much easier for editors
* Updates the VSCode extension to use the JSON errors
=> vscode+compiler: Better vscode errors

editors/vscode/syntaxes/jakt.tmLanguage.json, samples/apps/json.jakt
AK noticed this whilst working on the JSON video, straight-forward fix.
=> vscode: fix comment highlighting in enum block

src/codegen.rs, tests/codegen/generic_class.jakt
Fix incorrect type name generation when using templated classes.
Addresses issue #428.
=> codegen: Fix incorrect type name when using template class

src/parser.rs, tests/parser/yield_not_used_in_block_from_defer.jakt, tests/parser/yield_not_used_in_block_from_try.jakt
Previously it would panic in codegen when it noticed there are no
entered yieldable blocks.
=> parser: Only allow yield to be used inside a block

src/parser.rs
```
return {1:1}
}
```
Make code above error out instead of infinitely looping.
=> Parser: Fix infinite loop in `parse_set()`

src/typechecker.rs, tests/typechecker/array_negative_c_int.jakt
Before we couldn't typecast negative constants to c_int.
This fix makes it so now we can do things like `-1 as! c_int`.
Fixes #465.
=> typechecker: Added cint type id to negate

editors/vscode/package-lock.json, editors/vscode/package.json, editors/vscode/server/src/server.ts, src/compiler.rs, src/ide.rs, src/lexer.rs, src/lib.rs, src/main.rs, src/parser.rs, src/typechecker.rs
This adds a new `ide.rs` file that handles IDE support calls, which you can reach from new flags in `main.rs`
The first of these is "goto def", the ability to jump to the definition side for a given location in the file. This should be considered rudimentary for now, but hopefully should be good enough to help location areas for the definition or near the definition.
I've added "goto def" support in VSCode and turned it on my default. This will require a build of the compiler with the new flag in the path to work properly.
=> all: Add IDE support file, add goto-def support to compiler and VSCode

editors/vscode/server/src/server.ts, src/compiler.rs, src/ide.rs, src/lib.rs, src/main.rs
This adds support for typename on hover and dot (`.`) completions to the compiler and VSCode.
Typenames are still rudimentary and display the typename we would show in the terminal.
Completions are triggered via `.` and currently intended to retrieve fields and method names from a structure.
=> all: Add hover and dot completion support

editors/vscode/server/src/server.ts
Simple yet effective way to get field and function completions separately:
=> vscode: Separate function and field autocompletions

editors/vscode/server/src/server.ts, src/ide.rs, src/parser.rs
This fixes the incorrect span calculations in VSCode, which was counting characters but the compiler was counting bytes.
Also found an incorrect span in the parser and went ahead and fixed that as well.
=> parser+vscode: Fix incorrect span calculations

src/ide.rs, src/parser.rs, src/typechecker.rs
Some improvements:
- We now keep blocks with parse errors instead of wiping them. That allows you to use autocompletion in more places, even when the surrounding code is broken.
- Call spans are extended to the right `)`. This allows autocomplete to trigger on `foo().` where `foo()` returns something that supports dot access.
- Enum-scoped functions are now considered for autocompletion when doing dot access on a value of some enum type.
=> Improvements to IDE auto-completion

src/typechecker.rs, tests/typechecker/constructor_with_different_generic_instance.jakt
This renames builtin/common typenames to something more readable. 
Eg) instead of `Array<Foo>` we now show the shorthand `[Foo]`
=> typechecker: Improve typenames for common types

editors/vscode/package.json, editors/vscode/server/src/server.ts, src/ide.rs, src/lib.rs, src/main.rs, src/typechecker.rs
Adds support for "goto type definition", which allows you to go to where the type is defined for the given symbol.
There are a few heuristic steps we take that languages like Rust also take: if it's a common container type like Array, we don't actually care about the type definition for arrays, we care about the type the array contained. For cases like this, we jump to the contained type instead.
Also bumped the vscode extension to 0.0.3 since we made so many changes would be nice to know which version people are using.
=> all: Add support for goto type definition

selfhost/main.jakt
This patch adds an Arrow token to the lexer. Previously, the function parser was taking a Minus token and a GreaterThan token and combining them, but this should be the perview of the lexer.
=> Add "->" token to selfhost lexer

selfhost/main.jakt
Some work towards struct and class support. This does *not* include parsing member access, so most of the samples/tests for structs and classes will still fail to compile. But, I figured it was better to get this submitted sooner rather than later to not hold anyone else up.
This is my first contribution to the self-hosted compiler/using Jakt, so I'm 100% sure I've done some things wrong/weirdly, so don't hesitate to tell me. :^)
=> selfhost: Parse structs and classes

samples/functions/fat_arrow.jakt, selfhost/main.jakt
Parse the fat arrow token, and the following expression.
Make a new block and set the parsed expression as the only
statement so that return type inference can operate on the block.
=> selfhost: Parse fat arrow in function definition

editors/vscode/syntaxes/jakt.tmLanguage.json, samples/enums/is_variant.jakt, selfhost/main.jakt, src/codegen.rs, src/typechecker.rs, tests/typechecker/enum_is_variant_generic_unimplemented.jakt, tests/typechecker/enum_is_variant_nonexistent.jakt
This replaces `match enum { Variant => true, else => false }`.
=> typechecker+codegen: Implement the basic form of 'enum is Variant'

selfhost/main.jakt, src/parser.rs, src/typechecker.rs
This adds operator precedence parsing to the selfhost compiler.
Also fixed the parser to allow newlines between the case matches as well as fix a zero-index panic in the typechecker when the variant doesn't have a name yet.
=> selfhost+typecheck+parser: Add support for operator precedence parsing

runtime/lib.h, src/codegen.rs, tests/codegen/control_flow_inside_match.jakt, tests/codegen/control_flow_inside_nested_match_block.jakt
Refactored `ExplicitValueOrReturn` -> `ExplicitValueOrControlFlow`
with `LoopContinue` and `LoopBreak` as new variants, and now there
are three macros that exist to handle those values: one with just
`return` (for codegen places outside loop) and one with `return`,
`continue` and `break`, as well as another one that returns the same
control flow information by using `return LoopBreak` and 
`return LoopContinue` for instances where matches are 
nested.
Codegen has been updated to track whether `continue`/`break` is
allowed in the context of the code that's being generated and whether
it should use a `return LoopBreak` or `return LoopContinue` when
generating `Break` and `Continue` statements, since matches run through
lambdas and we have to return that control flow information to the …
=> runtime+codegen+tests: Support `continue`/`break` inside matches

selfhost/main.jakt
General code cleanup in the selfhost'd compiler
Also, started to use the new `break` in `match` feature, which cleans up more.
=> selfhost: Code cleanup, using new features

selfhost/main.jakt
A bit more code compression
For functions whose bodies are a single match statement, use the fat arrow syntax to immediately match. This lets us prevent one indentation we don't need.
=> selfhost: Code cleanup of match body functions

selfhost/main.jakt
This ports definitions over from the Rust-based compiler for the typechecker.
Had to rename a few enums so they didn't clash unfortunately.
Also - started the process of moving vardecls and inferences into the global list of definitions so that a) IDE support will be easier to write and b) inference has one place where we indirect to the type. This lets us update the inference without having to change the type. This should make unification easier in the future.
=> selfhost: Start typechecker by porting definitions

src/codegen.rs, src/typechecker.rs, tests/typechecker/format_throws.jakt
Made the typechecker mark `format` as `throws` because `runtime/lib.h`
declares `String::format` to return `ErrorOr`.
Removed the generation of `TRY` from codegen since it's now
marked as `throws` by the typechecker.
Fixes #517.
=> typechecker+codegen+tests: Mark `format` as `throws`

editors/vscode/syntaxes/jakt.tmLanguage.json
Previously the keyword `namespace` would be gray in namespace declarations, now it is treated as a keyword in a similar way to struct definitions.
Before this commit:
Now:
=> editors/vscode: Add syntax highlighting for namespace declarations

editors/emacs/README.md, editors/emacs/jakt_mode.el, editors/emacs/test.jakt
This PR adds an emacs major mode for highlighting syntax and indentation. I've tried my best to highlight all keywords by looking at jakt extensions for other editors. The indentation offset defaults to 4 and can be changed by the user if need be.
=> editors: Add syntax highlighting for emacs

selfhost/main.jakt
Previously, when parsing a statement, if the parser encountered an unknown token it would return garbage without advancing the index. This lead to infinite loops namely when parsing blocks. This commit fixes this by incrementing the index when generating a `Garbage` expression.
Before this commit, running `samples/basics/error.jakt` would result in an infinite loop, now it produces the expected error output.
`samples/basics/error.jakt:`
```jakt
!@#$!@@#%#$@
}
```
Before this commit: Infinite loop
Output after this commit:
```Error: unknown character: @
----- samples/basics/error.jakt:5:6
4 | function main() {
5 |     !@#$!@@#%#$@
^- unknown character: @
6 | }
-----
Error: unknown character: #
----- samples/basics/error.jakt:5:7
4 | function main() {
5 |     !@#$!@@#%#$@ …
```
=> selfhost: Prevent infinite loops due to unhandled tokens in blocks

editors/vscode/syntaxes/jakt.tmLanguage.json
The only primitive type not being highlighted in the TextMate grammar before was `void`.
=> editors/vscode: Add syntax highlighting for `void`

editors/emacs/README.md, editors/emacs/jakt_mode.el
Also, fix installation instruction in readme.
=> editors/emacs: Add syntax highlighting for `void`

samples/math/too_small_literal.jakt, samples/modules/a.jakt, samples/modules/b.jakt, samples/modules/basic_modules.jakt, samples/modules/sub_modules.jakt, src/codegen.rs, src/compiler.rs, src/ide.rs, src/lexer.rs, src/main.rs, src/parser.rs, src/typechecker.rs, tests/main.rs
Adds basic module support to typecheck and codegen.
The project is now split into modules and every id now has the module it comes from. Codegen generates the code for each module and wraps it in a namespace. The only module that doesn't get a namespace is prelude (which is its own module).
=> parser+typechecker+codegen+tests: Basic module support

editors/vim/syntax/jakt.vim
This fixes void not being highlighted in vim.
=> editors/vim: Add syntax highlighting for void

selfhost/main.jakt
This commit fixes a small bug where parsing expressions with no right-hand side would produce garbage. Previously, `parse_operator` would return a `ParsedExpression(BinaryOperator::Garbage)` when parsing an expression that isn't binary. This meant that it wouldn't actually get treated as a garbage `ParsedExpression` and would skip the checks for Garbage in `parse_expression()`. Additionally, when the result of parsing an operator returns garbage it shouldn't increment the index whcih this commit resolves as well.
With this commit parsing `samples/basics/hello.jakt` happens successfully whereas previously it would error:
Before this commit:
```
token: Token::Eol(JaktSpan(start: 51, end: 52))
token: Token::Function(JaktSpan(start: 52, end: 60))
token: Token::Identifier(name: "main", span: …
```
=> selfhost: Parse function calls properly

selfhost/main.jakt
This commit allows the parser to understand `Some`. While implementing this a small bug appeared in `parse_operand_base`'s handling of `LParen` where it wouldn't return the contained expression.
Previously, the parser would generate a `ParsedExpression::Call` for `Some` whereas it should be making an `OptionalSome`.
=> selfhost: Handle parsing `Some`

selfhost/main.jakt
The data structures ended up a little bit different from the baseline
compiler, to make the parsing code easier to follow.
=> selfhost: Parse `match` expressions

selfhost/main.jakt
After the recent addition of the `mut` variable syntax, some of the old parsing code for variables was no longer working. Most notably, any variables declared with `mut` would cause the parser to get into an infinite loop since the token wasn't being handled.
=> selfhost: Parse new `mut` keyword properly

selfhost/main.jakt
This patch adds parsing for single quoted strings `'a'` and byte strings `b'a'`.
With this, "tests/parser/byte_with_escape.jakt" parses; and no longer loops infinitely.
=> selfhost: Parse single quoted strings and byte strings

editors/vim/syntax/jakt.vim
Change vim syntax highlighting as well to correspond to the new Jakt syntax.
=> editors: Rename mutable to mut in vim syntax

selfhost/main.jakt, src/codegen.rs, src/typechecker.rs
This fixes a few breakages in module imports:
* Fix suggested improvement on the PR that I missed had subtle differences with the original. Now it no longer does early returns and imports all kinds of definitions that match the name
* codegen workaround when a call is behind a namespace and a module
* fix for selfhost unit test that didn't catch build break. Now selfhost should be again tested as a unit test
=> all: Fix breakage in module imports

selfhost/lexer.jakt
This token did not exist, so the `namespace` keword in
samples/namespaces/hello_namespace.jakt was parsed as an identifier.
Adding this token and adding it to the list of keywords fixes this.
=> selfhost: lexer: add token for `namespace` keyword

selfhost/main.jakt
The ParsedNamespace struct is adjusted to bring it closer to its
rust equivalent, and the parse_namespace function gains support for
parsing further namespaces (anonymous or not).
=> selfhost/parser: Add support for parsing namespaces

selfhost/main.jakt
This patch enables the selfhost compiler to parse all enums
in samples/enums/parse.jakt and samples/enums/recursive_enums.jakt.
We still cannot parse all of recursive_enums.jakt because of the
match statement, but we can parse all of the enums. :^)
=> selfhost: Parse enums

selfhost/parser.jakt
We can now parse all of the enum samples and we
report the correct errors for all of the enum tests. :^)
=> selfhost: Finish parsing enum

selfhost/lexer.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/utility.jakt
- Add a Lexer::lex() helper function that gives you back an array of tokens.
- Create a single array to contain errors and have the lexer and parser fill it with errors.
And also...
- Add copyright headers to self-hosted compiler
As always, everyone is encouraged to add themselves when making substantial contributions to the code. :^)
=> selfhost: Simplify main() somewhat + add copyright headers

selfhost/typechecker.jakt
Got a start on binary operator checking though had to shave a few yaks.
Yaks shaved:
* Moved all Ids to including the module ids, like we do in the rust compiler
* Added helpers to track down the definitions using these Ids
* Added typename builder
* Added helper functions for builtin types
* Added TypeId comparison method for comparing two types
* Started creating a unification function all type compatibility can run through
* Finally actually started adding binary operations typechecking
=> selfhost: More binary typechecking, module ids, typenames

selfhost/main.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, src/parser.rs
This gets rid of the awkward "with" that was previously used to mark
the start of an import list. The list is now wrapped in curlies instead.
The module is specified first, to allow IDE auto-completion to provide
relevant suggestions as soon as possible.
Before:
import module with symbol1, symbol2
After:
import module { symbol1, symbol2 }
=> parser: Tweak `import` syntax to use curlies for import lists

selfhost/lexer.jakt, selfhost/parser.jakt
A new token for the `as` keyword is added, and the parser is adjusted
to recognize it during the check for postfix operators. A new UnaryOperator
Typecast is added to represent the result of parsing.
=> selfhost/lexer+parser: Add support for parsing typecasts

src/codegen.rs
Left this in accidentally, it's no-longer necessary here and just generates extra noise.
=> codegen: Remove unnecessary extra pre-declarations

selfhost/main.jakt, selfhost/parser.jakt
You can now re-enable dumping the tokens from the lexer, using the `-l`
flag, and for consistency's sake the dumping of the final parsed
namespace is also toggled by a flag (`-p`).
If neither option is passed, then the compiler simply prints nothing and
returns zero if it was successful, or prints the errors and returns one if
there were issues with the code.
=> selfhost: Add basic CLI to selfhosted compiler

selfhost/typechecker.jakt
Moves some of the helpers around, adds `find_struct_in_prelude` helper and adds assignment typechecking.
=> selfhost: Port assignment checking

selfhost/parser.jakt
Increment the token index when finding an unexpected token on operator, struct/class and function parsing.
To prevent spamming error messages, we now have a flag to know whether  error has already been reported in the current state.
This is a hack to mimic the way the bootstrap compiler works and isn't implemented everywhere it should.
This patch also changes some class/struct error messages to display the correct declaration type.
Also, should we report every error we encounter when running in "language server" mode?
=> selfhost: Prevent infinite looping on error reporting

editors/vscode/syntaxes/jakt.tmLanguage.json
Image for reference: https://imgur.com/a/WE9i53U
This makes underlined words from section 1 "variable.field.enum.jakt". Words from section 2 are "entity.name.type.enum.jakt" (no change here).
The only thing I'm not sure is, if underlined words in sections 1 and 2 should be both "variable.field.enum.jakt" or "entity.name.type.enum.jakt", or the way it is on the screenshot, or maybe even something else.
Marking them both as a type makes some sense, but I don't like (a bit) how it looks after that: https://imgur.com/a/Bi7fLcx
Apart from enum highlighting, this also fixes
`function Foo() throws {`
where `throws` was not highlighted but when we had something like:
`function Foo() throws -> String {`
it was highlighted.
Before: https://imgur.com/a/GWTI2V5
After: https://imgur.com/a/jdW8Fu7
=> vscode: Fix enum and function that `throws` highlighting

editors/vscode/syntaxes/jakt.tmLanguage.json
Should work with the current `as?` and `as!` highlighting.
=> vscode: Add syntax highlighting for "import" and "as"

runtime/prelude.jakt, samples/apps/cat-std.jakt, samples/apps/cat.jakt, samples/apps/crc32.jakt, samples/apps/json.jakt, tests/main.rs
This PR allows `cat.jakt`, `crc32.jakt`, and `json.jakt` to compile & run again. It also now tests that these apps at least compile and output their help message.
=> runtime+tests: Fix and test the apps

editors/nano/jakt.nanorc
The previous syntax highlighting regex was exceeding the string
quotes, which made the variables or function names have the same
color as the string. With this change the color for string syntax
highlighting remains inside the quotes as it should.
=> editors/nano: Enhance string syntax highlighting

editors/vim/README.md
Many folks use a package manager like vim-plug these days, it's
much easier to maintain a portable vim config this way as well.
Lets provide instructions on how to use one with the Jakt vim plugin.
=> editors/vim: Add installation directions for `vim-plug`

selfhost/error.jakt, selfhost/lexer.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/utility.jakt
Similar to `error.rs` in the boostrap compiler `error.jakt` contains
the code for the `JaktError` enum and for printing error messages.
This code was cluttering up the top of `lexer.jakt` so it is much
nicer to have a proper home for it.
Note: this did require moving the `Span` struct out of the lexer.
Since the error code and lexer both need the span, and the lexer
also needs the error code, `Span` was moved into `utility.jakt`
at least for the time being until we are able to handle circular
imports. Not completely ideal, but I think the improvements to
`lexer.jakt` are worth it.
=> selfhost: Add `error.jakt` file and move error code there

samples/generics/generic_static_with_explicit_types.jakt, samples/tuples/namespaced_values.jakt, selfhost/parser.jakt
This implements all of the `todo()`s that were in `selfhost/parser.jakt` :^)
=> selfhost/parser: Implement some `todo()`s

selfhost/error.jakt
The error code was written before enums supported member functions.
the `severity_name` and `ansi_color_code` functions were clearly
meant to be members of the `MessageSeverity` enum. Now that such
functions are supported, lets use them :^)
=> selfhost/error: Use member instead of free functions for `MessageSeverity`

selfhost/parser.jakt
Since classes structs and enums all have a `name`, a `name_span`,
`generic_parameters`, `methods`, etc. and all represent user defined
types it makes sense for them to be combined into a single type to
reduce code duplication.
This change gets rid of `ParsedEnum` and `ParsedStruct` and replaces
both of them with:
```
struct ParsedRecord {
name: String
name_span: Span
generic_parameters: [[String:Span]]
definition_linkage: DefinitionLinkage
methods: [ParsedMethod]
record_type: RecordType
}
```
where `record_type` is one of these:
```
enum RecordType {
Struct(fields: [ParsedField])
Class(fields: [ParsedField], super_class: ParsedType?)
ValueEnum(underlying_type: ParsedType, variants:[ValueEnumVariant])
SumEnum(is_boxed: bool, variants: [SumEnumVariant])
Garbage
}
```
Splitting structs and …
=> selfhost/parser: Unify classes structs and enums as `ParsedRecord` type

selfhost/parser.jakt
The `parse_operand_postfix_operator` function would only attempt
to parse a single postfix operator, so if there were multiple e.g.
`index++ as? u32` or `Namespace::Variable++` only the first would be
consumed and the parser would then choke on further operators.
This was fixed by simply looping the process of trying to parse a
postfix operator and glomming it on to the current expression until
a token that is not a postfix operator is found and the expression is
returned.
The diff looks really nasty because git tries very hard to find lines
in common even when there are none because of indentation changes, but
essentially all that happened is that the code was indented twice (once
to turn it into a proper function, and twice to wrap it in a loop) and
a bit of code was added at the …
=> selfhost/parser: Fix parsing of multiple postfix operators

selfhost/main.jakt, selfhost/typechecker.jakt, src/codegen.rs, src/parser.rs
This connects the typechecker to the selfhost (with a couple workarounds for C++ codegen limitations)
It also fixes a couple infinite loops in the rust parser. As well as fixing codegen so that it was deterministic (using BTree* containers instead of Hash* containers)
Closes #613
(another attempt at fixing codegen to be deterministic)
=> selfhost+parser: Connect typechecker to selfhost

runtime/prelude.jakt, samples/arrays/reference_semantics.jakt, samples/basics/bubble_sort.jakt, samples/dictionaries/reference_semantics.jakt, samples/generics/generic_types.jakt, samples/sets/reference_semantics.jakt, samples/structs/value_semantics.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, src/parser.rs, tests/typechecker/type_predecl_visibility.jakt
Previously, the format was `[anon] foo: [mut] Bar`. This changes that to `[anon] [mut] foo: Bar`, which is consistent with mutable variable declarations.
Also, removed a redundant field, added some error checking for where the `anon` and `mut` keywords can appear in a parameter declaration, and fixed a bug.
=> all: Move `mut` to before parameter names

runtime/Jakt/String.h, runtime/Jakt/StringBuilder.h
The "alternative form" was not being propagated in the `NonnullRefPtr` formatter, preventing class types (and other ref-counted objects) from being pretty printed.  This PR fixes that.
=> runtime: Allow pretty printing class types

selfhost/parser.jakt
The variants parser didn't advance the index when the variant that it
encountered was just a name:
```jakt
enum DefinitionLinkage {
Internal
External
}
```
It also couldn't differ between an unclosed enum and getting EOF after
closing it since it advanced the index before breaking on `RCurly`. Now
the `RCurly` check is done at the end of the loop, and it is not skipped
inside the loop.
=> selfhost/parser: Avoid infinite loop in enum variants parser

selfhost/lexer.jakt
This patch allows for `b'\n'` to be lexed as SingleQuoteByteString(quote: "\n", ...).
Previously, it was reading only the backslash and skipping the rest.
=> selfhost/lexer: Support escape character in byte literal

selfhost/lexer.jakt
With this patch the lexer can handle hexadecimal, octal and binary numbers
=> selfhost: Implement different number types

selfhost/parser.jakt
Classes which had their closing '}' just before the Eof were considered
incomplete by the parser.
While parsing class bodies the parser wil return instead of breaking the while loop to
handle this case.
Fixes #633
=> selfhost: Fix incomplete class definition error

selfhost/main.jakt
If you call the compiler with flags, the error printer would say that
the file name of where the error occurred would be the first flag.
=> main: Fix error printing when called with flags

samples/control_flow/return_nothing.jakt, selfhost/parser.jakt, src/codegen.rs, src/ide.rs, src/parser.rs, src/typechecker.rs, tests/parser/no_return_in_defer.jakt
Allow `return` with no argument in both baseline and selfhost.
=> all: Allow `return` without value

editors/nano/jakt.nanorc
I have noticed that import keyword was missing when syntax highlighting.
=> editors/nano: Add missing import keyword

editors/vscode/syntaxes/jakt.tmLanguage.json
This small change fixes a syntax highlighting issue in vscode. As shown in the image, the second function keyword previously didn't get highlighted correctly. This happened because with the rule `(?<=function.*?)(<)` the gerneric-aguments list started at the operator `<`, since we match everything with the `.` up until this point. There is no `>`, so we also never exit the (non-existent) generic argument list.
=> editor/vscode: Fix collition of generic argument opening and any `<`

selfhost/main.jakt
Passing `-h` will now print the possible flags and options similarly to
how the Rust implementation does.
The `usage()` and `help()` functions now return the usage and help strings
rather than calling `println()` and returning an integer. This allows for
the usage message to be printed to stdout when `-h` is passed rather than
to stderr. Ideally this would be done with global constant strings as in
the Rust compiler, however that is not currently supported(?).
=> selfhost: Add help to command line arguments

selfhost/main.jakt
Expands on #615, eliminating the match block in main that evaluated
command line arguments :^)
As well as fat-arrowing the `usage()` and `help()` string functions and exiting with error code 1 when no arguments or source files are passed.
=> selfhost: Tidy command line argument parsing with helper

selfhost/codegen.jakt, selfhost/typechecker.jakt
Currently handles the most basic of cases. You must specify the
typename on the variable and the initialization must match exactly.
=> selfhost/typechecker+codegen: Check and generate variable declarations

selfhost/typechecker.jakt
I expanded the existing type checking of variable declarations in the selfhosted compiler to get closer to functionality of the rust compiler.
The checking of builtin types is still missing and will require additional functions.
This is my first pull request, so I'd appreciate all the feedback I can get :^)
=> selfhost/typechecker: Expand type checking of variable declarations

src/typechecker.rs, tests/typechecker/struct_file_order.jakt
This patch adds a separate pass that populates all the `CheckedStruct`
field vectors before actually typechecking struct methods.
This ensures that methods can refer to fields in other structs, even
if those other structs occur after the current struct in file order.
=> typechecker: Typecheck all struct fields before looking at methods

selfhost/main.jakt, selfhost/parser.jakt
This PR adds a new static `parse` function to `Parser` (similar to `Lexer::lex`, `TypeChecker::typecheck`, and `CodeGenerator::generate`) and uses it in main instead of having main muck around with the internals of the parser directly.
=> selfhost: Use new `Parser::parse` function instead of `parse_namespace`

selfhost/main.jakt
`main.jakt` is importing a bunch of stuff that it no longer
(or never did?) need.
This patch removes the unnessecary imports and the result is a very
tidy top of the file :^)
=> selfhost: Clean up imports in `main.jakt`

selfhost/typechecker.jakt
Add the following implementations to type_name:
* TypeVariable
* RawPtr
* GenericInstance with a debug/todo stop-gap output until prelude is available, and the actual implementation for the prelude structs.
* Inference just as a TODO for easier debugging
Also the else branch now gives additional debug printing
until we know it is exhaustive/unreachable.
=> selhost/typechecker: Implement more of type_name

selfhost/typechecker.jakt
I left the error messages as in the rust version (one starting uppercase and once lowercase).
=> selfhost/typechecker: Check Throw

runtime/Jakt/Format.cpp
This fixes the serenity build by removing some ignore unused result
warnings. This broke after debe647c17a005d67c680e5d216c96a2a6297c08 .
=> runtime: Wrap StringBuilder::append..() with MUST() in serenity branches

samples/math/integer_promotion_bad.jakt, selfhost/typechecker.jakt
The rust compiler does not give a hint here, but I thought it might be nice to do so anyway. Especially since this is probably an issue that inexperienced programmers will run into primarily.
=> selfhost/typechecker: Add hint for integer promotion errors and add a test for it

selfhost/typechecker.jakt
assuming the short-circuit for finding structs in the prelude is fixed, this will enable the following program:
```
let x = [1, 2, 3]
println("{}", x[1])
}
```
=> selfhost/typechecker: Check arrays and indexed expressions

selfhost/parser.jakt, selfhost/typechecker.jakt
**selfhost/parser:**
Add ParsedGenericParameter with name and span, and replace [[String:Span]] with [ParsedGenericParameter] for easier handling in typechecker. 
(It is also self documenting)
**selfhost/typechecker**
Add generic_params:[FunctionGenericParameter] to CheckedFunction and check them in typecheck_function_predecl.
=> selfhost/parser+typechecker Check FunctionGenericParameters

selfhost/typechecker.jakt
Fixes https://github.com/SerenityOS/jakt/issues/636
Future improvements:
* For compile time constants, whether the integer is positive or not can be checked.
=> typechecker: Check array fill size expression is convertible to integer

src/typechecker.rs
Until now, we've been ignoring any typechecking errors that occur
in imported files. Since codegen didn't do any validation, this meant
that totally invalid programs could still build.
=> typechecker: Don't lose typechecking errors in imported files

selfhost/typechecker.jakt
Make sure the scope ScopeId(0, 0) is created when
Typechecker::typecheck() is called and that it does not have a parent.
=> selfhost/typechecker: Sanitize root scope

samples/modules/a.jakt, samples/modules/b.jakt, tests/main.rs
Fixes #666 
This addresses the problem where tests are implicitly skipped when they don't have expectations.
Tests will now fail if they are not marked as skipped and don't have any expectations.
We also test the selfhosted compiler. In that case we only want to test `main.jakt`.
Instead of marking all other selfhost files as `skip` I've changed the test to target `main.jakt` instead.
=> tests: Make skip explicit

jakttest/error.jakt, jakttest/jakttest.jakt, jakttest/lexer.jakt, jakttest/parser.jakt, jakttest/utility.jakt
This adds a simple jakt-based test runner. Currently it will:
* parse the sample file passed to it
* read the expected output/error
* run the jakt compiler against the sample
* redirect the stdout/stderr of the compiler to output files
* for success tests: runs the created binary and checks its output against the expected string
=> jakttest: Add a jakt-based test runner

runtime/prelude.jakt
It is rather too verbose to explicitly type 'key' and 'value'
as parameters in for example dict.set(key: name, value: age),
while it could be anonymized to be dict.set(name, age).
=> runtime: Make set() function for dictionary have anon parameters

selfhost/parser.jakt
We can now pass `samples/boolean/logical_and.jakt` :^)
=> selfhost/parser: Fix expression order of operations

selfhost/typechecker.jakt
The last `return` or `yield` statement of the function's block
becomes the return type of the function
=> selfhost/typechecker: Infer return type of function

.github/workflows/ci.yml
From what I can tell we don't seem to accept PRs that introduce warnings.
This makes sure CI fails on them so we can see warnings instantly.
=> ci: Deny warnings in CI

selfhost/main.jakt
Passing `-h` now shows our shiny new `-b` flag for building executables :^)
=> selfhost: Update `help()` with build flag

jakttest/jakttest.jakt, jakttest/run-all.sh, runtime/prelude.jakt, selfhost/error.jakt, src/codegen.rs, src/typechecker.rs
This adds support for testing error messages to jakttest. To do so, it touches a few areas:
* Adds `eprint` to the Rust-based compiler
* Adds string.contains to the Rust-based compiler
* Uses `eprint` and string.contains in the selfhost compiler to output error messages
* Adds support to jakttest to redirect these error messages and search for expected error messages
* Updates the test harness to also notice skipped tests so we see the number of skipped tests
closes #713
=> all: Add support for testing error messages to jakttest

selfhost/typechecker.jakt
There was a bug in find_namespace_in_scope() where we returned the
parent scope of the scope we were looking for instead of the scope
itself.
=> selfhost/typechecker: Fix find_namespace_in_scope() bug

src/typechecker.rs
In this case we're checking the yielded expression's type id against
the (known) match yielded type, and not viceversa.
Fixes #672.
=> typechecker: Flip lhs and rhs type ids in match expression typecheck

selfhost/typechecker.jakt
Remove Inference Type for now, until selfhost has reached parity with the rust version,  as discussed in #701.
current main branch:
```
82 passed
250 failed
7 skipped
```
this PR:
```
82 passed
250 failed
7 skipped
```
This PR + #701:
```
79 passed
253 failed
7 skipped
```
This PR + #701 + #716:
```
86 passed
246 failed
7 skipped
```
(#716 is still in review and has some open issues that need to be resolved, should be done today)
=> selfhost/typechecker: Remove Inference Type for now

jakttest/jakttest.jakt
I noticed that sometimes jakttest passes a test just because the expected output is empty, even when the compiler throws an error. Now we check what the compiler output is during SuccessTests to avoid this issue and get more accurate test results.
=> Jakttest: Check compiler output and errors on SuccessTests

selfhost/typechecker.jakt
This Implements the last big TODO left over by #701 and adds most of the type-checking to typecheck_block that exists in the rust version of the compiler, only one of the support functions has an optimization TODO.
It also adds the following on the way
* the Match expression
* a function to check if an expression definitely returns
* a function to check if statement definitely returns
* a function to check types for their compatibility
* a function to substitute type-vars in types 
**Before:**
```
75 passed
257 failed
7 skipped
```
**After:**
```
76 passed
256 failed
7 skipped
```
**This PR and #701**
```
81 passed
251 failed
7 skipped …
```
=> selfhost/typechecker: Implement most of typecheck_block

selfhost/typechecker.jakt
As far as I'm concerned, classes are seen & treated the same way
as structs by the typechecker (since their semantic difference only
takes place in codegen), therefore typecheck_struct and the like
should also be run on classes.
Maybe more information could be sent when calling those functions
so they know they're dealing with a class and output their messages
correctly, i.e substituting 'struct' for 'class' where possible.
=> selfhost/typechecker: Run `typecheck_struct_predecl` in classes as well

selfhost/typechecker.jakt
Implement all the TODOs in typecheck_function but 1:
* resolve concrete types
* second return type pass to resolve generics
* infer return type (if necessary)
* report error if control reaches end of non-void function
=> selfhost/typechecker: Implement Check Function TODOs but 1

selfhost/typechecker.jakt
Now you can get UNKNOWN_TYPE_ID from a single source of truth,
`unknown_type_id()`.
=> selfhost/typechecker: Unify `UNKNOWN_TYPE_ID`

selfhost/parser.jakt
`parse_struct_class_body` was already handling the closing RCurly, this
caused structs to have no methods and RecordType::Garbage as the
function was returning prematurely.
=> selfhost/parser: Remove check for eof while parsing struct

editors/vim/README.md
I could figure it out myself but I think it's going to be a nice
touch for new contributors.
=> meta/vim: Add install instructions for `packer.nvim` (neovim only)

selfhost/typechecker.jakt
The `format` builtin function returns String and could throw.
=> selfhost/typechecker: Set return type and throws for format function

selfhost/typechecker.jakt
Fix a bug where we did not update the struct_id when going through all
structs in a namespace and predeclaring them.
=> selfhost/typechecker: Fix struct_id bug in namespace_predecl

selfhost/lexer.jakt, src/lexer.rs
Previously when parsing a string, the lexer would just continue to eat characters until a closing quote or EOF was found. It did produce a correct error for such a case, however this meant it could possible consume a _lot_ of input if there were no more strings for a while. This commit makes the lexer stop parsing if a newline is encountered. 
This was causing issues for my IntelliJ plugin, here are the results of this change: 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Also,  better invalid char escape errors:
<details>
<summary>Before</summary>
<br />
Idk why there's no pretty error message for this one
</details>
<details>
<summary>After</summary>
<br />
</details>
=> lexer: Better string/char error handling

selfhost/typechecker.jakt
This PR allows type assigning `T` to `T?` and `weak T?`.
```
struct Foo {
i: i32?
}
Foo(i: 5i32)
}
```
```
function foo(i: String?) {
}
foo(i: "hi")
}
```
=> selfhost/typechecker: type check `T?` and `weak T?` with `T`

selfhost/lexer.jakt
Accept files where the last line ends in a space (' ') character.
Accomplished by returning a Token::Eof constructed in the same way
as used for normal Eof cases.
=> selfhost/lexer: Return from next() in case of Eof after whitespace

editors/vim/README.md, editors/vim/ftdetect/jakt.vim, editors/vim/lua/lsp.lua
When a jakt file is opened, the LSP server in
`editors/vscode/out/server/src/server.js` is spawned for the current
instance, and the buffer is attached to the client. Requires Nvim 0.7.2.
Before merging, it must be checked that:
since Neovim's Lua API might change in the future.
notifying if it's not there, before trying to start the client.
More yaks will be added to the stack if necessary.
=> neovim: Add LSP support for neovim

selfhost/codegen.jakt, selfhost/typechecker.jakt
This implementation of the `is` operator differs from the Rust implementation
of jakt, in that any valid type name is accepted as the rhs of the `is` operator.
=> typechecker+codegen: Add support for the `is` operator

selfhost/codegen.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
This PR adds a flag `-d` to the selfhosted compiler that will put comments into the C++ code that link to the span of the corresponding statement in the Jakt source file.
This will be helpful for debugging compile errors of the generated C++ code as well as debugging runtime errors :^)
Example output:
```C++
#include <lib.h>
namespace Jakt {
ErrorOr<int> main();
ErrorOr<int> main(Array<String>) {
{
const i64 x = static_cast<i64>(80LL); /* samples/control_flow/if4.jakt:5:5 */
if ((x == static_cast<i64>(100LL))) /* samples/control_flow/if4.jakt:7:5 */ {
outln(String("true")); /* samples/control_flow/if4.jakt:8:9 */
}
else if ((x == static_cast<i64>(80LL))) /* samples/control_flow/if4.jakt:9:12 */ {
outln(String("it is 80")); /* samples/control_flow/if4.jakt:10:9 */
}
}
return 0;
}
}
```
The …
=> selfhost/codegen: Add comments to the C++ code that link back to the original Jakt statement

selfhost/codegen.jakt, selfhost/typechecker.jakt
This adds support for codegen'ing the struct's constructor. With it, another 3 tests pass.
I also fixed a logic bug in the field typecheck to check the field name. With it, another tests passes.
Now:
```
119 passed
213 failed
7 skipped
```
=> selfhost+codegen: Add struct constructor codegen

selfhost/codegen.jakt, selfhost/typechecker.jakt
main (424c891)
```
[ FAIL ] samples/enums/recursive_enums.jakt
[ PASS ] samples/enums/one_line_enum_declaration.jakt
[ FAIL ] samples/enums/parse.jakt
[ FAIL ] samples/enums/is_variant.jakt
[ PASS ] samples/enums/empty_enum.jakt
[ FAIL ] samples/enums/recursive_enums_bad.jakt
[ FAIL ] samples/enums/methods.jakt
[ PASS ] samples/enums/underlying.jakt
[ FAIL ] samples/enums/simple_match.jakt
[ FAIL ] samples/enums/simple_constructor.jakt
[ FAIL ] samples/enums/methods_access_violation.jakt
```
after these commits
```
[ FAIL ] samples/enums/recursive_enums.jakt
[ PASS ] samples/enums/one_line_enum_declaration.jakt
[ PASS ] samples/enums/parse.jakt
[ FAIL ] samples/enums/is_variant.jakt
[ PASS ] samples/enums/empty_enum.jakt
[ PASS ] samples/enums/recursive_enums_bad.jakt
[ FAIL ] …
```
=> More enum samples

selfhost/typechecker.jakt
Search with given scopes module instead of the last scopes module that didn't have the namespace we were looking for.
=> selfhost/typechecker: Fix bug in find_namespace_in_scope

selfhost/main.jakt
Add `-r` "build and run" flag to selfhost compiler.
_(sjakt is my local alias for selfhost build/main)_
```
$ sjakt -h
usage: jakt [-h] [OPTIONS] <path>
Flags:
-h            Print this help and exit.
-l            Print debug info for the lexer.
-p            Print debug info for the parser.
-b            Build an executable file.
-r            Build and run an executable file.
-d            Insert debug statement spans in generated C++ code.
```
Example:
```
$ sjakt -r samples/basics/hello.jakt 
Well, hello friends.
```
Also split up the output filename and the cpp filename for a future `-o` option.
=> selfhost/main: Add "build and run" flag `-r`

jakttest/parser.jakt
For tests with an escaped quote, the expected value would have no quote
and the test would fail if the actual value had a quote
samples/structs/serialize_string_in_struct is the test that brought
this to my attention.
This in combination with #777 causes serialize_string_in_struct to pass
=> jakttest/parser: Handle escaped quotes

editors/vscode/syntaxes/jakt.tmLanguage.json
The syntax highlighting would break if a line had `enum` followed by `{`
in it, if it wasn't an actual enum declaration.
E.g. `if enum_id.has_value() {` would be falsely detected.
=> editors/vscode: Fix syntax highlighting for keyword enum

selfhost/typechecker.jakt
Use hashmap.get(...) instead of iterating over keys to find an item.
Potentially brings the runtime down from Omega(n) to O(1) :^)
=> selfhost/typechecker: Make better use of hashmaps

samples/variables/integer_promotion_bad3.jakt
As shown below the difference between integer_promotion_bad2.jakt
and integer_promotion_bad3.jakt is that a newline is missing, but
the code is identical in both of them. Hence deletion.
--- samples/variables/integer_promotion_bad2.jakt	2022-06-16 12:39:18.484476389 +0200
+++ samples/variables/integer_promotion_bad3.jakt	2022-06-16 12:39:18.484476389 +0200
@@ -1,5 +1,5 @@
/// Expect:
-/// - error: "Integer promotion failed\n"
+/// - error: "Integer promotion failed"
mut i: u8 = 0;
=> samples: Remove integer_promotion_bad3.jakt file

selfhost/typechecker.jakt, src/typechecker.rs, tests/typechecker/dict_with_void_keys.jakt, tests/typechecker/dict_with_void_values.jakt, tests/typechecker/dictionary_mismatching_value_types.jakt
_I hope this is not very bad form, but there is already a PR #782 that I reviewed as I was in the midst of cleaning up my own implementation to be up-streamed._
It is also the same as rust version without the type hint logic but with updated error messages. Test cases have been updated accordingly.
Before:
```
...
[ FAIL ] samples/dictionaries/contains.jakt
[ FAIL ] samples/dictionaries/count_words.jakt
[ FAIL ] samples/dictionaries/dict_index_unwrap.jakt
[ FAIL ] samples/dictionaries/dict.jakt
[ FAIL ] samples/dictionaries/empty_literal.jakt
[ FAIL ] samples/dictionaries/empty_literal_without_hint.jakt
[ FAIL ] samples/dictionaries/indexed.jakt
[ FAIL ] samples/dictionaries/iterator.jakt
[ FAIL ] samples/dictionaries/lvalue2.jakt
[ FAIL ] samples/dictionaries/lvalue.jakt
[ FAIL ] …
```
=> selfhost/typechecker: Add Dictionary check

selfhost/codegen.jakt, selfhost/typechecker.jakt
Typecheck and codegen match statements on expressions.
With these changes three additional checks pass :^)
before
```
157 passed
176 failed
7 skipped
```
after
```
160 passed
173 failed
7 skipped
```
=> selfhost/typechecker+codegen: Match expression

selfhost/codegen.jakt, selfhost/lexer.jakt, selfhost/main.jakt, selfhost/typechecker.jakt, src/codegen.rs, src/lexer.rs, tests/parser/multiline_string_with_double_quotes.jakt
This adds support to the selfhost compiler to include the prelude and get definitions from it. As a result, it's able to pass a few more tests.
```
162 passed
169 failed
7 skipped
```
This PR also:
* adds support for multiline strings
* removes a test that's no longer valid (that prevented multiline strings)
* improves a few error messages
=> all: Add support for prelude to selfhost

selfhost/codegen.jakt, selfhost/typechecker.jakt
Adds array support to the selfhost codegen based off the Rust-based compiler.
Also, fixed bug in type equality.
Now:
```
178 passed
153 failed
7 skipped
```
=> selfhost/codegen+typecheck: Add array support to selfhost

selfhost/codegen.jakt, selfhost/typechecker.jakt
@jntrnr I decided to work on the matches some more, but before I could push it you already merged the PR :D
This allows an additional test `match_block_yield.jakt` to pass, which means we now have 166 passing and 166 failing o.o
=> selfhost/typechecker+codegen: Pass on match result type and implement yield 

selfhost/typechecker.jakt
This carries the return type from the checked call to the method expression, helping to fix a few tests.
Now:
```
183 passed
148 failed
7 skipped
```
=> selfhost/typecheck: Add method return types, and generic methods calls

selfhost/codegen.jakt
This adds tuple codgen support, allowing us to pass a few more tests:
Now:
```
187 passed
144 failed
7 skipped
```
=> selfhost/codegen: Add support for tuples

jakttest/jakttest.jakt, jakttest/run-all.sh
**_This depends on #771 to be merged first._**
Combine the compile and run steps into one by using the new `-r` "build and run" compiler flag introduced with #771.
Instead of writing the given jakt source file to output.jakt use it directly, which also enables the testing of applications that use imports.
Don't try to remove files that are no longer generated in run-all.
=> jaktest: Simplify, speed up and enable imports

selfhost/parser.jakt, selfhost/typechecker.jakt, src/typechecker.rs, tests/typechecker/set_mismatching_value_types.jakt, tests/typechecker/set_with_void_values.jakt
As the name suggests we now parse and typecheck sets. With this there are three additional tests passing:
```
samples/sets/empty_literal_without_hint.jakt
tests/typechecker/set_mismatching_value_types.jakt
tests/typechecker/set_with_void_values.jakt
```
Generating code for sets does not make much sense right now, since all other tests rely on method calls which don't work yet. So the compiler never gets past the typechecking phase.
=> typechecker+tests+selfhost/parser+typechecker: Parse and typecheck sets

jakttest/run-all.sh
Same as was done in  #767 for jakt, but this time for jakttest.
Minor adjustment to only check for `.jakt` files and fix of the info message.
=> jakttest: Recompile jakttest if it is not up-to-date

selfhost/codegen.jakt, selfhost/typechecker.jakt
This change adds support for typechecking and generating boxed enums. The `samples/enums/recursive_enums.jakt` sample still does not pass because we need support for `produce_codegen_dependency_graph` which relies on the `BTreeMap` and `BTreeSet` data structures.
when I manually put the generated code in the correct order, the test passes. :^)
Update: I finished the dependency graph and now more tests pass
```
[ PASS ] samples/enums/recursive_enums.jakt
[ PASS ] samples/enums/one_line_enum_declaration.jakt
[ PASS ] samples/enums/parse.jakt
[ PASS ] samples/enums/is_variant.jakt
[ PASS ] samples/enums/empty_enum.jakt
[ PASS ] samples/enums/recursive_enums_bad.jakt
[ FAIL ] samples/enums/methods.jakt
[ PASS ] samples/enums/underlying.jakt
[ FAIL ] samples/enums/simple_match.jakt
[ PASS ] …
```
=> selfhost/typechecker+codegen: Generate boxed enums

selfhost/codegen.jakt
```diff
++ [ PASS ] samples/imports/import_alias.jakt
++ [ PASS ] samples/imports/import_alias_list.jakt
++ [ PASS ] samples/imports/valid_import.jakt
++ [ PASS ] samples/namespaces/namespace_struct.jakt
```
Before (7a5a0e03b129260c506028b7bc37fa01cb62db89):
```
203 passed
129 failed
8 skipped
```
After:
```
207 passed
125 failed
8 skipped
```
=> selfhost/codegen: Hacky AK Formatter fix

jakttest/run-all.sh
The macOS version of `stat` uses different flags for formatting the
output. Check the OS type and set the flags accordingly.
=> jakttest/run-all: Use different format flags on macOS

selfhost/codegen.jakt, selfhost/typechecker.jakt
This fixes a misalignment in the method arg/param checking that allows more methods to successfully pass. This is part of the work to enable set methods to start working.
Before:
```
223 passed
109 failed
7 skipped
```
After:
```
232 passed
100 failed
7 skipped
```
=> selfhost/codegen+typecheck: Fix method checking and set codegen

selfhost/typechecker.jakt
* Fix "internal error: Method call on unsupported base Type::I64" in `samples/ranges/range.jakt`
=> selfhost/typecheck: Fix Range typecheking

runtime/Jakt/String.cpp, runtime/Jakt/String.h, runtime/Jakt/StringUtils.cpp, runtime/prelude.jakt, selfhost/codegen.jakt
This adds the `replace` method to the String runtime and then uses it to add support for inline cpp codegen.
Before:
```
239 passed
93 failed
7 skipped
```
After:
```
241 passed
91 failed
7 skipped
```
=> selfhost+runtime: Add support for inline cpp codegen

selfhost/typechecker.jakt
Make the sample generate code by setting up all the structure generics into
`generic_inferences` and call `substitute_typevars_in_type` for the function
return type
=> selfhost/typechecker: Make `samples/ranges/range.jakt` pass

selfhost/typechecker.jakt
Makes `tests/typechecker/throw_without_throws_function.jakt` pass
=> selfhost/typechecker: Fix typo in error message

editors/vscode/server/src/server.ts, src/main.rs
-v is currently used by --version. This caused hover to fail because of
argument ambiguity.
=> main+editors/vscode: Change hover argument from -v to -e

editors/vscode/server/src/server.ts, src/main.rs
This PR add support for "go to file" when declaration is in another (imported) source file. Note that this doesn't work for prelude types (e.g String, Error, File etc.)
=> editors/vscode: Implement goto-ing to `import`ed files

selfhost/parser.jakt
This adds a pass for the test at samples/control_flow/if_else_identical_error.jakt
In order to compare the ParsedBlocks, I had to add the equals function to the following Enums:
- ParsedBlock
- ParsedStatement
- BinaryOperator
- UnaryOperator
- ParsedExpression
- ParsedCall
Turns out is very ackward at the moment to compare Enum variants, so the code got a bit verbose.
=> selfhost/parser: Error when if and else are identical

selfhost/parser.jakt
Fix error message for Array literals with more than one expression.
Before:
`[ FAIL ] tests/parser/multiple_expressions_in_array.jakt`
After
`[ PASS ] tests/parser/multiple_expressions_in_array.jakt`
=> selfhost/parser: Fix error message for Array literals

jakttest/run-all.sh
run-all.sh script doesn't check for if selfhost binary is
already built when comparing if it is updated or not. This
results with tests failing without ever using the selfhosted
binary. Building selfhost before running the tests fixes
the issue.
=> jakttest: Build selfhost if binary does not exist

selfhost/lexer.jakt, selfhost/parser.jakt, src/lexer.rs, tests/parser/invalid_digits_in_binary_number.jakt, tests/parser/invalid_digits_in_octal_number.jakt
This PR makes every test in tests/parser pass :^)
before:
```
256 passed
78 failed
7 skipped
```
after:
```
260 passed
74 failed
7 skipped
```
=> tests+lexer+selfhost/lexer+parser: Fix some small bugs

selfhost/typechecker.jakt
This PR adds a pass for the /tests/typechecker/match_non_exhaustive.jakt test
Before::
259 passed
74 failed
7 skipped
After:
260 passed
73 failed
7 skipped
=> selfhost/typechecker: Adds a PASS match_non_exhaustive.jakt

selfhost/codegen.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
I haven't met my original goal of making `samples/generics/generic_fun.jakt` succeed, but that turned out to be a much deeper yak-hole than I anticipated. :sweat_smile: 
The last commit causes an infinite loop in `substitute_typevars_in_type()`, so leaving this as a draft until that's figured out.
=> selfhost: Work on generic functions

selfhost/typechecker.jakt
This adds a PASS for tests/typechecker/match_exhaustive_catchall.jakt
Before: 
265 passed
68 failed
7 skipped
After:
266 passed
67 failed
7 skipped
=> selfhost/typechekcer: Adds a PASS for match_exhaustive_catchall

selfhost/utility.jakt
If the compiler is invoked on a file without a leading directory like
`jakt test.jakt`, the output filename would miss the first character.
So the outputs would be `est` and `est.cpp`. Now, they are correct.
=> selfhost: Fix basename without directory

src/main.rs
When getting started with this project, I tried to run `cargo run selfhost/main.jakt` and was presented with the following error:
```
Error: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```
It turns out, I did not have `clang` installed. This change makes the error a little more helpful.
```
$ ./target/debug/jakt -C foo selfhost/main.jakt
jakt: error: C++ compiler "foo" not found
```
=> main: print better error if c++ compiler not found

selfhost/lexer.jakt
Commit #138186a erroneously erased two error messages in the lexing of
numbers. Re-introduced with this fix. Test for this can be added later so as 
not to change the number of tests used to track the progress for the
selfhosted compiler.
=> selfhost/lexer: Re-add error messages in number lexing lost in rebase

selfhost/typechecker.jakt
Allow assignment of a value to a `Optional` of the same type
=> selfhost/typechecker: Allow `T` assignment to `T?`

selfhost/codegen.jakt, selfhost/typechecker.jakt
Add enum methods and make `samples/enum/methods.jakt` pass
=> selfhost/typechecker+codegen: Add enum methods

selfhost/typechecker.jakt
This fix some bugs on function return type typeckecking and adds a PASS for the following tests:
**tests/typechecker/return_value_type_mismatch.jakt
tests/typechecker/function_return_type_with_fat_arrow.jakt**
Previously, when going through the typechecking namespaces declaration, the current_function_id was not being updated so the typechecker didn't got the return type hint correctly.
Also, in order for this to work correctly I created the function unify_with_type based on the same function on the Rust compiler. This function properly check for type compatibility.
There is a unify function that just compares type_id's and is being used on several places as a placeholder. We should probably start replacing it for the new one.
Before:
273 passed
60 failed
7 skipped
After
275 passed
58 …
=> selfhost/typechecker: Fix function return typecheck

selfhost/typechecker.jakt
This adds a PASS on the test: /tests/typechecker/enum_is_variant_nonexistent.jakt by just changing the error text to match that of the test.
=> selfhost/typecheker: Change error text to match test

selfhost/typechecker.jakt
This adds a pass for the test tests/typechecker/field_access_on_enum.jakt
It adjust the error emited from a panic to a .error with a matching message to the test
=> selfhost/typecheker: Adjust error to match test

runtime/Builtins/Dictionary.h
Array<K> has no default constructor, instead you have to use
Array<K>::create_empty which returns an error.
=> builtins/Dictionary: Use `Array<K>::create_empty()` in `Dictionary::keys()` method

selfhost/typechecker.jakt, src/typechecker.rs, tests/typechecker/block_yield_unobservable_if.jakt
This adds a pass for the test /tests/typechecker/block_yield_unobservable_if.jakt
I also changed the test and the rust typechecker to add error capitalization
=> selfhost/typechecker: Adjust error to match test

selfhost/codegen.jakt, selfhost/typechecker.jakt
before:
```
286 passed
48 failed
7 skipped
```
after:
```
292 passed
42 failed
7 skipped
```
We now pass the following additional tests:
* `samples/generics/generic_fun2.jakt`
* `samples/generics/generic_fun3.jakt`
* `samples/generics/generic_fun4.jakt`
* `samples/generics/generic_struct.jakt`
* `samples/generics/generic_struct_mismatch.jakt`
* `samples/generics/generic_types.jakt`
The following two generic tests still fail and will need work on type unification to function properly.
* `tests/typechecker/generic_late_type_check_bad.jakt`
* `tests/typechecker/generic_late_type_check.jakt`
=> selhost: Some more generics

selfhost/typechecker.jakt, src/typechecker.rs, tests/typechecker/bad_simple_enum_constructor.jakt
This adds a PASS for the test/typechecker/bad_simple_enum_constructor.jakt
I also changed the error message and the rust compiler to add error capitalization
=> selhost/typechecker: Fix error message to match test

selfhost/typechecker.jakt
before:
```
283 passed
50 failed
7 skipped
```
after:
```
286 passed
47 failed
7 skipped
```
this fixes the following samples:
* samples/dictionaries/count_words.jakt
* samples/sets/shorthand.jakt
* samples/sets/unique_numbers.jakt
=> selfhost/typechecker: Handle constant values in Ranges

selfhost/parser.jakt
`not x is EnumVariant` becomes `x is not EnumVariant`
=> selfhost/parser.jakt: Add support for `is not` expression

selfhost/parser.jakt
Reverts SerenityOS/jakt#622
Oops, I misremembered that this was supported in the Rust compiler. Landing it would break the feature freeze.
=> Revert "selfhost/parser.jakt: Add support for `is not` expression"

selfhost/typechecker.jakt
before:
```
297 passed
36 failed
7 skipped
```
after:
```
299 passed
34 failed
7 skipped
```
this fixes these samples:
* samples/dictionaries/empty_literal.jakt
* samples/dictionaries/empty_literal_without_hint.jakt
=> selfhost/typechecker: Handle empty Dictionary literals

selfhost/typechecker.jakt
Previously, these cases would not log any errors that occurred prior to
the panic, which is useful information when debugging.
=> selfhost/typechecker: Use Compiler::panic() where possible

jakttest/jakttest.jakt, jakttest/parser.jakt, tests/typechecker/enum_is_variant_generic_unimplemented.jakt
There were errors that had to do with Jakt's lexer like
overflowing integers that should not stop Jakttest from
running. I've written a new parser that acts on raw input
and that expects the same format.
Before:
```
297 passed
36 failed
7 skipped
```
After:
```
301 passed
36 failed
3 skipped
```
=> jakttest: Change parser to act on raw input

jakttest/build.ninja, jakttest/jakttest.jakt, jakttest/patch-includes.py, jakttest/process.cpp, jakttest/process.h, jakttest/run-all.sh, jakttest/run-one.sh
Rewrote Jakttest so it accepts all the test files and runs them through a process scheduler to be able to run the tests in parallel. The binary gets a clean temporary directory where it places one temporary directory per job. It uses that to store both C++ temporaries from Jakt compiler's output and stderr/stdout results, which it will read once it knows the job has finished with the directory. Doesn't use any locks since it makes sure to only run one job per directory.
Most of the "changes" here are just removing unneeded files (mainly the 900loc from lexer/parser) since I wrote a custom `Expect` section parser that runs through each file to know what to expect from its output. This new parser does not care about the Jakt language; instead it only looks for the expect section, reducing …
=> jakttest: Parallelize Jakttest

editors/vscode/package.json
Change the script used in npm install for the vscode extension so as to
use && instead of ; as separators for the commands. Perhaps ; works on linux
(it doesn't on windows) but apparently semicolons as separators means
the commands that come after will be executed regardless of whether the
previous one failed or not, which doesn't seem correct either.
=> editors/vscode: Fix npm install

selfhost/codegen.jakt
passes two more tests.
[ PASS ] tests/codegen/control_flow_inside_match.jakt
[ PASS ] tests/codegen/control_flow_inside_nested_match_block.jakt
=> selhost/codegen: Generate correct control-flow within match statements

selfhost/typechecker.jakt
another one
`[ PASS ] samples/control_flow/try_catch.jakt`
=> selfhost/typechecker: Use correct type id for error in catch

samples/pointers/bad_pointer_deref.jakt, samples/pointers/bad_raw_ptr.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, src/typechecker.rs
This change marks the last of the unary operations left to check.
passes all the pointers tests
```
[ PASS ] samples/pointers/raw_ptr.jakt
[ PASS ] samples/pointers/bad_raw_ptr.jakt
[ PASS ] samples/pointers/bad_pointer_deref.jakt
```
=> selfhost/parser+typechecker: Pointers

selfhost/codegen.jakt, selfhost/typechecker.jakt
Adds support for `eprint` to codegen+typecheck.
We'll need this for selfhost compiling selfhost.
=> selfhost/codegen+typecheck: Add support for eprint

selfhost/typechecker.jakt
Align with what the Rust compiler does but not adding a variable when we see a struct-like enum variant's fields.
=> selfhost/typecheck: Don't add variable in enum variant

jakttest/run-one.sh
Looks like tests/main.rs runs tests binaries this way. Makes
samples/apps/read_all.jakt pass.
Before:
```
321 passed
16 failed
3 skipped
```
After:
```
322 passed
15 failed
3 skipped
```
Diff:
```
samples/apps/read_all.jakt PASS (previously FAIL)
```
=> jakttest: Run test binaries with their CWD set to their parent directory

jakttest/process.cpp
waitpid() doesn't return the exit code on *wstatus*.
Exit code is returned by the macro WEXITSTATUS.
=> jakttest: Fix bad use of waitpid()

jakttest/jakttest.jakt, jakttest/run-one.sh
This options shows the reasons why a test or multiple tests failed. To
do this it makes run-one.sh return different codes depending on the
stage that failed, and direct stderr of each stage to different
files. This needs #863 merged to run correctly, since it uses the
exit code that was badly returned.
=> jakttest: Add --show-reasons option

selfhost/codegen.jakt, selfhost/typechecker.jakt
Currently both `unknown` and `void` types have the same id. This causes ambiguity because one can't know what was the intended meaning of the value.
This PR does following:
* Introduce new `Type` variant `Unknown`
* Fix the tests broken by this change.
* Fix checking for `unknown` in enum declaration
* Fix not generating code for enum match when enum has type `void`
=> selfhost: Separate unknown from void

runtime/Jakt/MemMem.h
Port of https://github.com/SerenityOS/serenity/pull/14580.
Fixes String::contains().
cc @jntrnr - your boog report :P
=> runtime: Use the correct data types in Jakt::bitap_bitwise()

selfhost/codegen.jakt
Adds support for generic enum instances to codegen. Fixes two tests.
Before:
```
322 passed
15 failed
3 skipped
```
Now:
```
324 passed
13 failed
3 skipped
```
=> selfhost/codegen: Add support for generic enums

selfhost/typechecker.jakt
We can't just go accessing [0] of an array without checking that it
has elements.
=> selfhost/typechecker: Fix Array OOB access in match typecheck

selfhost/typechecker.jakt
This was originally using `.find_type_in_scope` which would check the full scope (including parents). This prevented generics from shadowing where they should.
This checks only the scope you're adding the type to for the duplicate.
No new tests pass, yet, but samples/math/integer_casts.jakt no longer exits with error code 2.
=> selfhost/typechecker: Dupe prevention only in scope being added to

jakttest/jakttest.jakt
Since tests that compare their output use the test result kind to know
the output file to check, why not do that as well when reporting the
reason why a test based on comparing outputs failed?
Test run output hasn't got modified, it remains:
```
326 passed
11 failed
3 skipped
```
=> jakttest: Use enum for failed reason on compared outputs

jakttest/build.ninja, jakttest/fs.cpp, jakttest/fs.h, jakttest/jakttest.jakt, jakttest/patch-includes.py
For one test Jakttest might expect its output to be somewhere that the
shell script hasn't yet gotten to. This seems to avoid Jakttest erroring
out but it's only a temporary fix, since seems that it's not the *real*
reason why Jakttest fails to find an output file.
=> jakttest: Pre-touch output files

selfhost/typechecker.jakt
This fixes some errors when trying to compile selfhost with itself also fix some errors in the test:
samples/enum/simple_match.jakt
The test doesn't passes yet due to other errors but I will work each fix in a separate commit.
All tests that were previously passing still passes
326 passed
11 failed
3 skipped
=> selfhost/typechecker: Typecheck generic enum instances

selfhost/codegen.jakt
Now:
```
327 passed
10 failed
3 skipped
```
=> selfhost/codegen: Don't output generic externs

selfhost/typechecker.jakt
Now:
```
328 passed
9 failed
3 skipped
```
Note: this assumes the generic return type is the first generic parameter. We'll probably want this to be more flexible in the future.
=> selfhost/typechecker: Infer generic return type

jakttest/run-all.sh
This PR aims to add macOS support to jakttest as `nproc` isnt a command on macOS. 
Details: 
- The `jakttest/run-all.sh` script checks if the operating system is macOS
- On that case, it replaces `nproc` with `sysctl -n hw.ncpu`
This successfully works on my mac. 
Details : macOS Monterey 12.4. Shell : zsh
=> jakttest: Add macOS support.

src/typechecker.rs
Prefilling an array is wrapped inside a TRY() in generated cpp code so its scope should throw
This also should fix issue #137
=> typechecker: Error when prefilling array in functions that don't throw

jakttest/jakttest.jakt
Now Jakttest only outputs the tests that were skipped/failed, and
doesn't output anything for passed tests, similar to how Ninja only
outputs one line if everything goes fine without output.
=> jakttest: Remove clutter from Jakttest's output

selfhost/typechecker.jakt, src/typechecker.rs
Throwing also transfers control the same way as returning does, this
makes the compiler no longer get mad about missing returns in throwing
branches:
function foo() throws -> i32 {
throw Error::from_errno(10)
}
=> typechecker: Teach 'statement_definitely_returns' about Throw as well

selfhost/typechecker.jakt
This was a recurring issue with selfhost compiling selfhost. Align the Typed enum case typecheck to be closer to what the Rust-based one does, which gets rid of the error.
=> selfhost/typechecker: Align Typed enum typecheck with Rust-based

jakttest/fs.cpp, jakttest/fs.h, jakttest/jakttest.jakt
There might be cases where the test that we launched fails at a different
stage than what we are told to check; in that case we get the error output
of the stage that failed and store that if --show-reasons is set.
Reverts the changes from #900, since it fixes the actual bug instead of being a
mere workaround.
EDIT(2): test summary when rebasing with `main`:
```
330 passed
7 failed
3 skipped
```
=>  jakttest: Catch test failures that happen in an earlier stage

samples/math/too_small_literal.jakt, selfhost/lexer.jakt, selfhost/typechecker.jakt, src/codegen.rs, src/typechecker.rs
It turns out that fallible integer casts never worked at all. This made them hard to use in selfhost, so this patch starts by fixing them in the rust-based compiler.
We then move on to fixing the `samples/math/too_small_literal.jakt` test in the selfhost compiler
=> Make `samples/math/too_small_literal.jakt` pass with selfhost

selfhost/typechecker.jakt
Aligns one of our error message to be more closely match what the rust-based compiler does.
Now:
```
334 passed
3 failed
3 skipped
```
=> selfhost/typechecker: Align error message with RBC

runtime/lib.h, runtime/prelude.jakt, samples/math/too_large_literal.jakt, selfhost/lexer.jakt, selfhost/prelude.jakt, src/lexer.rs
This patch adds two runtime helpers for unchecked integer arithmetic
so we can use them to see if a numeric literal is too large for our
normal u64 storage.
Fixes samples/math/too_large_literal.jakt
=> selfhost+runtime: Don't panic on too-large numeric literals

selfhost/codegen.jakt, selfhost/typechecker.jakt
This isn't a full fix, but gets us a step closer to getting samples/match/match_generic_codegen.jakt working
=> selfhost/typechecker: Match RBC for unknown vars

.github/workflows/ci.yml, jakttest/build.ninja, jakttest/fs.cpp, jakttest/fs.h, jakttest/jakttest.jakt, jakttest/os.cpp, jakttest/os.h, jakttest/patch-includes.py, jakttest/process.cpp, jakttest/process.h, jakttest/run-all.sh
This PR implements a series of steps to remove the `jakttest/run-all.sh` script
and make `jakttest` the entrypoint. These are the things that `jakttest` should
do by itself:
[^1]: These are achieved through `sysconf`, which is specified by POSIX.1-2008.
=> jakttest: Remove run-all.sh from Jakttest

editors/emacs/jakt_mode.el, editors/nano/jakt.nanorc, editors/sublime/sublime-for-yakt.sublime-syntax, editors/vim/syntax/jakt.vim, editors/vscode/syntaxes/jakt.tmLanguage.json, samples/guard/basic.jakt, samples/guard/no_else.jakt, samples/guard/no_scope_exit.jakt, selfhost/lexer.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
This patch adds support for the `guard` keyword from swift. Fixes #452.
```
[ PASS ] samples/guard/basic.jakt
[ PASS ] samples/guard/no_else.jakt
[ PASS ] samples/guard/no_scope_exit.jakt
```
I understand this probably won't get merged until the selfhost gets to 100% but that can't be too far away, right?
=> Guard keyword

jakttest/fs.cpp
Although it is supposed to follow POSIX.1-2008, struct stat in MacOS
headers doesn't have conforming names for struct stat timing members
(st_atime, st_mtime, st_ctime); leaving with us with no choice but to
patch our own headers to implement a fix that should've happened 16
years ago.
=> jakttest: Fix struct stat member naming on MacOS

selfhost/codegen.jakt
There were collisions in type ids due to seen_types not also storing the
ModuleId, resulting in no codegen for some enums/structs
=> selfhost/codegen: Update seen_types to store TypeId to_string

jakttest/parser.jakt, tests/main.rs
While selfhost is near to compile itself, some features are leaking into
the new selfhost, but their tests are (obviously) not passing in the
Rust based compiler. I figured out we can slap "selfhost-only" after
"Expect:" and have the Rust test driver skip over that one, but have
Jakttest run it.
=> jakttest+tests: Add ability to mark tests as selfhost only

selfhost/codegen.jakt
This fixes a handful of different codegen bugs that are preventing jakt-in-jakt:
* Fallible casts now use the proper inner type for the cast
* Struct-like enums that have field renames are now respected
* Proper arrows in invocations when a boxed enum
=> codegen: Improve selfhost codegen towards jakt-in-jakt

selfhost/codegen.jakt
While building selfhost with selfhost some namespace names were doubled
and therefore causing errors.
544 errors -> 456 errors
=> codegen: Fix doubled namespace prefix

jakttest/jakttest.jakt, jakttest/patch-includes.py, jakttest/process.cpp, jakttest/process.h
Instead of polling for every running test and spinning, we call
sigwait() when we don't have anything to run, so that Jakttest's process
is suspended until any child exits (SIGCHLD). When it wakes up it does
generic polls with waitpid(-1, ...) to process all the tests that
finished executing and mark their directories as freed, launch more test
processes and go back to sleep.
This way we avoid spinning which gets in the way of the N jobs running
clang++ that are compiling the generated C++ from running the tests.
On my system (i7-8550U, 4 physical cores, 8 processing units) this shaved around
10 seconds, which means Jakttest was previously getting in the way a LOT.
cc @alimpfard @ADKaster
=> jakttest: Make Jakttest not poll for processes

selfhost/codegen.jakt
These fixes now allow it to run with no errors.
The Dependency resolution case for Optional could probably be better, not sure if it should be a more general case or only for optional, or if it is needed at all.
=> Codegen fixes for Jakt in Jakt

tests/codegen/out_of_order_optional_type.jakt
Previously when a type was Optional it wasn't added as a dependency for
the parent type. selfhost-only as this ordering fails on the rust
version.
=> tests: Add selfhost-only test for out of order Optional type

samples/imports/assign_across_import/helper.jakt, samples/imports/assign_across_import/main.jakt, selfhost/typechecker.jakt
This prevents situations in which a generic type is instantiated across
two different modules and the typechecker will reject any assignments
between those two "different" types.
=> typechecker: Search for a type in all modules

selfhost/codegen.jakt, src/codegen.rs
@RealBlueta came across this bug. Both `codegen_enum_match()` and
`codegen_type_possibly_as_namespace()` which it calls, add `typename `
before the type name itself, if the type was defined inside a
namespace, and it followed the `CheckedEnumVariant::StructLike` branch.
The other branches that output `typename ` are not affected, and
removing `typename ` from them causes tests to fail.
A proper solution would be to have one place for responsible for
outputting `typename ` but this works and doesn't break anything. :^)
=> codegen: Prevent `typename typename Foo` from appearing in generated C++

jakttest/fs.cpp
This typo resulted in Jakttest not properly detecting that selfhost
files had been updated.
=> jakttest: Use mtime and not atime when checking modified time

selfhost/codegen.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
This was made possible by an earlier change, but not yet refactored in
the selfhost code.
There are some places that have not been updated as the compiler
doesn't handle inferring optional tuples yet.
=> everywhere: Use Compiler to infer type of `None`

samples/imports/same_imports.jakt, samples/namespaces/extend_namespace.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/utility.jakt
If a namespace or import is added, it is checked against the pre-existing
namespaces/imports in the same (parsed) scope, and if there is one that matches
the same characteristics, it is merged with it. This way we avoid creating two
different scopes for the same namespace, which results in false negatives, and
we avoid creating redundant import lists.
=> jakttest: Merge imports & namespaces when equivalent

README.md, samples/references/basic.jakt, samples/references/basic2.jakt, samples/references/no_mutable_reference_to_immutable_binding.jakt, samples/references/no_reference_locals.jakt, samples/references/no_reference_return_type.jakt, samples/references/no_reference_struct_fields.jakt, selfhost/codegen.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
This PR adds the following features:
- Reference types: `&T` and `&mut T` for immutable and mutable references to T.
- Reference expressions: `&foo` and `&mut foo` to create references to the variable `foo`.
- The dereference operator (`*`) now works on references as well.
Limitations:
- No reference locals
- No reference return values
- No reference struct fields
Basically, functions can now take parameters by reference, but we don't allow you to keep references around for long enough that they may become invalid.
This is meant to be a first, small set of reference features that we can make solid and safe before moving on to adding more complex features.
=> Basic support for reference types

README.md, samples/references/implied_argument_label.jakt, selfhost/typechecker.jakt
Just how we allow you to omit the argument label when passing a variable
with the same name as the parameter, we now also allow it when passing
a reference to such a variable.
=> selfhost: Don't require argument label for same-name references

selfhost/compiler.jakt, selfhost/error.jakt, selfhost/ide.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/utility.jakt
A port of the IDE support from the Rust-based compiler to the selfhost compiler.
Functionality is ported and connected to the commandline params. You can use it on simple tests, but more complex applications (namely selfhost itself) do not currently seem to yield info for hovers in all places it should.
Probably worth landing even though we're not at feature parity because it's big enough it'll bitrot quickly. We can continue to evolve it. With luck, we're only a few logic fixes away from being back to parity with the Rust-based compiler.
co-authored with: @cybergsus
=> IDE: Porting the Rust-based IDE support to selfhost

editors/vscode/server/src/server.ts, selfhost/compiler.jakt, selfhost/main.jakt, selfhost/typechecker.jakt, src/main.rs, src/typechecker.rs
The compiler now emits information about implicit `try` in the code
which then become inlay hints in the IDE.
This is default-on for now, so we can figure out what we think about it.
=> selfhost+rbc+editors: Add LSP inlay hints for implicit `try`

selfhost/codegen.jakt
`else => ""` already covers everything.
There is no need to have another arm returning `""`
=> selfhost/codegen: Remove unnecessary MatchArm

selfhost/main.jakt
gcc appears to use `-fdiagnostics-color=always` instead of
`-fcolor-diagnostics`
gcc requires `-Wno-literal-suffix` because of StringView `operator"" sv`
combined with https://github.com/SerenityOS/jakt/pull/969 allows stage 3 with gcc
=> main: Check for gcc compiler and adjust args

runtime/lib.h, runtime/prelude.jakt, selfhost/prelude.jakt, selfhost/utility.jakt
Because i was a usize (through String::length()) the condition i >= 0
would always be true and we'd hit an out-of-bounds error.
=> selfhost: Avoid underflowing when filename doesn't contain extension

selfhost/compiler.jakt, selfhost/error.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
With these fixes, we can now show diagnostics, type hints, and try hints when using selfhost as the backend for the IDE extension.
There are still some little issues to figure out, but this is a huge step towards usability.
=> selfhost: Bunch of fixes to the IDE integration

meta/jakt_gdb.py, selfhost/codegen.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
Before in gdb:
<details>
<summary>Open for horror story</summary>
```
(gdb) p/r *(Jakt::parser::ParsedType*)parsed_type.m_ptr
$3 = {
<Jakt::Variant<Jakt::parser::ParsedType_Details::Name, Jakt::parser::ParsedType_Details::NamespacedName, Jakt::parser::ParsedType_Details::GenericType, Jakt::parser::ParsedType_Details::JaktArray, Jakt::parser::ParsedType_Details::Dictionary, Jakt::parser::ParsedType_Details::JaktTuple, Jakt::parser::ParsedType_Details::Set, Jakt::parser::ParsedType_Details::Optional, Jakt::parser::ParsedType_Details::Reference, Jakt::parser::ParsedType_Details::MutableReference, Jakt::parser::ParsedType_Details::RawPtr, Jakt::parser::ParsedType_Details::WeakPtr, Jakt::parser::ParsedType_Details::Empty>> = {
<Jakt::Detail::VariantConstructors<Jakt::parser::ParsedType_Details: …
```
=> random fixes / GDB pretty printer

samples/control_flow/never_return.jakt, samples/control_flow/no_never_return.jakt, samples/control_flow/statements_after_never_return.jakt, selfhost/ide.jakt, selfhost/prelude.jakt, selfhost/typechecker.jakt
Functions that don't return can be marked as returning `never` so the
typechecker won't complain about not returning a value after calling
a never-returning function.
=> prelude+typechecker: Add never type

selfhost/typechecker.jakt, tests/typechecker/auto_deref.jakt
This applies where not doing so makes no sense, i.e. the following ops:
- used as subject of control flow (if/while/throw/etc)
- used as a match subject
- operated on by a unary operator (except deref itself)
- operated on by a binary operator
- indexed in various ways
- having a method called on it (including forced-unwrap)
- used as the 'fill size' value of an array literal
=> typechecker: Automatically dereference references

build.ninja
This renames the bootstrap's output to `build/stage0` and then uses stage0 to build `build/jakt` which is the bootstrapped build of the real jakt compiler.
From here, we can test using `build/jakt` and we should be running the tests against the latest compiler.
=> build: Be sure to build stage1 compiler with bootstrap

editors/vscode/syntaxes/jakt.tmLanguage.json
“Without highlighted modulo, life would be a mistake.”
― Friedrich Nietzsche
=> editors/vscode: Highlight modulo operator

editors/clion-or-jetbrains-ides/README.md
This plugin is not contained in the Jakt repo, so let's make it easier
to find.
=> editors: Add README for CLion plugin so it's easier to find

selfhost/parser.jakt
Make something like:
```
class Test
{
}
--
enum Test
{
}
--
struct Test
{
}
```
as well as:
```
if something == something_else
{
}
else
{
}
```
valid. Not sure if it is a design decision to not allow that 🤔
=> parser: Allow newlines in certain situations

bootstrap/stage0/jakt.cpp, selfhost/parser.jakt
Let's allow ourselves to split long function declarations across multiple lines.
=> parser: Allow newlines in function parameter lists

samples/enums/is_variant_binding.jakt, samples/enums/is_variant_binding_compound.jakt, samples/enums/is_variant_binding_compound_middle.jakt, samples/enums/is_variant_binding_compound_multiple.jakt, selfhost/codegen.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
In codegen, it will de-sugar this:
```
let foo = Foo::Bar(5)
let baz = Foo::Baz(m: "Hello")
if foo is Bar(n) {
if baz is Baz(m: different) {
println("{} {}", n, different)
}
}
}
```
Into this:
```
ErrorOr<int> main(Array<String>)
{
{
const Foo foo = typename Foo::Bar(static_cast<i64>(5LL));
const Foo baz = typename Foo::Baz(String("Hello"));
if ((foo).has<Foo::Bar>()) {
const i64 n = (foo.get<Foo::Bar>()).value;
if ((baz).has<Foo::Baz>()) {
const String different = (baz.get<Foo::Baz>()).m;
outln(String("{} {}"), n, different);
}
}
}
return 0;
}
```
=> selfhost: Add bindings on is op for enum variants

selfhost/typechecker.jakt
This corrects the span for bindings after the first binding in an `is` condition.
=> typechecker: Set 'is' binding to correct span

selfhost/codegen.jakt, selfhost/typechecker.jakt, tests/typechecker/is_binding_on_boxed_enum.jakt
We have to generate `->` to dereference boxed enums in C++.
=> typechecker+codegen: Support `is` bindings on boxed enums

samples/enums/is_variant_binding_else.jakt, samples/enums/is_variant_binding_else_complex.jakt, selfhost/typechecker.jakt
This fix an issue where the else condition were not being evaluated on the following case:
```
enum E {
A(i64)
}
let e = E::A(1)
if e is A(x) and x == 2 {
println("FAIL")
} else {
println("PASS")
}
}
```
=> selfhost: Eval else condition on is with bindings

samples/enums/is_variant_binding_compound_unmatched.jakt, samples/guard/is_guard.jakt, samples/guard/is_guard_compound_matched.jakt, samples/guard/is_guard_compound_unmatched.jakt, samples/guard/is_guard_no_exit.jakt, samples/guard/is_guard_no_leaks.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
This adds support for using the `is` clause in `guard` statements. The result is a way to match and bind without rightward drift:
```
> cat ./samples/guard/is_guard_compound_matched.jakt 
/// Expect: selfhost-only
/// - output: "PASS\n"
enum Foo {
Bar(i64)
}
let foo = Foo::Bar(5)
let bar = Foo::Bar(7)
guard foo is Bar(x) and x < 10 else {
println("not matched")
return -1
}
println("hello there: {}", x)
}
> ./build/is_guard_compound_matched 
hello there: 5
```
=> parser+typechecker+tests: Add support for 'is' in 'guard'

samples/enums/is_variant_binding_untyped_variant.jakt, selfhost/typechecker.jakt
This fixes a bug uncovered by AK on the following case:
```
enum E {
A(x: i64)
B
}
let e = E::B
if e is A(x) and x == 5 {
println("FAIL")
} else {
println("PASS")
}
}
```
After the fix, the else statement gets evaluated when the
first condition is not true.
This works perfectly but it should be noted that it can
generate some redundant code during the code gen phase.
The redundant code probable gets optimized by llvm but
I will work on a more efficient solution in a later commit
=> selfhost/typechecker: Eval else condition on is op

bootstrap/stage0/jakt.cpp, selfhost/codegen.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, tests/parser/multi_line_conditions.jakt, tests/typechecker/simple_enum_constructor_in_unknown_namespace.jakt
Take advantage of the new `is` bindings to reduce rightward drift in a whole bunch of places.
=> Use `is` and `guard` in more places :^)

selfhost/main.jakt
Hello friends! I built and ran `jakt` from a different directory and got an error.
```bash
→ cat noop.jakt
return 0;
}
```
**Before**:
```bash
→ cmake -B build
→ cd build && make
→ ./jakt -r ../noop.jakt
Runtime error: Error(code=2)
```
**After:**
```bash
→ cmake -B build
→ cd build && make
→ ./jakt -r ../noop.jakt
Could not write file: build/noop.cpp (Error(code=2))
```
I might try to figure out why it's trying to write to the `build` directory when I'm already in the `build` directory, but now I know I should probably just run it from the source dir. 😄
=> selfhost: Show an error if unable to write C++ file

README.md
Cloning the repository to a Windows machine with `core.autocrlf` enabled in your Git client results in compilation errors when attempting to build the stage1 compiler. I updated the README to explicitly mention the requirement to preserve `\n` line endings.
=> documentation: Add note about line endings on Windows

runtime/Builtins/Array.h, samples/arrays/slice.jakt, selfhost/codegen.jakt
`operator[]` and `at` were both applying the offset for a slice so the
values returned from the slice were incorrect for offsets other than 0
ArrayIterator `next` wasn't accounting for the offset when determining
if the end of the slice had been reached.
Added `slice_range` in `Array` to avoid subtraction underflow.
=> codegen+runtime: Fix array slice offsets

CMakeLists.txt, build.ninja, jakttest/build.ninja, selfhost/main.jakt
This cuts down build time spent in Clang by 2.7s, or 23%.
The open question is if jakt will ever support C++ exceptions (generated, for example, int the inline c++ code blocks, or third party c++ libraries called from jakt code)
```
hyperfine -r 5 "cd jakt/build/ && clang++ -std=c++20 -I ../runtime/ -Wno-parentheses-equality -Wno-trigraphs -Wno-user-defined-literalsi jakt.cpp" "cd jakt/build/ && clang++ -std=c++20 -I ../runtime/ -Wno-parentheses-equality -Wno-trigraphs -Wno-user-defined-literals -fno-exceptions jakt.cpp"
Benchmark 1: cd jakt/build/ && clang++ -std=c++20 -I ../runtime/ -Wno-parentheses-equality -Wno-trigraphs -Wno-user-defined-literalsi jakt.cpp
Time (mean ± σ):     14.772 s ±  0.092 s    [User: 14.208 s, System: 0.552 s]
Range (min … max):   14.666 s … 14.881 s    5 runs …
```
=> build: Use -fno-exceptions when compiling jakt-generated cpp code

selfhost/ide.jakt, selfhost/typechecker.jakt
Previously many spans would appear as part of an enum, when they were, in fact, not a part of it.
For example:
Another fix refers to Typed enum variant span, which I think was wrong (please, check if I am correct here). Due to this, signatures for Typed enum variants were not present. After the change I made, they work:
=> ide+typechecker: Miscellaneous span fixes

bootstrap/stage0/jakt.cpp, bootstrap/stage0/runtime/Builtins/Array.h, bootstrap/stage0/runtime/Jakt/Error.h, bootstrap/stage0/runtime/Jakt/Optional.h, bootstrap/stage0/runtime/Jakt/StringBuilder.h, bootstrap/stage0/runtime/Jakt/Variant.h, bootstrap/stage0/runtime/lib.h, bootstrap/stage0/runtime/prelude.jakt, runtime/Jakt/Variant.h, selfhost/codegen.jakt
This is the last occurrence of Variant::visit, which may be putting some
strain on compilers template engines
This is as of the last commit unused and we have a better way of
implementing this through our compiler without relying on the
c++-compiler's template engine.
----
I did not update the stage0 README. because the commit hashes may change during merging
=> codegen+bootstrap+runtime: Use switch-statements in enum's debug_description + Remove Variant::visit

samples/arrays/throws.jakt, selfhost/typechecker.jakt
Previously, this would error in c++ compilation.
=> typechecker: Report error for arrays in non-throwing scope

selfhost/codegen.jakt
We always know the internal typeid, so we can do this lookup our selves
and put less strain on the c++-compiler
=> codegen: Remove last use-cases of Variant::has

samples/functions/default_arguments.jakt, samples/functions/default_arguments_bad_type.jakt, samples/functions/default_arguments_complex.jakt, samples/functions/default_arguments_constructor.jakt, samples/functions/default_arguments_default_before_required.jakt, samples/functions/default_arguments_method.jakt, samples/functions/default_arguments_mixed.jakt, samples/functions/default_arguments_some_defaults.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, tests/parser/non_parameter_3.jakt
This PR adds the possibility to use default arguments for functions and method calls.
```
function say(text: String = "WHF", number: i64 = 5, boolean: bool = false, optional: String? = None) {
println("{} {} {} {}", text, number, boolean, optional)
}
say()
}
// output: "WHF 5 false None\n"
```
=> parser+typechecker: Implement default args for functions/methods

samples/enums/enum_recursive_method.jakt, selfhost/typechecker.jakt, tests/typechecker/struct_constructor_in_enum_function.jakt
Fixes #527 #677
This also allows a number of refactors such as moving `expression_type` to a method `type` in the `CheckedExpression` enum.
I will submit the refactoring as a separate PR.
=> typechecker: typechecking ordering fixes

selfhost/main.jakt
This updates the interpreter to allow main to have a void return as well, just as we do for compilation. If void, just return 0.
=> interpreter: Allow void main return

CMakeLists.txt, bootstrap/stage0/runtime/Builtins/Array.h, bootstrap/stage0/runtime/Jakt/Assertions.h, bootstrap/stage0/runtime/Jakt/Error.h, runtime/Builtins/Array.h, runtime/Jakt/Assertions.h, runtime/Jakt/Error.h
CI was getting quite unreadable, so let's fix some warnings and suppress others.
=> meta+runtime: Reduce number of warnings produced by Windows CI

samples/basics/reserved_variable.jakt, selfhost/lexer.jakt
This commit adds a small restriction on identifier names. They are no longer allowed to start with `__jakt` as names like these are used in codegen for fresh variables and etc.
This is to protect against like this that looks legal but fails in the C++ compile step:
```
let __jakt_var_1 = "hello"
try foo() catch {
print(__jakt_var_1)
}
}
function foo() throws -> void {
throw Error::from_errno(9000)
}
```
```
build/foo.cpp:15:6: error: redefinition of '__jakt_var_1'
auto __jakt_var_1 = [&]() -> ErrorOr<void> { return TRY((foo())), ErrorOr<void>{}; }();
^
build/foo.cpp:14:14: note: previous definition is here
const String __jakt_var_1 = String("hello");
^
build/foo.cpp:16:18: error: no member named 'is_error' in 'Jakt::String'
if (__jakt_var_1.is_error()) {{
~~~~~~~~~~~~ ^ …
```
=> selfhost: Reserve identifiers starting with __jakt

samples/enums/methods_access_violation.jakt, selfhost/typechecker.jakt, tests/typechecker/class_private_default.jakt, tests/typechecker/class_private_field_ctr.jakt, tests/typechecker/class_private_static.jakt, tests/typechecker/struct_private.jakt, tests/typechecker/struct_private_field.jakt
This cleans up some error messages for private visibility.
* Removes `from scope None` since it doesn't make sense
* Adds hint for private constructors
* Renames `variable` to `field` and `function` to `method`, to be closer to terms people may expect
Before:
```
Error: Can't access function ‘JsonParser’ from scope None, because it is marked private
----- samples/apps/json.jakt:346:18
345 | function parse_json(input: String) throws -> JsonValue {
346 |     mut parser = JsonParser(input, index: 0)
^- Can't access function ‘JsonParser’ from scope None, because it is marked private
347 |     return parser.parse()
-----
```
Now:
```
Error: Can't access constructor ‘JsonParser’, because it is marked private
----- samples/apps/json.jakt:346:18
345 | function parse_json(input: String) throws -> …
```
=> typechecker+tests: Clean up error messages for private visibility

selfhost/codegen.jakt, selfhost/types.jakt
`module.is_prelude()` is a lot clearer than `module.id.id == 0`. :^)
=> types+codegen: Make checks for prelude module more explicit

jakttest/jakttest.jakt
Instead of hiding the reasons why tests fail by default, flip the default so that we show the tests that failed and why during a normal run of `jakttest`.
You can turn this off with `--hide-reasons`
=> jakttest: Show reasons tests fail by default

selfhost/lexer.jakt
This improves the error messages generated from #1076 when using a reserved identifier from 
```
----- foo.jakt:2:9
1 | function main() {
2 |     let __jakt_var_1 = "hello"
^- reserved identifier name
3 |     try foo() catch {
-----
Error: reserved identifier name
----- foo.jakt:4:15
3 |     try foo() catch {
4 |         print(__jakt_var_1)
^- reserved identifier name
5 |     }
-----
Error: Expected initializer
----- foo.jakt:2:9
1 | function main() {
2 |     let __jakt_var_1 = "hello"
^- Expected initializer
3 |     try foo() catch {
1 selfhost: Improve error messages when using a reserved identifier
-----
Error: Unsupported expression
----- foo.jakt:2:9
1 | function main() {
2 |     let __jakt_var_1 = "hello"
^- Unsupported expression
3 |     try foo() catch {
-----
Error: Unsupported …
```
=> selfhost: Improve error messages when using a reserved identifier

selfhost/typechecker.jakt, tests/typechecker/generic_type_check_method_call.jakt, tests/typechecker/generic_type_check_method_call_invalid_argument.jakt
For codegen the arguments should be included in a method call before it
has been resolved. Later in the typechecking process the specialized
version of the function is typechecked.
=> typechecker: Add generic method call args if function can't be resolved

selfhost/main.jakt
With this PR, if clang exits with a non-zero exit code, we'll exit jakt with a non-zero exit code. This will allow shell scripts, CI, etc to pick up on compiler errors that are coming from clang and not just directly from jakt.
=> main: Exit with non-zero exit if clang fails

selfhost/ide.jakt
Adds range support to the IDE support so you can hover over the `from` and `to` elements of a range and get IDE feedback
=> ide: Add range support to IDE

editors/vscode/syntaxes/jakt.tmLanguage.json
This PR fixes "mut" highlighting in function argument lists (before only the "mut this" argument was highlighted) and adds highlighting for the "is" keyword.
Before:
After:
=> editors/vscode: Small highlighting improvements

samples/match/match_optional_inference.jakt, samples/match/match_type_hint.jakt, selfhost/codegen.jakt, selfhost/interpreter.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/match_exhaustive_catchall.jakt, tests/typechecker/match_non_exhaustive.jakt, tests/typechecker/numeric_inference_optional.jakt
Previously for an Optional match you would need
```
let b = match a {
Bar => Some(2)
Baz => {
let ret: i64? = None
yield ret
}
}
```
With a type hint it can now be written as
```
let b: i64? = match a {
Bar => 2
Baz => None
}
```
Also adds numeric inference on optional types.
=> typechecker: Add type hint for match statement return type

.github/workflows/ci.yml, CMakeLists.txt, bootstrap/stage0/runtime/io.h, cmake/install-rules.cmake, jakttest/jakttest.jakt, jakttest/os.cpp, jakttest/os.h, jakttest/process.cpp, jakttest/run-one.ps1, runtime/io.h, samples/imports/import_extern_c.jakt
This feels even more hacky than run-one.sh, but does appear to work.
Also fix a few bugs in process.cpp along the way that were never
tested with the initial implementation.
Add CI as well.
=> jakttest: Enable Windows execution by using a PowerShell script

samples/match/match_yield_after_guard.jakt, selfhost/codegen.jakt, selfhost/typechecker.jakt
In cases where there is a yield statement guard is rewritten as a
yielded match with 2 cases rather than an if statement.
=> typechecker: Allow yield after guard statement in block

selfhost/typechecker.jakt, tests/typechecker/binary_op_right_to_left.jakt
This adds the ability for binary operations to have their arguments inferred right-to-left in the cases where the lhs is an unknown int. This allows expressions like this to now typecheck:
```
100 + 16u8
```
The resulting code will be the same, we just will infer the type of `100` correctly now.
=> typechecker+tests: Infer unknown ints in binary ops in both directions

selfhost/typechecker.jakt, tests/typechecker/enum_unknown_variant_is.jakt
Previously, code like this that included an unknown variant with `is` in an `if` could crash.
```
enum Foo {
Bar(i64)
}
let x = Foo::Bar(100)
if x is Baz(y) {
}
}
```
I've added this as a test, including it with a binding so we can ensure this continues to work.
=> typechecker: Fix crash of unknown variant with `is` 

samples/match/match_ranges.jakt, selfhost/codegen.jakt, selfhost/typechecker.jakt
```
let x = 42
let y = match x {
0..30 => "foo"
30..100 => "bar"
else => "baz"
}
println("{}", y)
}
```
=> typecheker+codegen: Add basic support for ranges in match cases

samples/functions/implicit_argument_label_on_dereference.jakt, selfhost/typechecker.jakt
We already allowed you to omit the argument label when passing a
reference (immutable or mutable) to a variable with the same name as the
parameter. This patch extends that feature to also support dereferences.
=> typechecker: Allow omitting label on dereference of same-name variable

samples/classes/inheritance.jakt, selfhost/codegen.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt
co-authored with @awesomekling
This adds simple form of class-based inheritance to get us started. For this first PR, the focus is on adding an inheritance hierarchy and calling methods in your parent class.
eg)
```
class Parent {
public function greet(this) {
println("I am the parent")
}
}
class Child: Parent {
}
let child = Child()
child.greet()
}
```
=> all: Add support for basic class inheritance

editors/vscode/package.json, editors/vscode/snippets/jakt.json
This is a handy feature that can paste in a bunch of stuff for only a
few keypresses. This way you don't have to remember the correct
incantation to get a test to parse, just type `jt` (or `jte`).
=> editors/vscode: Add snippets

editors/vscode/syntaxes/jakt.tmLanguage.json
This also fixes the corruption of syntax highlighting in the rest of the file, when something like
`function_call(&mut argument)` occurred.
Before:
After:
=> editors/vscode: Add syntax highlighting for references in arguments

samples/generics/generic_class.jakt, selfhost/codegen.jakt
Fixes the updated test case of #428 and adds a test for it (similar to generic_struct test).
=> codegen+tests: Use proper dereference operator for generic classes

samples/pointers/bad_pointer_deref.jakt, selfhost/typechecker.jakt, tests/typechecker/function_pass_by_reference.jakt, tests/typechecker/generic_function_pass_by_reference.jakt
Previously when resolving a call we didn't check to see if we needed to
dereference a variable in scope before checking if it is a function.
This also adds checking for references in `check_types_for_compat`
=> typechecker: Allow calling a function passed by reference

CMakeLists.txt, bootstrap/stage0/runtime/Jakt/Assertions.h, cmake/install-config.cmake, cmake/install-rules.cmake, cmake/jakt-executable.cmake, runtime/Jakt/Assertions.h
This re-organization of the CMake files enables a simple project to
have a CMakeLists.txt as simple as:
cmake_minimum_required(VERSION 3.20)
project(MyJaktProgram LANGUAGES CXX)
find_package(Jakt REQUIRED)
add_jakt_executable(MyJaktProgram
MAIN_SOURCE src/main.jakt
MODULE_SOURCES
src/foo.jakt
src/bar.jakt
)
.. as long as the jakt install directory is in the CMAKE_PREFIX_PATH
=> meta: Install helper cmake file for add_jakt_executable()

CODE_OF_CONDUCT.md
An adaptation of the Serenity CoC/rules from discord for the repo. These are already enforced, but we don't specify them on GitHub only discord, so this helps to make them more visible.
=> rules: Adapt rules from official discord for repo

selfhost/codegen.jakt, selfhost/lexer.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/polymorphism.jakt, tests/typechecker/polymorphism_override_needs_virtual.jakt
This adds two related features to our class support: class-based polymorphism and method overrides.
Method overrides require there to be a method in the parent class hierarchy that has a corresponding virtual method.
Example:
```
class Parent {
public virtual function greet(this) {
println("greeting from the parent")
}
}
class Child: Parent {
public override function greet(this) {
println("greeting from the child")
}
}
function use_parent(anon parent: Parent) {
parent.greet()
}
let child = Child()
use_parent(child)
}
```
=> all: Add class-based polymorphism and method overrides

selfhost/interpreter.jakt, selfhost/repl.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/generic_across_scopes.jakt
Previously we were using an empty or incorrect inference set in many
places, and using TypeId::equals() to check for type compatibility,
which lead to a slew of issues in generic functions and their
instantiations.
This commit should fix most of those, and also allow function
expressions with generic types to actually work.
~~TODO: add a test (and fix whatever breaks)~~
=> typechecker: Properly keep track of generic inferences across scopes

samples/apps/json.jakt, samples/control_flow/for_throw.jakt, samples/control_flow/return_nothing.jakt, samples/enums/methods.jakt, samples/enums/recursive_enums.jakt, selfhost/codegen.jakt, selfhost/ide.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/codegen/control_flow_inside_match.jakt, tests/codegen/control_flow_inside_nested_match_block.jakt, tests/typechecker/function_for_return.jakt, tests/typechecker/unreachable_code_after_return.jakt
We used to only check for reachability after "never return" statements.
Now, we check after every statement that can divert control flow.
fixes #151
=> typechecker: Report errors in more unreachable cases

jakttest/jakttest.jakt
This also adds an error when a specified file/ directory isn't readable.
=> jakttest: Allow specifying a directory as a path argument

samples/generics/generic_class_method.jakt, samples/generics/generic_struct_method.jakt, selfhost/codegen.jakt
1) I've realized that the fix that I introduced in https://github.com/SerenityOS/jakt/commit/6d369fad0241b5bb284e0ae475bb3706196f3b4c can be simplified
2) Fix dereference operator for methods in generic classes (similar to the fix in https://github.com/SerenityOS/jakt/commit/6d369fad0241b5bb284e0ae475bb3706196f3b4c but already simplified like above)
3) Previously, if the generic struct had no data members, ex. like this one:
```cpp
struct A<T> {
public function test(this, anon x: T) => x
}
```
And we wanted to create an instance of it, ex. like so:
```cpp
let name: A<String> = A()
```
In CPP it would look like this:
```cpp
const A<String> name = A();
```
And unfortunately CPP would complain.
This PR changes the CPP codegen to:
```cpp
const A<String> name = A<String>();
```
=> codegen: Generic classes/structs fixes

selfhost/codegen.jakt, selfhost/typechecker.jakt, tests/typechecker/polymorphism_missing_override.jakt
C++ allows to omit the override keyword, however in Jakt we can do better
and actually enforce it :^)
Previously this would just compile, but resulted in unexpected behaviour where it was still calling the method on the child.
Also adds a commit that makes sure that the parent class is added to the codegen dependency graph, because C++ requires that.
=> typechecker+tests: Enforce override keyword on function that is virtual

samples/functions/fat_arrow.jakt, samples/generics/passing_arrays.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, tests/typechecker/generic_late_type_check.jakt
Not specifying a return type for a function block results in that block
returning void. We will still infer the return type for fat arrow
functions.
=> typechecker: Don't infer return type for function blocks

editors/vscode/syntaxes/jakt.tmLanguage.json
Before:
After:
Before:
After:
Technical details:
One "constant.numeric.float.jakt" is for numbers that do not have a `.` inside them, but have explicitly specified the type to be `f32` or `f64`. The other "constant.numeric.float.jakt" is for numbers that have a `.` inside them (and may or may not specified the type).
=> editors/vscode: Add syntax highlighting for "virtual", "override" and floating point numbers

selfhost/parser.jakt, selfhost/typechecker.jakt, tests/typechecker/block_yield_function.jakt
This follows the behavior of yielding out of defers, if blocks, statement blocks, etc. Resolves #461.
=> typechecker: Emit Jakt error instead of C++ one, when trying to yield out of functions

jakttest/jakttest.jakt, jakttest/parser.jakt
When creating a test to expect "error:" and no error occurs the test
result stage will be later than the expected stage.
=> jakttest: Better output for test failure cases

runtime/Builtins/Array.h, tests/codegen/array_slice_extra_array_value.jakt, tests/codegen/array_slice_range_end_omited.jakt
Previously when using a range with no size specified the iterator
wouldn't be correctly limited to the size of the slice.
Fixes #1089
=> runtime: Use correct size bound for array slice iterator

selfhost/parser.jakt, tests/parser/invalid_cast_syntax.jakt
Previously, we would assume an empty type after `as`, which led to us
rejecting everything after the as. Now, we error with a hint about the
incorrect syntax, and continue parsing a typename.
fixes #385
=> parser: Continue parsing typename after invalid cast syntax

editors/vscode/README.md
Previously the documentation would have cmake write build files into the project root.
=> editors/vscode: Document the correct build directory path for cmake

editors/vscode/server/src/server.ts
This ensures that include paths are properly resolved on all platforms. The previous technique did not work on Windows.
=> editors/vscode: Convert file URLs to paths with "fileURLToPath()"

jakttest/jakttest.jakt, jakttest/parser.jakt, samples/guard/is_guard_no_exit.jakt, samples/imports/assign_across_import/helper.jakt, tests/typechecker/enum_with_type_from_prelude.jakt
Now tests that have no skip tag and that have an incorrect
format (i.e Jakttest can't figure out what the test is expecting) are
not skipped but reported as failures.
=> jakttest: Fail if no explicit skip tag is set

selfhost/codegen.jakt, selfhost/parser.jakt, tests/parser/invalid_function_decl.jakt
Or if Comptime is not followed by Identifier. This fixes invalid code
like ``comptime function foo() {}``or``function function foo() {}``
from creating a nameless function.
Also, stop generating function declarations for comptime functions. We don't need em.
=> selfhost/parser: Report error if Function is not followed by Identifier

editors/vscode/README.md, editors/vscode/package.json, selfhost/main.jakt
Make the go-to-definition actions work by escaping file paths before inserting them into JSON documents, as they contain backslashes on Windows. This also technically fixes paths on Linux, as they can contain pretty much any character expect for slashes and null.
There are other strings that are inserted into JSON documents, but they should not contain slashes or double-quotes, as they are type names and function prototypes.
Not really related, but this PR also updates the VS Code extension build instructions in order to avoid installing the vsce package globally.
=> main+editors/vscode: Make go-to-definition actions work on Windows

CMakeLists.txt, bootstrap/stage0/jakt.cpp, editors/vscode/server/src/server.ts, selfhost/codegen.jakt, selfhost/formatter.jakt, selfhost/lexer.jakt, selfhost/main.jakt, selfhost/parser.jakt
Reasonably stable and okay now :^)
Issues to fix:
Specific issues noted by https://github.com/SerenityOS/jakt/pull/1140#issuecomment-1235334949:
Would be nice to have:
=> formatter: MVP code formatter

selfhost/formatter.jakt
This fixes the issue where `1-3+2` was formatted to `1-3 + 2` instead of `1 - 3 + 2`
=> formatter: Fix space around minus

selfhost/formatter.jakt
This fixes the formatter, which previously would output:
`Bar(x: i64,y: i64)`
Now outputs:
`Bar(x: i64, y: i64)`
=> formatter: Fix space after comma in enum

selfhost/codegen.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/generic_recursive_function.jakt, tests/typechecker/generic_recursive_function_with_respecialization.jakt
This avoids the issue where currently infinite recursion will occur in
typechecking as typecheck_and_specialize_generic_function will be
recursively called.
=> typechecker: Add FunctionGenerics class to store specializations

editors/vscode/server/src/server.ts, samples/modules/callback_modules.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/utility.jakt
This allows us to 'format modified lines' instead of formatting the entire document.
Also contains a `match` error nicety, I got tired of having the screen light up
=> main+editors/vscode: Implement a range formatter

selfhost/codegen.jakt, selfhost/interpreter.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/match_in_lambda.jakt
Match codegen requires the current function to get the return type for the control flow part of `ExplicitValueOrControlFlow`. For a lambda we weren't updating the current function so would get the wrong return type.
=> codegen: Add FunctionId for lambdas for correct match codegen

selfhost/formatter.jakt
This updates the formatter so that imports become a comma-delimited list that breaks at 120 columns.
eg)
```
import parser {
BinaryOperator, DefinitionLinkage, DefinitionType, EnumVariantPatternArgument, FunctionLinkage, FunctionType
ParsedBlock, ParsedCall, ParsedCapture, ParsedExpression, ParsedExternImport, ParsedField, ParsedFunction
ParsedMatchBody, ParsedMatchCase, ParsedMethod, ParsedModuleImport, ParsedNamespace, ParsedParameter
ParsedRecord, ParsedStatement, ParsedType, ParsedVarDecl, Parser, RecordType, TypeCast, UnaryOperator
Visibility
}
```
=> formatter: Add support for compact imports

samples/pointers/bad_pointer_deref.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt
Ran the (vim) command:
```
:s/`{}`/‘{}’/gc
```
on all selfhost files, now every quote should be back to its original style.
=> all: Revert quote style in more places

editors/vscode/server/src/server.ts
This adds a URI decode which is required on my Windows machine for the IDE support to work. Otherwise, we'd try to convert an encoded URI and fail to find any imported files from the file you're editing.
=> vscode: Fix Windows IDE paths for includes

selfhost/codegen.jakt, tests/codegen/tuple_enum_variant.jakt
Previously instantiating a Tuple with an enum variant as a variant would give a c++ error for no viable constructor.
This is because for example:
`let tuple = (Foo::A, 1)`
would codegen to
`Tuple{ typename Foo::A(), static_cast<i64>(1LL)}`
Which would be a constructor of Tuple(Foo, long) with an argument of a Tuple<Foo::A, long>
With the compiler not knowing how to convert a Tuple(A, long) into a Tuple(Variant<A, B>, long)
It now will codegen to:
`Tuple{ Foo { typename Foo::A() } , static_cast<i64>(1LL)}`
Thanks to Andrew Kaster for explaining the c++ issue and working out the fix.
=> codegen: Wrap enum variant call in enum type

editors/vscode/README.md
The cmake configuration should use -S and -B for source and build directories instead of --Build. Further add the language type to bash in the code snippets
=> documentation: Fix commands in editors/vscode/README.md

selfhost/codegen.jakt, selfhost/compiler.jakt, selfhost/main.jakt, selfhost/repl.jakt
Because the cost of checked math is so high, let's use unchecked math specifically during optimized release builds. This matches languages like Rust, but just in general is probably what many devs might expect as the cost of doing checked math is quite high (in my tests it's something like 3x slower.
=> all: Make optimized builds use unchecked math

selfhost/typechecker.jakt, tests/typechecker/call_instance_method_statically.jakt
Previously this would just get the "Wrong number of arguments" error because an instance method has the `this` argument.
=> typechecker: Add better error for calling an instance method statically

selfhost/formatter.jakt
If we are in array initialization, semicolon is a valid syntax to specify the size of the array. Otherwise, it is superfluous and should be replaced with newline.
before:
```
println("hello friends;"); println("goodbye friends"); // what about comments
let arr = [0;69]
unsafe {
cpp {
"int wat;"
}
}
}
```
after:
```
println("hello friends;")
println("goodbye friends") // what about comments
let arr = [0; 69]
unsafe {
cpp {
"int wat;"
}
}
}
```
=> formatter: Replace semicolons with newlines when appropriate

runtime/IO/File.cpp
This removes using `readlink` on macOS and instead using the results from `_NSGetExecutablePath` directly. This fixes an issue where macOS was not able to build the proper path to discover the runtime lib.
=> runtime: Simplify exe path on macOS

selfhost/formatter.jakt, selfhost/lexer.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/utility.jakt, tests/parser/invalid_digits_in_binary_number.jakt, tests/parser/invalid_digits_in_octal_number.jakt
This changes the lexer to output a `Number` token with: `prefix: LiteralPrefix, number: String, suffix: LiteralSuffix` instead of
`number: NumericConstant`
The parser then parses this token into a `NumericConstant`
The primary motivation for this is so that the Number token carries the information required to reconstruct the source for formatting. It also makes for a better separation of concerns though as this was parsing that the lexer was doing.
This also changes the lexing slightly in that for example for an octal: `0o78` would end up as `Garbage` due to the 8 being an invalid digit. It would now lex as `0o7` and then a number `8`
`0o8` would lex as `0o` and `8`, with `0o` giving an error in the parser as having no digits.
=> all: Move `NumericConstant` parsing to the parser

selfhost/typechecker.jakt, tests/typechecker/is_variant_binding_match_case.jakt, tests/typechecker/is_variant_binding_return_statement.jakt
Currently `expand_context_for_bindings` is only used with if/ guard conditions.
It is also useful to have though in expressions where there is no block but the binding can be used as part of the expression.
There are probably other places where it would make sense in future.
=> typechecker: Add is variant bindings to return/match pattern expressions

samples/structs/field_default_values.jakt, selfhost/codegen.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/class_private_field_ctr.jakt
Fields with default values can be ommitted from the implicit constructor call and are treated as default arguments. Additionally the constructor is no longer automatically marked private in the presence of private fields, instead each constructor call is checked and rejected only if it actually sets any private fields.
=> parser+typechecker: Add support for struct field default values

samples/closures/lambdas_can_throw.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, tests/typechecker/lambda_no_return_type.jakt
This updates lambdas to match the rules now for other types of functions
- Only infer type if it is an arrow function.
- For non arrow functions without a return type specified the return type becomes void instead of unknown.
=> parser+typechecker: Update lambda return type inference

selfhost/error.jakt
This fixes where the arrow points in when an error occurs earlier in a larger file. Before, we were miscalculating the largest line number, which caused us to miscount how many spaces over to put the arrow and label.
Before:
```
Error: Type mismatch: expected ‘i64’, but got ‘String’
----- testme.jakt:3:15
2 |   let x = "bob"
3 |   let y = x / 3
^- Type mismatch: expected ‘i64’, but got ‘String’
4 |
-----
Error: Binary arithmetic operation between incompatible types (‘String’ and ‘i64’)
----- testme.jakt:3:11
2 |   let x = "bob"
3 |   let y = x / 3
^- Binary arithmetic operation between incompatible types (‘String’ and ‘i64’)
4 |
-----
```
Now:
```
Error: Type mismatch: expected ‘i64’, but got ‘String’
----- testme.jakt:3:15
2 |   let x = "bob"
3 |   let y = x / 3
^- Type mismatch: …
```
=> errors: Fix where error arrow points as number of lines grows

runtime/IO/File.cpp
File::write might get an empty array, so fwrite() returning zero does not
always mean that an error occurred. Better check that an error actually
occurred before returning an Error(errno=0).
=> runtime:  Do not error when writing zero bytes to a File

samples/modules/a.jakt, samples/modules/basic_modules.jakt, samples/modules/generic_module_scope.jakt, selfhost/typechecker.jakt, selfhost/types.jakt
As specializing a generic function creates a new scope in the current module, a function from another module is no longer able to make local calls within that module.
This change instead uses the original function scope as the parent when creating a new scope for specialization, allowing it to make calls local to the module it is in.
=> typechecker: Use function scope as parent for generic specialization

selfhost/typechecker.jakt, tests/typechecker/return_array_literal_in_function_returning_tuple.jakt, tests/typechecker/return_tuple_literal_in_function_returning_array.jakt
We should catch attempts to return an array or tuple literal when it's incompatible with the context return type.
=> typechecker: Error on array/tuple literals when another type is expected

CMakeLists.txt
Now that we can build individual modules separately, `ccache` can help speed things up substantially when making smaller edits.
=> build: Use ccache if available

samples/enums/common_members.jakt, selfhost/codegen.jakt, selfhost/interpreter.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/parser/unclosed_brace_in_enum.jakt, tests/parser/unclosed_brace_in_ref_enum.jakt, tests/typechecker/field_access_on_enum.jakt
In cases where all enum variants share a member, the member can now be
hoisted into the enum body, and can be directly accessed via the normal
dot notation.
=> everywhere: Add support for common enum fields 

selfhost/typechecker.jakt
This pull request disables dumping of type hints for enum fields that have an explicit type, removing hints that duplicate type information.
Before
After
Note that this depends on #1234
=> typechecker: Hide type hints for explicitly typed enum fields

samples/functions/return_no_value_in_function_returning_value.jakt, selfhost/typechecker.jakt
Previously this was reported by the c++ compiler.
I was wondering if the hint necessary because it feels a bit repetitive to me because it uses the same span as the error.
=> Typechecker: Error on return with no value in function returning a value

jakttest/README.md
Just a small typo I found while reading the docs.
Cheers :)
=> Fix typo `stdandard` ->  `standard` in jakttest/README.md

selfhost/error.jakt, selfhost/typechecker.jakt
This does a few changes to the error reporting output to make it a little nicer. A little easier to see by example.
Before:
After:
Change list:
* Moved to using UTF-8 box drawing, which gives nicer lines
* Make vertical and horizontal lines connected for a bit of a nicer look
* Use the boxes to let your eyes group what is line numbers and what is source
* BONUS: fix the bad assignment span to actually point at the immutable variable
=> errors: Improve errors reporting output

selfhost/error.jakt
If we want it, here's a PR that will put the label at the end of the error span rather than the beginning.
Example:
=> error: Move error label to end of span

bootstrap/stage0/runtime/jaktlib/arguments.jakt, jakttest/jakttest.jakt, runtime/jaktlib/arguments.jakt, samples/apps/read_all.jakt, samples/arrays/array_iterator.jakt, samples/arrays/slice.jakt, samples/compiletime_execution/dict.jakt, samples/compiletime_execution/set.jakt, samples/dictionaries/iterator.jakt, samples/sets/iterator.jakt, samples/tuples/destructuring_assignment_for.jakt, selfhost/build.jakt, selfhost/codegen.jakt, selfhost/compiler.jakt, selfhost/formatter.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/lexer.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/path.jakt, selfhost/posix_compiler.jakt, selfhost/posix_process.jakt, selfhost/repl.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, selfhost/utility.jakt, selfhost/windows_compiler.jakt, selfhost/windows_process.jakt, tests/codegen/array_slice_range_end_omited.jakt
This removes most uses of `.iterator()`. There are still a couple places where we explicitly want an iterator and one case I wasn't quite sure how to implement IntoIterator for, but it's definitely noticeably cleaner now.
=> all: Remove most uses of .iterator()

README.md, samples/traits/default_implementation.jakt, selfhost/typechecker.jakt
This ensures that a default implementation is only used if the method doesn't exist on the struct.
Also added a default implementation sample based on the readme example.
=> typechecker: Move trait default implementations below struct methods

selfhost/typechecker.jakt, tests/typechecker/assign_bool_literal_to_string.jakt, tests/typechecker/return_bool_literal_in_function_returning_string.jakt, tests/typechecker/return_bool_literal_in_function_returning_void.jakt
Previously, boolean literals just ignored type hints. We also add some tests for this behavior.
Fixes #1254.
=> typechecker: Unify bool literal with type hint

samples/closures/capture_this.jakt, selfhost/parser.jakt
This patch allows us to capture the `this` raw reference in a closure, such as in:
```
struct Foo {
message: String
function bar(this) {
let baz = function[this]() => println(this.message)
baz()
}
}
let foo = Foo(message: "WHF")
foo.bar() // prints "WHF"
}
```
Previously we had pass in the enclosing type as a reference parameter to achieve this.
For now, we do a by-reference (in C++ terms) capture of the current object, but since we currently do not allow storing or returning closures, this should be safe.
=> parser: Initial support for capturing `this`

selfhost/codegen.jakt, selfhost/formatter.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, tests/parser/range_patterns.jakt
This changes the parsing rules for ranges, which lets them have a more correct precedence when used in more situations. The common one this will fix is when a range is used in a match separated by `|` to say "one of these ranges match".
Example:
```
match abc {
100..200 | 300..400 => println("success")
else => println("failure")
}
```
=> parser+test: Fix precedence of ranges

selfhost/build.jakt, selfhost/formatter.jakt
Makes this
```
import foo( bar, baz) { }
```
do this
```
import foo(bar, baz) { }
```
instead of this
```
import foo (bar, baz) { }
```
=> Formatter: Don't die on `import foo()`

selfhost/codegen.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt
It's now possible to mutate enum fields by matching them:
```jakt    
match my_enum {
MyVariant(&mut field) => {
field = new_value
}
}
```
=> Allow binding mutable reference to enum field in match case

CMakeLists.txt, cmake/jakt-executable.cmake, runtime/CMakeLists.txt
Ensure that the runtime path is properly passed to external jakt executables based on the RUNTIME_DIRECTORY propery rather than hardcoding to CMAKE_CURRENT_LIST_DIR/runtime, which is only correct when the add_jakt_executable is run from the top level directory in jakt/.
Clean up some other cmake variables to ensure that we are explicit about what include paths are required to build a jakt compiler, what paths are required by cpp files created by that jakt compiler, and which paths are passed in from the user.
=> cmake: Clean up include and runtime paths to un-break external projects

samples/modules/c.jakt, samples/modules/common_import.jakt, selfhost/typechecker.jakt
Previously `::` was converted to `__` when setting the imported name but not when checking if the import existed, so the module would be imported again each time that it was seen.
=> typechecker: Prevent imports with `::` being imported multiple times

selfhost/codegen.jakt, tests/codegen/optional_chaining_class.jakt
The operator for accessing members of classes is `->`, since they are of type NonnullRefPtr. But when mapping an optional for chaining, the operator generated was the default `.`.
My code seems a bit weird. Any pointers on how to make it look better are appreciated.
=> codegen: Fix codegen for optional chaining with classes

samples/tuples/optional.jakt, selfhost/typechecker.jakt
Previously there would be a cpp error for example with:
```
let foo: (bool?, bool?) = (false, false)
```
It required
```
let foo: (bool?, bool?) = (Some(false), Some(false))
```
This change automatically wraps the values when typechecking.
Fixes: #752
=> typechecker: Wrap values for optional inner tuple types in `Some`

jakt.nix
This brings jakt more inline with other Serenity projects by providing a nix-shell build-dependencies setup :^)
=> misc: Add jakt.nix

selfhost/typechecker.jakt, tests/typechecker/dont_crash_on_bogus_generic_call.jakt
...in the presence of previous type errors that made the call impossible to specialize.
When this happens, we will already have queued up errors about the type errors, so we just bail out of the generic typecheck and let said errors bubble to the user.
=> selfhost+tests: Fix a crash when trying to typecheck generic call

runtime/Builtins/Dictionary.h, runtime/Jakt/Forward.h, runtime/Jakt/HashMap.h, samples/arrays/push_values.jakt, samples/attributes/deprecated.jakt, samples/attributes/external_name.jakt, samples/dictionaries/with_class.jakt, selfhost/codegen.jakt, selfhost/formatter.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/parser.jakt, selfhost/posix_compiler.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, selfhost/windows_compiler.jakt
A friendly class type cannot be used in dictionaries otherwise.
This issue stems from the fact that HashMap<T, U> hands U out as `Traits<U>::PeekType` (and not U itself), so we can't go back to the original U object from that if they're not the same type.
=> runtime: Return the correct types from Dictionary::get() / random other fixes

editors/vscode/syntaxes/jakt.tmLanguage.json
Now correctly highlights `trait`, `implements` and `requires`.
=> editors/vscode: Add syntax highlighting for traits

samples/arrays/slice_of_slice.jakt, samples/enums/methods.jakt, samples/optional/mutable_unwrap.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, tests/typechecker/class_private_field_default.jakt, tests/typechecker/restrict_to_scopes_accepted.jakt, tests/typechecker/struct_private_field.jakt, tests/typechecker/yield_out_of_method_not_allowed.jakt
I've decided to clean up `typecheck_method` and `typecheck_function` a little bit. I've tried to keep commits as atomic as possible to help the reviewer/s while also trying not to spam with them too much...
This PR does several things:
- 64c4070c678f3cb1bdfe841610f5efd08c334c97 removing the second `function_return_type_id = .typecheck_typename()` in `typecheck_function`.
I think this does not achieve anything (at least the removal of this does not break any tests) other than overwriting the previous value of the return type, which for function blocks with no specified type, would default to void at this point in code (as was the intention in bea32fbf16dee90f4038a42fd2552e2da0630ff7). In other words, this overwrite prevents us from defaulting to void for function blocks with no specified …
=> Typecheck_function/method clean up and fixes to achieve parity

selfhost/codegen.jakt, tests/codegen/lambda_throw_and_return_void_implicit_return.jakt
Resolves https://github.com/SerenityOS/jakt/issues/1280.
Now we always add a `return {};` for all lambdas that can throw and return `void`, similarly to how we do it for regular functions.
=> Add implicit return for lambdas returning void, which can throw

selfhost/parser.jakt, tests/parser/namespace_allow_newline_after_keyword.jakt
This PR removes an amazing 1 FIXME
Allowing newlines after a `namespace foo`, but before a `{`, is the same behavior that we have for `if` and `match` statements, `function`s etc.
=> Allow newlines after "namespace" keyword + minor FIXME

CMakeLists.txt, cmake/install-config.cmake.in, cmake/jakt-executable.cmake, runtime/CMakeLists.txt
The Compiler Explorer misc-builder doesn't add -pthread automatically.
We might have to revisit this when adding actual threading support to
jakt.
=> CMake: Make sure that we link against -pthread when required

selfhost/error.jakt, selfhost/parser.jakt, tests/typechecker/dont_choke_on_multiline_error_spans.jakt
I've been hunting a weird panic that I've stumbled upon. Turned out it was a logic error in the display_message_with_span in error.jakt. While being there I've also fixed some other issues.
- 0081da911eec952ee0468c794d1ebaa9a3969294 we didn't properly print the span of the errors that occurred in first line of the source code
test.jakt:
```cpp
function main() { return y }
```
Previously:
```
greenclover@CloverLaptop:~/jakt$ ./build/bin/jakt ./own/test.jakt 
Error: Variable 'y' not found
───┴─
```
Now:
```
greenclover@CloverLaptop:~/jakt$ ./build/bin/jakt ./own/test.jakt 
Error: Variable 'y' not found
───┬─ ./own/test.jakt:1:26
1 │ function main() { return y } 
│                          ╰─ Variable 'y' not found
───┴─
```
- 865cb956ab2ad51bf2615d953eb0fb4e8f7bc16c we were not gathering a …
=> Simplify error display + some fixes (including a fixed panic)

selfhost/codegen.jakt, selfhost/typechecker.jakt, tests/typechecker/match_enum_else_binding_generic.jakt
Previously the responsibility for an error (or alternatively a panic) when a generic else in a match had bindings was on codegen. It wasn't done in typechecker because `ignore_errors` is set to `true` when typechecking such expression.
But we know that this situation is not allowed in any case, so we can set `ignore_errors` to `false` and emit an error.
Removes 1 FIXME :^) and gives a better span for such an error.
=> Error in typechecker when generic else in a match has bindings

.github/stale.yml
As there are some older PRs building up here I think it would be useful to have the same setup here as with serenity so that we get the list down to just PRs that authors are still actively wanting to be merged.
This is just the config that serenity is using copied over.
Someone with permissions will need to install the app: https://github.com/apps/stale
=> meta: Add github stale bot config

selfhost/parser.jakt, tests/parser/if_else_branches_different_array_expr.jakt, tests/parser/if_else_branches_different_dict_expr.jakt, tests/parser/if_else_branches_different_set_expr.jakt, tests/parser/if_else_branches_different_tuple_expr.jakt
A typo / missing parenthesis when comparing the size of both arrays caused an out-of-bounds array access during element-wise comparison.
=> parser: Fix possible out-of-bounds array access in ParsedExpr::equals() for ParsedExpr:: Array, Dictionary, Set and Tuple

selfhost/typechecker.jakt, tests/typechecker/control_flow_while_1.jakt, tests/typechecker/control_flow_while_2.jakt, tests/typechecker/control_flow_while_3.jakt, tests/typechecker/control_flow_while_4.jakt, tests/typechecker/control_flow_while_5.jakt
Previously, control flow of a `while` block was a little bit too definitive. Ex. in:
```cpp
while condition {
return
}
println("Hello, condition might not be true!")
```
it would be resolved to `AlwaysReturns` and the `println()` would be marked as an "Unreachable code".
But `while` blocks act somewhat similarly to the `if` blocks that have no `else` statement. The **condition** might not be `true` so the result cannot be definitive, only partial.
`While` blocks, however, also consume all the `break`s and `continue`s, and without them, partial results can be downgraded to `MayReturn`s (like we already did before this patch).
This means that if the condition is not known to be always true, no matter what the inner control flow of the `while` block is, we will resolve it to `MayReturn`. …
=> typechecker: Make `while` block control flow resolving less definitive + use more info

selfhost/typechecker.jakt, tests/typechecker/control_flow_19.jakt, tests/typechecker/control_flow_19_continue_case.jakt, tests/typechecker/control_flow_20.jakt, tests/typechecker/control_flow_20_continue_case.jakt, tests/typechecker/control_flow_21.jakt, tests/typechecker/control_flow_21_continue_case.jakt, tests/typechecker/control_flow_22.jakt, tests/typechecker/control_flow_22_continue_case.jakt
Very similar to #1306.
When resolving an `if... else` statement, whenever an `if` block was resolved to `MayReturn` we were losing information about the potential `break`s in the `else` block. And the other way around as well, whenever an `else` block was resolved to `MayReturn`, we were losing information about `break`s in the `if` block.
Tests not added for `PartialAlwaysReturns` and `PartialNeverReturns` because of the same reason as in the mentioned PR. I've still changed the behavior for these to the more correct one, in case `unify_with()` changes its behavior.
=> typechecker: Control flow, don't lose information about `break`s

selfhost/parser.jakt, tests/parser/match_duplicate_pattern_enum.jakt, tests/parser/match_duplicate_pattern_enum_with_namespaces.jakt, tests/parser/match_duplicate_pattern_enum_with_variables.jakt, tests/parser/match_duplicate_pattern_int.jakt, tests/parser/match_equals_different_case_body.jakt, tests/parser/match_equals_same_case_body.jakt, tests/parser/match_equals_same_compare_unordered.jakt
- patterns, that are enum variants now get treated as equal when one is a subset of the other
-> `Foo::A` is the same as `A`, but not the same as `Bar::A`
- match cases no longer get detected as equal, when they have different bodies
- match cases now get detected as equal, even when they are in different order
- duplicate patterns in a single match expression are now an error
=> parser: Fix comparison of match cases to be order independent & also compare case bodies

selfhost/typechecker.jakt, tests/typechecker/logical_not_cannot_use_on_non_boolean_type.jakt
=> typechecker: Don't allow using logical Not on non-boolean types

runtime/CMakeLists.txt
=> runtime: Update AK includes to match new DeprecatedFlyString name

selfhost/typechecker.jakt, tests/typechecker/optional_array_assign_empty.jakt, tests/typechecker/optional_dictionary_assign_empty.jakt, tests/typechecker/optional_set_assign_empty.jakt
We were not unwrapping type hints from an Optional which caused programs like these:
```cpp
mut arr: [i64]? = []
}
```
to fail (the array that we are assigning is empty and thus, there is nothing from which we can infer the type of the value other than a type hint).
When inferring a type of rhs from a type hint, we first check if struct ids of a type hint and rhs are the same (in this case we are checking if type hint and rhs are both arrays). This would previously fail because type hint is an array wrapped in an Optional, so we end up comparing Optional's struct id with an Array's struct id.
=> typechecker: Unwrap type_hints from an Optional in some places

samples/generics/iterator.jakt, selfhost/typechecker.jakt
Previously the return type would be Void which would cause a cpp error when for example trying to assign to a void type. With Unknown auto will be used in the generated code.
This fixes: #1063 and makes it possible to iterate on a generic type.
=> typechecker: Set call return type to Unknown when unresolved

.github/workflows/ci.yml, selfhost/main.jakt
Following the serenity CI update, switch to using clang-15.
=> ci: Use clang-15 to build on CI

README.md, samples/closures/trailing_closure_parameter.jakt, selfhost/codegen.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/parser/trailing_closure_not_allowed_in_for.jakt, tests/parser/trailing_closure_not_allowed_in_guard.jakt, tests/parser/trailing_closure_not_allowed_in_if.jakt, tests/parser/trailing_closure_not_allowed_in_match.jakt
See `samples/closures/trailing_closure_parameter.jakt` for an example.
As shown by the tests, these are not parsed in the expressions of if/for/guard/match, since that leads to ambiguous syntax and also just looks bad.
This is a very limited first pass. A single block is parsed, and treated as a closure. This means that closure parameters, captures, and the return type (including the throwingness) cannot be defined. Ideally the return type would be inferred based on the closure's contents and the called function's parameter type.
=> parser: Allow trailing closure arguments to occur after the call's ()

runtime/lib.h, selfhost/codegen.jakt, tests/codegen/class_casts.jakt
This patch implemens `as!` and `as?` for class pointer values, both upwards and downwards in the class hierarchy.
=> codegen+runtime: Support upcast and downcast with class pointers

selfhost/codegen.jakt, selfhost/formatter.jakt, selfhost/ide.jakt, selfhost/parser.jakt, selfhost/repl.jakt, selfhost/typechecker.jakt, tests/typechecker/wrong_parameter_name_in_anon_argument_label.jakt
We were using this behavior, consciously or not, in a couple of places.
=> typechecker: Disallow argument label overriding

selfhost/typechecker.jakt, tests/typechecker/assign_weak_to_weak.jakt
We were rejecting these by trying to unify `weak T?` and `T` even though both sides of the assignment are the same exact type.
=> typechecker: Allow assignment of `weak T?` to `weak T?`

selfhost/error.jakt
This adds an underline for a bit better readability of an error span.
Before:
```
Error: Call to unknown function: ‘fooo’
────┬─ andreas.jakt:9:5
8  │ fn main() {
9  │     fooo()
│        ╰─ Call to unknown function: ‘fooo’
10 │ }
────┴─
```
Now:
```
Error: Call to unknown function: ‘fooo’
────┬─ andreas.jakt:9:5
8  │ fn main() {
9  │     fooo()
│     ───┬
│        ╰─ Call to unknown function: ‘fooo’
10 │ }
────┴─
```
A few more examples:
```
Error: Binary arithmetic operation between incompatible types (‘String’ and ‘i64’)
────┬─ testme.jakt:9:11
8  │
9  │   let y = x / 3
│           ────┬
│               ╰─ Binary arithmetic operation between incompatible types (‘String’ and ‘i64’)
10 │
────┴─
Error: Type mismatch: expected ‘i64’, but got ‘String’
────┬─ testme.jakt:15:15
14 │
15 │ …
```
=> error: Underline error span for better readability

selfhost/codegen.jakt, tests/typechecker/is_operator_on_imported_class.jakt, tests/typechecker/simple_base_and_derived.jakt
This makes the `is` operator work on imported class names.
=> codegen: Qualify the typenames in `is` expressions

selfhost/codegen.jakt, selfhost/compiler.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, tests/typechecker/class_private_field_ctr_no_label.jakt, tests/typechecker/no_argument_label_when_required.jakt, tests/typechecker/wrong_parameter_name_in_arg_label.jakt, tests/typechecker/wrong_parameter_name_in_arg_label_with_matching_name.jakt
1. Don't allow overriding the argument label when the label is **required**, but argument name matches the parameter name (as opposed to the fix in 5c0b593 which only fixed situations where the label was explicitly **not required** (it somehow went under my radar)). This is done by using the `get_argument_name()` in `validate_argument_label()`, which returns the label first, if it exists, so if it exists, we later only compare the label with the parameter name during validation
2. When the argument label doesn't match the parameter name and argument name is retrievable, but it also doesn't match the parameter name - don't highlight the **argument name** when printing an error, highlight the **wrong label**. This is a side effect of using `get_argument_name()` in …
=> typechecker: Argument label validation fixes

editors/vim/syntax/jakt.vim
A simple change as I noticed function didn't work and it's fn now :^)
=> editors/vim: Switch 'function' to 'fn'

editors/emacs/jakt-mode.el, editors/nano/jakt.nanorc
I should have done this in 1 commit
=> editors: Switch 'function' to 'fn' in Emacs and Nano

selfhost/parser.jakt, selfhost/typechecker.jakt
* Place the type hint of the iteration variable right next to the variable declaration, instead of after `in`.
* Don't show type hints for tuples when destructuring, as each of the constituent already gets a type hint. (Like regular destructuring assignments.)
Before:
After:
=> parser+typechecker: Put type hints of for statements at the expected location

runtime/Builtins/DynamicArray.h, tests/runtime/array_slice_of_slice.jakt
We were incorrectly adding the slice offset to the size of the subslice, which made them too large if the offset was non-zero.
=> runtime: Make slicing an array slice with a non-zero offset work

runtime/Builtins/DynamicArray.h, tests/runtime/array_slice_equality.jakt
Code generation already assumed that slices have `operator==()`, which they didn't. :^)
=> runtime: Make it possible to compare two array slices

selfhost/types.jakt, tests/typechecker/control_flow_try_catch.jakt
In theory fixes #1365 (and probably many more situations), unfortunately we can't currently `return` from `try` blocks.
=> types: Make try-catch use the same control flow resolution as if-else

selfhost/parser.jakt, tests/parser/value_enum_eof_after_right_curly.jakt
By applying the same logic as in the normal enums.
Spotted in https://youtu.be/IRT5wGTH4iY?t=282
=> parser: Don't incorrectly error when value enum has eof after ending `}`

CMakeLists.txt
This doesn't work on Windows, so do the same hack we already did for Time.cpp for now.
=> build: Don't build AK/DOSPackedTime.cpp

samples/attributes/stores_arguments.jakt, selfhost/typechecker.jakt, tests/typechecker/field_pointer_lifetime.jakt
Allow creating local references to struct fields in methods.
It turned out the way we were checking scope lifetimes was a bit backwards. We use this method every to guard against the inverse (the child scope outliving the parent) but the method wasn't implemented that way. To be honest, I still don't understand a 100% why some tests were passing in the old implementation.
I also had to invert the exit condition to account for the fact that comptime scope parent chains are disjunct from runtime scope parent chains, but at least we now know that the json parser sample is testing for that case :wink:.
Fixing this also surfaced that the `stores_arguments` attribute test wasn't actually testing the feature but was passing due to the bug. I had to adjust it to actually test the failure case for …
=> typechecker: Allow field references in methods

selfhost/typechecker.jakt, tests/typechecker/polymorphism_override_arity_mismatch.jakt, tests/typechecker/polymorphism_override_param_mutability_mismatch.jakt, tests/typechecker/polymorphism_override_param_type_mismatch.jakt, tests/typechecker/polymorphism_override_return_type_mismatch.jakt, tests/typechecker/polymorphism_override_throw_mismatch.jakt
Actually typecheck that the relevant parts of an override function match the virtual they target.
Closes #1335
Closes #1336
=> typechecker: Typecheck function overrides

selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/unsafe_extern_function_call_bad.jakt, tests/typechecker/unsafe_extern_function_call_good.jakt, tests/typechecker/unsafe_function_call_bad.jakt, tests/typechecker/unsafe_function_call_good.jakt
This PR adds support for marking functions `unsafe`.
Unsafe functions cannot be called in a safe context, you must enter an `unsafe {}` block first.
This first cut supports free functions and extern functions. Methods, etc, are left for our future selves :^)
=> Unsafe functions

samples/basics/is_none.jakt, selfhost/codegen.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/enum_is_none.jakt, tests/typechecker/is_none_type_mismatch.jakt
First step towards being able to doing `is` checks on optionals as if they were enums.
=> selfhost: Add `is None` operator

bootstrap/stage0/typechecker.cpp, runtime/jaktlib/platform/windows_compiler.jakt, selfhost/codegen.jakt, selfhost/formatter.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/main.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/parser/match_bare_literals.jakt, tests/typechecker/match_non_exhaustive_value.jakt, tests/typechecker/match_true_false_else.jakt, tests/typechecker/match_true_false_exhaustive.jakt
Also:
- change, well, most but probably not all occurrences of the `true => else =>` pattern (or much less frequently -
`false => else =>`) to the `true => false =>` pattern,
- fix one test that was affected by this (which had a `true => false => else =>` pattern, `else` obviously not reachable),
- fix one error not starting with an uppercase.
Funny business like this is still possible though:
```rust
fn main() {
let x = false
let y = false
match x {
true => { }
false => { }
(y == y) => { }
}
}
```
=> typechecker: Teach match about true & false being exhaustive

selfhost/typechecker.jakt, tests/typechecker/for_loop_auto_dereference_range.jakt
=> typechecker: Auto-dereference range expression in the for-loop

samples/classes/assign_derived_to_base.jakt, selfhost/typechecker.jakt, tests/typechecker/assign_derived_to_base_on_declaration.jakt, tests/typechecker/assign_derived_to_optional_base_on_declaration.jakt, tests/typechecker/assign_derived_to_weak_base_ptr_on_declaration.jakt
Partially based on #1350. Resolves #1341 + assigning Derived to Optional\<Base\> and assigning Derived to Base weak ptr.
=> typechecker: Allow subclass to be assigned to type of it's base class (v2)

selfhost/typechecker.jakt, tests/typechecker/return_none_should_return_non_optional.jakt
Resolves #1390. This is looking kinda meh, but we do that in this way in a couple of places already
=> typechecker: Prohibit returning None if non-optional is expected

CMakeLists.txt, cmake/jakt-executable.cmake
link.exe defaults to 1MiB of stack size. When using clang-cl, which defaults to linking with link.exe, provide an explicit stack size of 8MiB to better match with Unix platforms.
Fixes #1328
=> CMake: Remove fdiagnostics-color with clang-cl, and give stack size

jakttest/jakttest.jakt, jakttest/process.cpp
Makes `sigwait` common to `poll_running_tests`, making the last waiting loop also suspend instead of polling its children.
Fixes #1228, since there's no more spinning and spamming `wait4`.
=> jakttest: Move blocking on any exiting child to `poll_process_exit`

selfhost/repl.jakt
Currently the repl shows a parser error "Unsupported expression" when the user enters an empty line. This commit adds a check for the empty line and skips the loop to avoid the error.
=> repl: Avoid showing an error when entering an empty line

runtime/prelude.jakt, samples/strings/contains.jakt
Pulled in the string.contains method from the C++ side. Added a few tests to ensure it was working.
=> prelude+tests: Add string.contains support

cmake/jakt-executable.cmake
When building Serenity with ENABLE_JAKT, it builds Jakt using this cmake file, BUT it already has the `-Wall -Wextra -Werror` options set. This was causing it to fail to compile Jakt: Some warnings were not enabled by default, so building Jakt directly would work, but they are enabled by these extra options, so would fail as part of building Serenity.
By defining the options here, we make sure that we can't accidentally break the Serenity build without also breaking the Jakt build itself.
Of course, ideally we would also generate code that doesn't set off warnings, but that's trickier.
=> CMake: Enable all warnings, then manually disable those we trigger

editors/vscode/server/src/server.ts
Using text.size will prematurely stop this calculation from working in files where the text.size is not the same as the buffer.size. Because we use the buffer and index into it, the buffer.size should be the guard.
=> VSCode: Use buffer.size not text.size as upper limit

runtime/Jakt/DeprecatedStringBuilder.h
Fixes the build.
Depends on AK change here: https://github.com/SerenityOS/serenity/pull/18551
=> runtime: Drop the Optional formatter in favour of the one in AK

selfhost/interpreter.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/call_function_in_struct_field_initializer.jakt
This overcomes #1429 by inserting temporary garbage expressions into the
default value of the parameters in the generated struct constructor. To
make this work, I had to add a type id to the `Garbage` checked
expression, so that constructor calls that are checked before the
default field being filled can be properly resolved.
Fixes #1429 .
=> typechecker: Defer struct default field typecheck

selfhost/parser.jakt, tests/parser/invalid_enum_variant_with_type.jakt
A bit of git stash cleaning 🚿
`parse_variable_declaration()` will not push the `.index` if `.current()` is not an `Identifier`
=> parser: Fix infinite loop on invalid enum variant with type

selfhost/lexer.jakt, tests/parser/cpp_keywords.jakt
=> lexer: Do not allow c++ keywords as identifiers

selfhost/typechecker.jakt, tests/typechecker/array_type_inference.jakt, tests/typechecker/match_trait_impl_with_substitutions.jakt
`When a generic typevar is resolved from LHS, a simple (and working!)
strategy is to just substitute LHS with the resolved type and
re-evaluate the checks, instead of trying to check anything in advance, which will have nuances that are handled in the rest of match cases.
Fixes #1246
Fixes #1436.
=> typechecker: LHS typevar should be replaced when resolved

selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/multiple_explicit_ctors.jakt
This broke since b37e3e3b7287f6cf9358a13ddf67bde24d84e02c as that commit made the default-argument checker require a single constructor (or ICE).
This commit fixes that, and makes the libline-backed repl build again.
=> typechecker: Only look for implicit default constructors for defaults

selfhost/lexer.jakt
On an optimised build:
Using match
```
rob@rob-linux:~/jakt$ time jakt -e 2000 selfhost/main.jakt
{"hover": "mut output: struct String"}
real	0m9.275s
user	0m9.182s
sys	0m0.080s
```
Using a set
```
rob@rob-linux:~/jakt$ time jakt -e 2000 selfhost/main.jakt
{"hover": "mut output: struct String"}
real	0m4.774s
user	0m4.681s
sys	0m0.093s
```
Stylistically the match is nicer, maybe it could be made just as fast. Match seems (at least to me, maybe someone else can confirm those numbers) to be costing a lot of performance on a hot code patch like this, for something similar like this that can map to an exists lookup.
=> lexer: use a set for cpp keyword check

selfhost/parser.jakt
Makes this work:
```
import extern "foo.h" {
extern enum Foo : i32 { _1, _2, _3 }
}
```
=> parser: Allow extern declaration of enums

selfhost/codegen.jakt, tests/codegen/explicit_void_in_nested_match.jakt
Since C++ can't implicitly construct `ExplicitValue<void>` from `void`,
Jakt outputs explicit constructors of `ExplicitValue<void>()`. Now it
also outputs them when calling `release_return` under nested matches.
=> codegen: Nested branch `release_return` handles `void` explicitly

jakt.nix
This PR fixes two issues:
- Jakttest won't run without python3, since it runs `run_one.py` as its helper script.
- Jakt won't build with `clang_14`, it has issues with `StringView` prefix:
```bash
set -xe
rm -rf build
cmake -B build -DCMAKE_CXX_COMPILER=clang++ -G Ninja
ninja -C build
```
<details><summary>Build log:</summary>
```
-- The CXX compiler identification is Clang 14.0.6
-- The C compiler i+ ninja -C build
GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/32nc0cdhkw8hygcxycychwcdf8r9ipfj-clang-wrapper-14.0.6/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working …
```
=> nix: Fix various issues with nix devshell

.github/workflows/win64_llvm_clang_build_and_cache.yml
This workflow will fetch, build, and cache LLVM Clang on an x64 action runner. The build needs to be done in release mode or the standard runners will not have enough space to complete the build.
This job will take approximately 3 hours and 45 minutes to complete.
=> CI: Workflow to build Clang on Windows

jakttest/jakttest.jakt, selfhost/typechecker.jakt, tests/typechecker/invalid_arbitrary_namespace_in_format.jakt
This removes the detection of `format` from arbitrary namespaces where
the function may not exist, or be an entirely different function.
Fixes #1461.
=> typechecker: Detect `*print*` and `format` calls exclusively on empty namespace

selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt
=> typechecker: Move error span to catch keyword

README.md, runtime/jaktlib/path.jakt, runtime/jaktlib/platform.jakt, runtime/lib.h, samples/generics/const_generics.jakt, selfhost/build.jakt, selfhost/codegen.jakt, selfhost/cpp_import/clang.jakt, selfhost/cpp_import/clang_c.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/lexer.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/platform.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/parser/bogus_generic_call.jakt
- Makes it possible to build jakt as part of serenity's toolchain (see https://github.com/alimpfard/serenity/commit/4e8f6b634c6a1267f4301e8deddf8edc57696bc3)
- Const generics (almost) + NTTP support in cpp_import/clang
- Dependent types (`foo<i32>::bar` etc)
- partial support for explicit type specialization (+ support in cpp_import)
- Some random feng shui
=> Take another step towards testing Jakt in serenity

selfhost/formatter.jakt
Previously the formatter would turn `fn foo<T requires(...)` into `fn foo<Trequires(...)` which is a compile error. This change adds a space as the preceding trivia to the `requires` token so that the formatter has one fewer reasons to be turned off.
=> formatter: Add a space before requires in function generics

samples/compiletime_execution/dict.jakt, selfhost/typechecker.jakt, tests/typechecker/fallible_operation_no_throws.jakt
This fixes a cryptic c++ error message when you forget to put `throws` on your function.
=> typechecker: Report error when creating a string in non-throwsy block

selfhost/codegen.jakt, tests/codegen/enum_common_bindings.jakt
When destructuring an enum field from an enum variant, codegen needs to
identify what is a common field and what is a variant field:
Given some enum like this:
```jakt
enum Foo {
value: i32
Bar(other: i32)
Baz
}
```
And a usage like this:
```jakt
if foo is Bar(value, other) {
return value + other
}
```
The generated C++ will use `foo.as.Bar.value` instead of `foo.common.init_common.value`,
which results in a C++ error. This PR fixes this mishap.
=> codegen: Make EnumVariantArg use common section for common enum fields

selfhost/formatter.jakt
This stops the formatter from breaking code that uses reflection
=> formatter: Add space after reflect keyword

selfhost/typechecker.jakt, selfhost/utility.jakt, tests/typechecker/class_same_name_function_and_member.jakt, tests/typechecker/class_same_name_member_and_function.jakt
=> typechecker: Ensure that no name is redefined as a different symbol

selfhost/codegen.jakt, tests/codegen/inheriting_struct_constructors.jakt
Previously struct constructors weren't checked for deriving, just class
constructors.
Fixes #1486.
=> codegen: Make derived struct constructors call their base's constructors

runtime/jaktlib/platform/darwin_errno.jakt, runtime/jaktlib/platform/posix_errno.jakt, runtime/jaktlib/platform/posix_fs.jakt, runtime/jaktlib/platform/windows_fs.jakt
Windows' _fullpath and _getcwd will handle allocation if we pass NULL as the buffer, but please note that this [will not remove path length limitations](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation).
Unfortunately, posix_fs.jakt is not so straightforward.
realpath: POSIX.1-2008 lets us pass NULL for the second argument, resolved_path; libc will allocate for us.
getcwd: Linux lets us pass NULL, but POSIX defines this as undefined behavior. Can and should we special-case any os/libc whose getcwd will do the allocation for us?
=> runtime: Don't hardcode PATH_MAX

documentation/cmake-bootstrap.md
The outdated documentation has been confusing people for a while.
Clang 15 is the minimum required, as set in the `jakt.nix` file in
601b5dd8.
=> documentation: Update minimum required clang version

editors/kate/Jakt.xml, editors/kate/README.md
Hey there,
I have developed a `Jakt language` highlighting plugin for `Kate Editor`. I believe that this plugin would be a valuable addition to the main project. Therefore, I would like to kindly request a pull request to contribute my plugin to the main repository.
I have thoroughly tested the plugin and ensured that it meets the coding standards and guidelines of the Kate Editor project. It provides accurate syntax highlighting and enhances the editing experience for `Jakt language` files.
Thanks,
VHeidair
=> editors/kate: Kate Editor, syntax highlighting for Jakt

tests/codegen/escaped_backslash_cpp.jakt
This previously caused a crash (#1159). This time it was caused by a bug in AK/StringUtils, and fixed by https://github.com/SerenityOS/serenity/pull/22326, but it'd be nice to detect if codegen messes this up again in the future.
Fixes #1159.
=> tests: Ensure backslashes are replaced correctly in codegen

selfhost/typechecker.jakt
This kind of code now gets inlay type hints in Code:
if thing is Type(a, b) {
...
}
Meaning it shows up like:
if thing is Type(a: i32, b: String) {
...
}
=> selfhost: Dump type hints for `is` bindings

bootstrap/stage0/build.cpp, bootstrap/stage0/codegen.cpp, bootstrap/stage0/compiler.cpp, bootstrap/stage0/error.cpp, bootstrap/stage0/formatter.cpp, bootstrap/stage0/git.cpp, bootstrap/stage0/ide.cpp, bootstrap/stage0/interpreter.cpp, bootstrap/stage0/jakt__arguments.cpp, bootstrap/stage0/jakt__path.cpp, bootstrap/stage0/jakt__platform.cpp, bootstrap/stage0/jakt__platform__utility.cpp, bootstrap/stage0/lexer.cpp, bootstrap/stage0/main.cpp, bootstrap/stage0/parser.cpp, bootstrap/stage0/platform.cpp, bootstrap/stage0/project.cpp, bootstrap/stage0/repl.cpp, bootstrap/stage0/repl_backend__default.cpp, bootstrap/stage0/runtime/AK/ByteString.h, bootstrap/stage0/runtime/AK/Checked.h, bootstrap/stage0/runtime/jaktlib/prelude/string.jakt, bootstrap/stage0/typechecker.cpp, bootstrap/stage0/types.cpp, bootstrap/stage0/utility.cpp, runtime/jaktlib/prelude/string.jakt, selfhost/types.jakt
Together with https://github.com/SerenityOS/serenity/pull/22377 these changes make compiling the compiler with itself in debug mode ~44% faster.
```
$ time build/bin/jakt_before -S selfhost/main.jakt 
real    0m23,247s
user    0m22,917s
sys    0m0,212s
$ time build/bin/jakt_after -S selfhost/main.jakt 
real    0m16,072s
user    0m15,875s
sys    0m0,192s
```
=> Some things to make the compiler faster when built in debug

bootstrap/stage0/codegen.cpp, bootstrap/stage0/codegen.h, bootstrap/stage0/formatter.cpp, bootstrap/stage0/git.cpp, bootstrap/stage0/ide.cpp, bootstrap/stage0/main.cpp, bootstrap/stage0/repl.cpp, selfhost/codegen.jakt, tests/codegen/nested_loop_in_match.jakt
ControlFlowState was handling control flow forwarding in an error-prone and unintuitive manner. It also was being used to apply control flow forwarding from the scope of the match IIFE that is being called, instead of the state of the outer scope, which is where the calling and forwarding takes place.
The only tracking that is needed to apply control flow forwarding is the following two things about the parent scope:
1. Is the current scope the outer loop where continue/break is handled or should it forward the special LoopContinue/LoopBreak signaling types?
2. Is the current scope the function scope to return from or should it forward the special signaling return from `ExplicitValueOrControlFlow`?
Fixes #1520.
=>   codegen: Simplify control flow forwarding rules for match IIFEs

bootstrap/stage0/codegen.cpp, bootstrap/stage0/codegen.h, bootstrap/stage0/git.cpp, selfhost/codegen.jakt, tests/codegen/nested_loop_in_match_with_nonvoid.jakt
On #1523 I forgot to update the forwarded returns from matches to be the same as
the return codegen.
Fixes #1525.
=>  codegen: Ensure return is forwarded with the correct type

selfhost/cpp_import/clang.jakt, selfhost/cpp_import/libcpp.jakt, selfhost/formatter.jakt, selfhost/interpreter.jakt, selfhost/parser.jakt, selfhost/repl.jakt, selfhost/typechecker.jakt, selfhost/types.jakt
Now that we are free to use `[]` and `[:]` in default initializers anywhere, we can use them a *lot* more and cut down on verbose initialization code.
=> selfhost: Use default initializers in a lot more places

selfhost/types.jakt, tests/typechecker/string_literal_throw.jakt
The information is already available, use that instead of assuming the worst.
Fixes #1530.
=> types: Don't assume all string literals will throw

selfhost/codegen.jakt
When matching a vanilla string literal, we now codegen a comparison
against `"foo"sv` instead of wrapping it in a temporary `ByteString`.
This drastically cuts down on temporary string allocations. :^)
This gives ~10% speedup on `jakt -S selfhost/main.jakt`
=> codegen: Avoid creating temporary ByteString to match against literal

runtime/lib.h, selfhost/codegen.jakt, selfhost/interpreter.jakt, selfhost/typechecker.jakt, selfhost/types.jakt
This makes it possible to cast between integers and floats, or floats of different types.
The runtime code adds a few fixmes about range and representation checks that must be resolved for the casts to be considered "sane", but for now this is reasonable enough.
=> selfhost: Add support for casting to float types

bootstrap/stage0/codegen.cpp, bootstrap/stage0/formatter.cpp, bootstrap/stage0/git.cpp, bootstrap/stage0/ide.cpp, bootstrap/stage0/interpreter.cpp, bootstrap/stage0/main.cpp, bootstrap/stage0/repl.cpp, bootstrap/stage0/typechecker.cpp, samples/control_flow/must.jakt, selfhost/typechecker.jakt, tests/typechecker/must_cancels_throwsy.jakt
Code generation forwards it correctly, but typechecker did not ensure
the inner expression's typecheck knew that the expression could throw.
=> typechecker: Ensure must allows throwsy expressions in non-throwsy contexts

selfhost/codegen.jakt, tests/codegen/try_loop_controls_in_match.jakt
`continue` and `break` should still work inside a match context. The
"inside try" part is only for the `try`'s IIFE, but it should still
forward the correct value when using control flow inside the `catch`.
=> codegen: Keep previous control flow state when compiling catch block

selfhost/typechecker.jakt, tests/typechecker/break_inside_defer.jakt, tests/typechecker/break_inside_loop_inside_defer.jakt, tests/typechecker/break_outside_loop.jakt, tests/typechecker/continue_inside_defer.jakt, tests/typechecker/continue_inside_loop_inside_defer.jakt, tests/typechecker/continue_outside_loop.jakt, tests/typechecker/return_in_lambda_in_defer.jakt
=> typechecker: Disallow usage of 'continue' and 'break' outside of loops

selfhost/typechecker.jakt, tests/typechecker/missing_argument_when_default_argument_involved.jakt
=> typechecker: Error on missing non-default args when defaults provided

selfhost/codegen.jakt, selfhost/interpreter.jakt, selfhost/repl.jakt, selfhost/typechecker.jakt
"not implemented" and "invalid type" should not be throwing and instead
panicking, since getting to those means the typechecker failed at its
job. When wanting a checked expression from a void value, it can be
handled manually if needed, before calling in the function.
Also, there are parts of the interpreter that throw when encountering a
user-facing error like unwrapping a None. These should forward the error
using the `*Result` values from the interpreter, since that's the
mechanism for handling errors that are raised when interpreting user
code.
=> interpreter: Reserve throwing for soft errors

selfhost/codegen.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/codegen/match_yield_void.jakt, tests/typechecker/assign_optional_void.jakt, tests/typechecker/yield_void_match.jakt, tests/typechecker/yield_void_match_inside_match.jakt, tests/typechecker/yield_void_try_catch_in_match.jakt
Fixes #1544. First sample now shows an error "Cannot assign `Optional<void>` to a variable". Second sample prints "PASS".
=> Disallow assigning Optional<void>, allow yielding void functions and nothing

CMakeLists.txt, selfhost/main.jakt, selfhost/platform/posix_compiler.jakt
If the developer has another `clang` in their path that is different
from the one that ends up getting found via find_package, this could
lead to some really unexpected behavior.
=> CMake: Always grab the resource-dir from the Clang we find_package'd

README.md
I found a typo in the task list element in the "Closures" section and fixed it.
**Before**:
**After**:
=> README: fix markdown typo in document

selfhost/codegen.jakt, tests/codegen/import_function_only_helper.jakt, tests/codegen/import_function_only_in_impl.jakt
All the forward declarations are now in their modules' header files, and header
files don't interact with each other unless the modules they represent interact
with each other.
The remaining `SetConsoleOutputCP` has been moved to the generation of C++
files, since it's potentially used only there. 
This PR's focus is to limit the scope of code generation to the modules that it
affects, so that side effects at a distance (e.g from a `#define min` in an
`import extern`) are easier to track down, since those won't generate a wall of
C++ compiler errors everywhere.
I haven't properly benchmarked it, but there's nothing to gain in clean builds,
since the amount of code generated is the same, only in different files. It
could improve cached build performance since previously adding a function …
=> Remove `__unified_forward.h` header

editors/emacs/jakt-mode.el, editors/kate/Jakt.xml, editors/sublime/sublime-for-jakt.sublime-syntax, editors/vim/syntax/jakt.vim, editors/vscode/syntaxes/jakt.tmLanguage.json, jakttest/README.md, jakttest/jakttest.jakt, jakttest/parser.jakt, jakttest/run_one.py, runtime/jaktlib/path.jakt, selfhost/codegen.jakt, selfhost/compiler.jakt, selfhost/formatter.jakt, selfhost/lexer.jakt, selfhost/main.jakt, selfhost/parser.jakt, selfhost/repl.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/codegen/export.jakt, tests/codegen/export_helper/use_import.cpp
Supports exporting types to handy header files, following the design in the SerenityOS discord: https://discord.com/channels/830522505605283862/983664833096466462/1258917037988777985
This PR supports only exporting types. Exporting functions and namespaces is left out for now.
Things to  fix (sorted by relevance):
- ~~support exporting generic types~~ inherently supported by just `using name;`
- ~~specify an export directory other than `<builddir>/exports`~~ done by alimpfard
- ~~find out how to get to the build directory from the export directory, so that includes work without setting the build directory as include dir~~ done by alimpfard
- ~~group exports by namespace tree, not by type.~~ Discarded, it's pretty but not needed
=> selfhost: Add support for `export`s

selfhost/typechecker.jakt
Fixes a bug where an imported class with the same name as its defining
module/namespace would be skipped in call resolution:
```
// in tvec3.jakt
class tvec3 {
thing: i32
public fn create(...) -> tvec3 => ...
}
```
```
// in main.jakt
import tvec3 { tvec3 }
fn main() {
let t = tvec3::create(...)
}
```
Prior to this change, Jakt will reject the `create` call in `main.jakt`
as an `unknown function`.
=> typechecker: Try namespaces last when resolving calls

selfhost/codegen.jakt, selfhost/typechecker.jakt, selfhost/types.jakt
A module namespace is not inherently named, that's an implementation detail that should not be exposed to the user.
Previously `import foo { foo }` would import the module `foo`'s main namespace, which was effectively the same as `import foo`; this is not a desirable behaviour as any namespace called `foo` within that module would effectively be shadowed by this alias.
=> selfhost: Do not conflate module namespace names with regular names

selfhost/codegen.jakt, tests/codegen/same_namespace_class.jakt
Namespace qualifiers for Jakt types (not prelude ones) now have the
`Jakt::` namespace prepended to them.
Fixes a bug where if a class A is defined in module A, Jakt would use `A::A`
in the method definition of a class, and C++ would complain saying that
`A::A` refers to the constructor, since the method definition is inside
the class.
=> codegen: Include toplevel `Jakt::` in namespace qualifiers

selfhost/typechecker.jakt, tests/codegen/is_expr_runs_only_once.jakt
Generates temporary variables for `IsEnumVariant` LHS expressions and
adds them to the previous block.  This way pattern bindings use the
cached temporary and avoid re-evaluating any potential side effects.
Fixes #1450.
=> typechecker: Run `IsEnumVariant` LHS only once

selfhost/typechecker.jakt, tests/typechecker/assign_base_to_derived.jakt, tests/typechecker/match_do_not_infer_none.jakt, tests/typechecker/match_expression_type_mismatch.jakt, tests/typechecker/match_infer_class_from_block.jakt, tests/typechecker/match_infer_class_from_expression.jakt, tests/typechecker/match_infer_optional_from_block.jakt, tests/typechecker/match_infer_optional_from_block_bad.jakt, tests/typechecker/match_infer_optional_from_expression.jakt, tests/typechecker/match_infer_optional_from_expression_bad.jakt
2b7e74b
6e2ba49
Previously we would wrongly assume that given:
```rs
class A { }
class B : A { }
```
assignment of `A` to a variable of type `B` would be fine which led to a C++ compiler error.
acf7229
6f43208
When yielding ex. an `Optional<T>` or a `WeakPtr<T>` out of the match, if we already inferred the result type to be `T`, we would just print an error that types are incompatible. On the other hand, if we first inferred the result type to be ex. `T?`, everything would be fine. Inferring the "most compatible" type seems more reasonable. This not only works for Optionals, WeakPtrs, but also for classes and subclasses since the code is based on the `check_types_for_compat` method (which works correctly after the fixes in the first two commits).
5d80411
Yielding `None` if the result type …
=> Make returning Optional, WeakPtr and None from match less of a pain. Fix for subclasses and classes

editors/vim/syntax/jakt.vim
Multiline strings were highlighted as if they were Jakt code, making the
`appendff` format strings in codegen hard to distinguish from the
*proper* Jakt code. Now `oneline` is not assumed and those highlight
correctly.
=> editors/vim: Fix multiline string highlight support

selfhost/typechecker.jakt, tests/typechecker/cast_nonexistent_mult.jakt
This is what the original logic was trying to do, but its scope of "ignore type errors" was much greater, leading to miscompilations.
=> typechecker: Make type casts use TypeHint::CouldBe

selfhost/typechecker.jakt, tests/typechecker/while_is_enum_variant.jakt
Now conditions are first processed like in `if` or `guard`, except
that when statements for temporaries are needed the loop is converted
to a bare loop with an `if cond { body } else { break }` statement
after said statements, to ensure they're run in a loop.
While implementing this I found out that the precondition statements' control
flow wasn't being taken into account, so I fixed it before implementing the
feature.  
This makes `while <thing> is <variant>(<bindings>)` compile.
=> typechecker: Support `IsEnumVariant` in while loop

selfhost/typechecker.jakt, tests/typechecker/function_base_class_array_argument_derived_given.jakt, tests/typechecker/function_base_class_dictionary_argument_derived_given.jakt, tests/typechecker/function_base_class_dictionary_argument_derived_given2.jakt, tests/typechecker/function_base_class_set_argument_derived_given.jakt
=> typechecker: Choose broader type in arrays, sets and dicts

selfhost/compiler.jakt, selfhost/main.jakt, selfhost/repl.jakt, selfhost/typechecker.jakt
Now Jakt does not bake the contents of prelude in the binary, instead it
uses the provided runtime path so that prelude can be edited and
overridden when required.
Saves ~186 kB of generated C++ code, which were the contents of the
prelude, encoded as an array of static casts.
=> selfhost: Fetch prelude contents from dynamic runtime path

runtime/jaktlib/prelude/operators.jakt, samples/basics/escape_sequence.jakt, samples/closures/capture_by_reference.jakt, samples/closures/capture_by_value.jakt, samples/closures/trailing_closure_parameter.jakt, selfhost/codegen.jakt, selfhost/error.jakt, selfhost/parser.jakt, selfhost/types.jakt, tests/parser/missing_return_type_arrow.jakt, tests/parser/missing_return_type_arrow_after_throws.jakt, tests/typechecker/generic_function_with_function_param_wrong_return_type.jakt, tests/typechecker/none_coalescing_assign_to_immutable.jakt
- codegen: Hint when parentheses are needed in codegen_expression
- codegen: Avoid generating extra parentheses with error handlers
- codegen: Use `this->` on accessors when appropiate
Codegen added a lot of extra opening parentheses that made expressions inside `while`/`if` hard to parse visually due to a large number of opening parentheses. Now codegen does not emit parentheses on most cases that it doesn't need to, it's only missing cases that are based on binary operator precedence.
These commits removed ~2000 parentheses and ~100kB worth of selfhost C++ code.
- runtime: Make integral comparisons use C++ operators
Due to the inlined comparison functions that used `.compare` with a cast, any Jakt expression that had a `<` (e.g the condition for `while bytes_written < writes_read`) …
=> codegen+runtime: Make C++ output easier to parse visually

selfhost/codegen.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt
Jakt now keeps the match patterns grouped by case because there are ways to avoid duplicating the code
once we know more about the types in codegen.
Typechecker still does the same amount of work as before since I haven't explored the consequences of not duplicating at the parser level.
Codegen does less work sometimes because joining multiple patterns also means generating the match body less times.
For selfhost, a big example of these kicking into action is
`typecheck_binary_operation`. I gathered the amount of lines of formatted C++
of the function on each output and time it takes to parse an unformatted
`typecheck_binary_operation`:
|Commit|Lines of formatted code|
|---|---|
|`main`        | 5518|
|This commit   | 349|
|Commit         |Time spent in `ParseFunctionDefinition`
|--- …
=> codegen: Avoid duplicating match bodies

selfhost/codegen.jakt
ExplicitValueOrControlFlow (from now EVOCF) is only required when using control
flow features like `return`(ing from a function), `continue` or `break` inside
a match that yields a value, because yielding a value requires usage of an
IIFE. If those features aren't used, or the match doesn't yield a value, there
is no need to forward any control flow through the return channel.
This removes EVOCF instantiations from the clang -ftime-trace profile, since
most matches don't require `AK::Variant`s.
=> codegen: Use ExplicitValueOrControlFlow sparingly

selfhost/codegen.jakt
So that array indexing doesn't awkwardly call `operator[](index)`,
which is what it does since the Index trait was introduced.
=> codegen: Convert `operator[]` to C++ index operator

documentation/pattern-match-avoid-duplication.md, selfhost/codegen.jakt, selfhost/ide.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/codegen/match_enum_same_body_different_impl.jakt
Fixes cases where the body is not duplicated when it should,
specially with instantiations that are inferred inside the body for
functions that support both instantiations and overloading. C++ can deal
with overloading, but we add the template parameters ourselves, which
makes the typing wrong for at least one pattern.
Introduces `BindingKey`, `MatchBuilder` and `BindingKeyBuilder`, which
together help keep match body code duplication at a low rate while being
as least intrusive as possible to the logic for each match typecheck:
`typecheck_match` has three big `for` loops with bodies that walk the
match cases in very different ways, and the deduplication system is
orthogonal to all of them. Most of it is implemented between
`MatchBuilder` and `BindingKeyBuilder`.
These builder states …
=> typechecker+codegen: Emit new bodies for bindings with different types

selfhost/compiler.jakt
This PR fixes an issue with IDE integration where the compiler would use the relative path of the temporary file for imports, rather than the main file path specified.
=> compiler: Use --assume-main-file-path as relative path for imports

samples/tuples/destructuring_assignment.jakt, samples/tuples/destructuring_declaration.jakt, selfhost/codegen.jakt, selfhost/ide.jakt, selfhost/interpreter.jakt, selfhost/parser.jakt, selfhost/typechecker.jakt, selfhost/types.jakt, tests/typechecker/tuple_assignment_struct_fields_invalid.jakt
Currently we allow descructuring declarations for example:
```
let (x, y) = (1, 2)
```
This extends so that we can do destrucuting assignments for example:
```
mut x = 0
mut y = 0
(x, y) = (1, 2)
```
Additionally we can do nested destructuring for example:
```
mut x = 0
mut y = 0
mut z = 0
(x, (y, z)) = (1, (2, 3))
```
Will add this for declaration destructuring as part of a separate PR.
Note: This is similar to an older PR: https://github.com/SerenityOS/jakt/pull/1161
The main difference being that it specifically only allows `Var` or `JaktTuple` for nesting on the LHS. Also the earlier PR had fairly significant parser changes but this version handles it within the typechecker without introducing parsing changes.
=> everywhere: Allow descructuring assignments
