SerenityOS/jakt

- .github/workflows/ci.yml
- src/codegen.rs
- src/compiler.rs
- src/lexer.rs
- src/lib.rs
- src/main.rs
- src/parser.rs
- src/typechecker.rs
- tests/main.rs
This might be too strict for the repository right now, but I think it would be beneficial to have this setup as the repository grows in size.
> Add clippy check to github actions

- src/codegen.rs
- src/parser.rs
- src/typechecker.rs
At least for me, Clippy now doesn't complain about anything.
> Fix all clippy warnings

- src/typechecker.rs
This gives the typechecker its own pretty printer for type names rather than using codegen to create the typenames
> Typechecker: better typenames in mismatch errors

- src/lib.rs
> Meta: Make all normal Clippy lints a hard error

- runtime/prelude.jakt
- samples/classes/static_method.jakt
- src/typechecker.rs
- tests/typechecker/class_private_static.error
- tests/typechecker/class_private_static.jakt
> Make non-`public` static methods actually private

- README.md
- samples/enums/parse.jakt
This updates the enum test case that tries the different supported enum cases and also adds an output file so that the testcase is actually run.
> Tests: Update enum testcase to latest syntax

- src/parser.rs
- src/typechecker.rs
> Everywhere: Replace remaining instances of 'ty'

- samples/enums/underlying.jakt
- src/typechecker.rs
Add separate typecheck for main functions as stated in https://github.com/SerenityOS/jakt/issues/184
Also fix tests to use this new declaration.
> typechecker: Check jakt `main` type declaration

- README.md
Updates the build steps to what seems to work for me (had to add `-I.`)
> docs: Update readme for latest build steps

- samples/weak/assign_weak_to_weak.jakt
- samples/weak/question_mark_required.jakt
- samples/weak/reject_immutable_weak.error
- samples/weak/reject_immutable_weak.jakt
- src/typechecker.rs
- tests/typechecker/assign_to_weak_on_declaration.jakt
(Sorry for the duplicate PR, had some git issues)
Closes #295
> typechecker: Reject immutable weak references

- samples/match/match_generic_codegen.jakt
- src/typechecker.rs
- tests/typechecker/array_with_void_values.jakt
- tests/typechecker/dict_with_void_keys.jakt
- tests/typechecker/dict_with_void_values.jakt
- tests/typechecker/match_exhaustive_catchall.err
- tests/typechecker/match_exhaustive_catchall.jakt
- tests/typechecker/match_non_exhaustive.err
- tests/typechecker/match_non_exhaustive.jakt
- tests/typechecker/match_non_exhaustive_value.err
- tests/typechecker/match_non_exhaustive_value.jakt
- tests/typechecker/set_with_void_values.jakt
- tests/typechecker/tuple_with_void_values.jakt
Now with fun hints and extra cute errors!
> typechecker: Add a (fairly primitive) match exhaustiveness check

- src/typechecker.rs
- tests/typechecker/constructor_with_different_generic_instance.error
- tests/typechecker/constructor_with_different_generic_instance.jakt
> Typechecker: Fix not erroring when checking Struct and GenericInstance

- runtime/Builtins/Array.h
- runtime/prelude.jakt
- samples/arrays/array_iterator.jakt
- samples/arrays/array_iterator.out
Basic array iteration, before:
for i in 0..array.size() {
let value = array[i]
...
}
After:
for value in array.iterator() {
...
}
This is obviously not perfect, but an incremental improvement. :^)
> runtime: Add a simple Array iterator

- README.md
As of now, it is not necessary to invoke compiler arguments when building, it is internally handled in the main.rs file.
> docs: Update readme for the latest build steps

- samples/apps/example.jakt
Left here from my previous pr by accident
> samples: Delete example.jakt

- src/parser.rs
> Parser:  Mark main as throws automatically

- src/parser.rs
Previously, parse_operator matched the token contents using lots of
copy-and-pasted cases. This commit coalesces many of these cases to
avoid duplication.
> Parser: Deduplicate code by coalescing parse_operator cases together

- src/typechecker.rs
Currently, blocks do not keep track of their own scope. This makes analysis of the produced type tree pretty much impossible. This PR adds a `ScopeId` field to `CheckedBlock` in order to allow analysis (for example, getting the declaration for a random identifier nested deeply inside of a function). 
I'm not really sure if some of these blocks even really need their own scopes (for example, generated constructors), so maybe instead of creating a new scope for those, the scope id field should be optional? Not sure. I only really need it for `typecheck_block`.
> typechecker: Store ScopeId on CheckedBlock

- runtime/AK/Atomic.h
- runtime/AK/Checked.h
- runtime/AK/Error.h
- runtime/AK/Iterator.h
- runtime/AK/Memory.h
- runtime/AK/NonnullRefPtr.h
- runtime/AK/Optional.h
- runtime/AK/RefCounted.h
- runtime/AK/RefPtr.h
- runtime/AK/Span.h
- runtime/AK/String.h
- runtime/AK/StringView.h
- runtime/AK/TypeCasts.h
- runtime/AK/Variant.h
- runtime/lib.h
This speeds up building the self-hosted by about 15% on my machine.
Since we'll be building it a lot, let's optimize for build time
instead of performance right now. :^)
> runtime: Remove ALWAYS_INLINE everywhere

- selfhost/main.jakt
- src/typechecker.rs
- tests/typechecker/field_access_on_enum.jakt
Handful of progress patches for the self-hosted Jakt compiler coming through.
Also a slight warning improvement + test for the Rust-based compiler.
> Work towards the self-hosted compiler

- editors/vscode/syntaxes/jakt.tmLanguage.json
- selfhost/main.jakt
- src/codegen.rs
This is a start at adding operator parsing to the selfhost compiler.
> selfhost: Add start of operator parsing

- editors/vscode/.eslintrc.js
- editors/vscode/.vscodeignore
- editors/vscode/package.json
- editors/vscode/server/package.json
- editors/vscode/server/src/server.ts
- src/ide.rs
Before it just displayed `function name()`, now it displays the whole signature.
> ide+vscode: Show full function signature

- editors/vscode/client/package-lock.json
- editors/vscode/client/package.json
- editors/vscode/package-lock.json
- editors/vscode/package.json
- editors/vscode/server/package-lock.json
- editors/vscode/server/package.json
- editors/vscode/server/src/server.ts
- samples/generics/generic_struct_mismatch.jakt
- src/main.rs
- src/parser.rs
- src/typechecker.rs
- tests/typechecker/assign_incompatible_to_optional.jakt
- tests/typechecker/assign_integer_to_weak.jakt
- tests/typechecker/constructor_with_different_generic_instance.jakt
- tests/typechecker/field_access_on_enum.jakt
> Add type inlay hints to the VSCode extension

- src/parser.rs
- src/typechecker.rs
> parser+typechecker: Emit type hints for enum match cases

- editors/vscode/package-lock.json
- editors/vscode/server/src/server.ts
This commit implements a throttled function factory. This was done because it was being called too many times
while typing, causing some lag. Now about 50% of calls are rejected while typing fast. Also cleans up printing to console so there is less spam.
> vscode: Throttle text document validation

- editors/vscode/server/src/server.ts
This whole situation is a mess, since LSP requires that we provide
file offsets and column indices in UTF-16 "coordinates". This patch
doesn't improve the architecture, but instead makes a cache of line
break locations in the document text so we don't have to scan from the
start of the document every time we want to convert between systems.
This significantly reduces UI lag caused by the type inlay hints.
The *nice* solution to all this would be that vscode adds support for
UTF-8 offsets in the future. There's a new LSP extension for this,
but so far they only advertise UTF-16 support.
> editors/vscode: Cache line break positions for faster span conversion

- editors/vscode/server/src/server.ts
Use binary search to find the correct line index and remove unnecesary loop to get the index of the character in the line.
> vscode: Optimize convertSpan

- src/ide.rs
- src/parser.rs
- src/typechecker.rs
This PR adds span information to more places in our checked AST. New places with span info:
* parameter types of functions
* return types of functions
* enum variant sub-components
* struct field types
This allows you to access them via the IDE support as well, which enables features like goto-def on the types.
> all: Improve type span information

- editors/vscode/client/src/test/helper.ts
- editors/vscode/package.json
- editors/vscode/server/src/server.ts
Add ignore comments and fix up type definitions to stop getting warnings.
Please merge after PR #505 since one commit is included after that.
> vscode: Cleanup up warnings and add extension dependencies to install script

- src/main.rs
> main: Bubble up error code from clang command

- src/typechecker.rs
- tests/typechecker/dont_return_from_every_match_case.jakt
- tests/typechecker/return_from_every_match_case.jakt
> typechecker: Check whether each match arm returns

- src/typechecker.rs
> typechecker: Modules first scopes are created correctly

- src/compiler.rs
- src/ide.rs
- src/typechecker.rs
This improves the IDE support for most IDE features.
Completions are returning more than they should, but hover/goto def/errors/goto type def seem to be mostly working.
> all: Fix breakage in IDE support

- runtime/Builtins/Array.h
The runtime patch makes Array capacity grow in larger increments, which makes the self-hosted compiler lex itself in milliseconds instead of 10+ seconds 😅 
The other patch adds character and byte literal parsing to selfhost.
> selfhost+runtime: Small progress on self-hosting

- src/codegen.rs
- src/compiler.rs
- src/ide.rs
- src/typechecker.rs
Fixed a bug where root module was not being created properly, resulting in the scopes being incorrect.
> compiler+typechecker+codegen: Root module created properly

- selfhost/lexer.jakt
- selfhost/main.jakt
As the Namespaces for AK and the Jakt executable are different now we
can make this change.
> selfhost: Rename JaktSpan to Span

- src/codegen.rs
This works for comping JT's draft changes from https://github.com/SerenityOS/jakt/pull/564
(Though though may be some corner cases this still misses)
> codegen: Sort modules by dependencies & predeclare everything first

- src/codegen.rs
- src/typechecker.rs
This fixes my previous changes that kinda accidentally worked.
> typechecker+codegen: Topologically sort modules in codegen

- editors/vscode/server/src/server.ts
Adds the path of the working file to the include path when invoking
the compiler. Without this the compiler fails to resolve imports as
the file it is invoked on is in a temporary directory, without any
of the other source files present.
> editors/vscode: Add working file parent directory to include path

- editors/nano/README.md
- editors/nano/jakt.nanorc
sometimes you want a terminal editor, and Nano is a very simple/friendly
choice. Adding syntax highlighting makes the user experience better.
> editors: add support for GNU Nano

- editors/vscode/server/src/server.ts
The compiler may emit duplicate type hints in some situations,
such as "foo | bar | baz" match cases.
This patch deduplicates the hints in the language server for now.
The nicer fix will be to not emit duplicate hints in the first place,
but let's leave that for the self-hosted compiler instead of making
big changes to the baseline compiler now.
> editors/vscode: Collapse duplicate inlay hints

- selfhost/typechecker.jakt
Adds OptionNone and OptionSome to the selfhost expression typechecker
> selfhost: Port more expression checking

- selfhost/codegen.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
Lots of stuff missing here, but let's stand up a basic skeleton that can be filled in.
> selfhost: Flesh out basic function and call codegen

- selfhost/lexer.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
Implement lexing and parsing of numeric constants with type suffixes
> selfhost: Better support for numeric constants (+ suffixes)

- selfhost/lexer.jakt
- selfhost/parser.jakt
- src/parser.rs
- tests/parser/missing_return_type_arrow.jakt
- tests/parser/missing_return_type_arrow_after_throws.jakt
Handful of parsing patches written on a train.]
> selfhost+parser: Hack on selfhost until it can parse its own lexer :^)

- selfhost/codegen.jakt
- selfhost/lexer.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
More patches from a bumpy train in the countryside 🚋
> selfhost: More work on selfhost lexing & parsing

- selfhost/typechecker.jakt
- tests/typechecker/main_too_many_params.jakt
- tests/typechecker/main_wrong_param_type.jakt
- tests/typechecker/main_wrong_return_type.jakt
The main function should have no more than one parameter and it must
be a String array. If a return type is stated, it must be c_int.
> selfhost/typechecker: Check main has correct parameters and return type

- editors/vscode/package.json
- editors/vscode/server/src/server.ts
- meta/update-vscode-extension.sh
- selfhost/codegen.jakt
- selfhost/lexer.jakt
- selfhost/typechecker.jakt
- src/codegen.rs
- src/ide.rs
- src/typechecker.rs
The `else` thing:
The rest are just niceties to make the last commit possible :P
> Some IDE things, Some selfhost, and a little bit of return; sauce

- selfhost/typechecker.jakt
Adds more type equality support. This should now cover all our basic types.
> selfhost/typecheck: Improve equality checking

- selfhost/codegen.jakt
- selfhost/typechecker.jakt
With this change, we pass all of the if samples! :^)
> Check and generate If statements

- selfhost/typechecker.jakt
Add checks for
* Garbage
* InlineCpp
* ForcedUnrwap
to selfhost typechecker
> selfhost/typechecker: Check Garbage, InlineCpp and ForcedUnrwap 

- selfhost/typechecker.jakt
> selfhost/typechecker: Simplify Typechecker::type_name()

- selfhost/codegen.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
the only problem that stands in the way of running `samples/basics/bubble_sort.jakt` is the prelude.
:yakbait: anyone??
> selfhost/parser+typechecker+codegen: Misc progress to run bubble_sort sample

- selfhost/typechecker.jakt
This is required by #701 and #716.
> selfhost/typechecker: Add resolve_type_var method

- selfhost/typechecker.jakt
I've been working on porting this for a while now :^)
I can't really check if everything is working as it is supposed to, as struct codegen is not implemented yet. But in order to work on codegen we need to typecheck first anyway.
This PR will conflict with #701 as both implement `resolve_type_var()`.
> selfhost/typechecker: Typecheck structs

- selfhost/codegen.jakt
- selfhost/typechecker.jakt
Moving closer to including the prelude
> selfhost: Implement various codegen

- samples/functions/call_wrong_arg_count.jakt
- selfhost/typechecker.jakt
- src/typechecker.rs
6 more tests passing with these changes :^)
> selfhost: Handful of test progressions

- jakttest/run-all.sh
I got burned by running the tests on an old version of the selfhost.
> jakttest: Script enhancements

- selfhost/typechecker.jakt
Implements typechecking for IndexedTuple
> selfhost/typechecker: Typechecking for IndexedTuple

- selfhost/error.jakt
- selfhost/typechecker.jakt
One of these days, someone other than AK/JT will add their license information to some Jakt code... ;^)
> selfhost: Add missing licenses to selfhost code

- selfhost/codegen.jakt
- selfhost/typechecker.jakt
Adds some basic support for codegen of classes with constructors. Passing tests: +2
Now:
```
121 passed
211 failed
7 skipped
```
> selfhost/codegen: Add support for basic class codegen

- selfhost/codegen.jakt
also, generate debug descriptions and ak formatter for structs/classes
> Finish support for `is` operator

- selfhost/codegen.jakt
- selfhost/typechecker.jakt
plus bonus bug fix that I needed to run the tests :^)
> selfhost/typechecker+codegen: CatchAll for enum matching

- selfhost/typechecker.jakt
Resolves the Fixme in `typecheck_typename`
> selfhost/typechecker: Implement GenericResolvedType

- samples/imports/foo.jakt
- samples/imports/import_alias_list.jakt
- selfhost/codegen.jakt
- selfhost/compiler.jakt
- selfhost/lexer.jakt
- selfhost/main.jakt
- selfhost/parser.jakt
- selfhost/prelude.jakt
- selfhost/typechecker.jakt
- selfhost/utility.jakt
Adds multi-file/module support + some fix-ups.
Before (62b30a0dea3922edcaa8d2f9ed60c1f9858c1c84)
```
197 passed
134 failed
8 skipped
```
After
```
203 passed
129 failed
8 skipped
```
(Also has 2 commits from open tooling PRs in there)
> selfhost: Add multi-file/module support

- samples/arrays/array_bad.jakt
- samples/arrays/array_bad2.jakt
- selfhost/typechecker.jakt
- src/typechecker.rs
A few small bug fixes so that now these 4 additional tests pass
```
samples/arrays/array_bad.jakt
samples/arrays/array_bad2.jakt
samples/arrays/empty_literal_without_hint.jakt
samples/arrays/prefill.jakt
```
> typechecker+tests+selfhost/typechecker: Some low-hanging fruit in the array samples

- src/ide.rs
Just like we do for function calls already
> ide: Give usage information for method call parameters

- selfhost/typechecker.jakt
+2 more passing tests :^)
`samples/arrays/empty_infer_call.jakt`
`samples/arrays/inference_empty.jakt`
> selfhost/typechecker: Infer generic of empty array in assignments

- selfhost/codegen.jakt
- selfhost/compiler.jakt
- selfhost/error.jakt
- selfhost/lexer.jakt
- selfhost/main.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
- selfhost/utility.jakt
I cleaned it up some more and all tests are passing. :^)
> selfhost: Make spans aware of which file they belong to

- selfhost/parser.jakt
Solve a couple of FIXMEs and TODOs by adding deep comparisons of Enum variants.
All the same tests in main are passing.
> selfhost/parser: Add edge cases comparisons and resolve FIXMEs

- selfhost/codegen.jakt
Every statement is now covered in `codegen_statement`.
> selfhost/codegen: Implement codegen for yield

- src/main.rs
Fix the logic in the compiler missing check to allow for the compiler to be in the path but not at the given location (helpful for the default invocation of clang++)
> main: Fix compiler missing check

- selfhost/codegen.jakt
- selfhost/typechecker.jakt
Adds codegen for `WeakPtr` built in type.
Fixes `assign_to_weak_on_declaration` test
> selfhost/codegen: Codegen WeakPtr type

- selfhost/typechecker.jakt
Passes 2 more tests
```
[ PASS ] samples/weak/basic.jakt
[ PASS ] samples/weak/reassign.jakt
```
> selfhost/typechecker: Allow assigning T to weak T?

- selfhost/typechecker.jakt
pass a couple more tests
```
[ PASS ] samples/sets/inference_empty.jakt
[ PASS ] samples/match/match_non_enum.jakt
```
> selfhost/typechecker: Infer type of set literals

- selfhost/codegen.jakt
- selfhost/typechecker.jakt
`[ PASS ] samples/dictionaries/lvalue.jakt`
> selfhost/typechecker+codegen: Dictionary lvalue

- samples/apps/json.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
- src/typechecker.rs
- tests/typechecker/block_yield_type_mismatch.jakt
```
[ PASS ] samples/apps/json.jakt
[ PASS ] tests/codegen/ns_level_circular_dependency.jakt
[ PASS ] tests/typechecker/block_yield_type_mismatch.jakt
```
```
324 passed
13 failed
3 skipped
```
> selfhost: Pass 3 more tests

- selfhost/typechecker.jakt
Make `samples/namespaces/call_functions_in_nested_namespaces.jakt` pass
> selfhost/typechecker: Fix bug in `resolve_call()`

- src/typechecker.rs
cc @awesomekling 
Andreas noticed we were dropping errors on the return type in some cases. This isn't a complete fix, but at least stops us from dropping those errors if the type sides aren't compatible.
fwiw: not 100% sure this is necessary, but gives something to watch out for in the selfhost compiler - we probably want to separate inference from the typecheck so it's clear when we should error and when we shouldn't.
> typechecker: Don't drop error message on return types

- runtime/Builtins/Array.h
- runtime/prelude.jakt
- selfhost/codegen.jakt
- selfhost/parser.jakt
- selfhost/prelude.jakt
- selfhost/typechecker.jakt
In addition to running all the unit tests, selfhost also needs to compile itself of course.
There's currently a *lot* of errors when trying to do that. Here are some assorted patches that reduce the error count.
> Misc progress towards selfhost compiling selfhost

- jakttest/jakttest.jakt
- jakttest/parser.jakt
- jakttest/run-one.sh
- samples/functions/argument_labels_bad.jakt
- samples/functions/call_missing_function.jakt
- tests/typechecker/nonexistent_type.jakt
Now:
```
326 passed
11 failed
3 skipped
```
> jakttest: Handle tests that panic a bit better

- selfhost/typechecker.jakt
And moar goodies to make those two tests pass.
```
330 passed
7 failed
3 skipped
```
> typechecker: Port over late generic instantiation logic

- selfhost/typechecker.jakt
Fixes: tests/typechecker/constructor_with_different_generic_instance.jakt
> selfhost/typechecker: Check mismatched struct/generic struct

- runtime/lib.h
- selfhost/codegen.jakt
- selfhost/typechecker.jakt
needs a bit more work still to make the generated selfhost c++ file compile
> selfhost: Topologically sort modules before generating code

- selfhost/main.jakt
-o option changed from binary directory to output filename as it is a more
common usage of -o
> main: Add option to specify the output filename

- README.md
- samples/closures/capture_by_reference.jakt
- samples/closures/capture_by_value.jakt
- samples/closures/function_as_parameter.jakt
- samples/closures/function_as_variable.jakt
- samples/closures/lambdas_can_throw.jakt
- samples/closures/no_returning_functions.jakt
- selfhost/codegen.jakt
- selfhost/ide.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
Andreas's video about references inspired me to start this again and take a more systematic approach. The result is a much better product in my opinion. Returning a function is explicitly not allowed right now as there are some things that need to be worked out.
> Closures but for real this time

- runtime/IO/File.cpp
- runtime/IO/File.h
- runtime/prelude.jakt
- selfhost/compiler.jakt
- selfhost/main.jakt
- selfhost/prelude.jakt
- selfhost/typechecker.jakt
With these changes, the selfhost compiler can fully annotate and check itself within the IDE extension.
Goto-def and dot completions are still missing.
> selfhost: More work on IDE extension support

- selfhost/main.jakt
- selfhost/typechecker.jakt
Here's enough fixes to make IDE dot completions work with selfhost as the IDE extension backend.
> selfhost: Make IDE dot completions work

- runtime/Jakt/Optional.h
- samples/optional/throw_while_none_coalescing.jakt
- selfhost/codegen.jakt
- selfhost/typechecker.jakt
This necessitated some additional C++ helpers in Optional<T>.
> selfhost+runtime: Support throwing call on right side of `??` operator

- runtime/Jakt/Error.h
- runtime/Jakt/Optional.h
- selfhost/codegen.jakt
- selfhost/ide.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
- tests/codegen/optional_chaining.jakt
~~Still need to write a few more tests, but~~ here it is - `operator?.`.
> selfhost+runtime: Implement optional chaining

- runtime/Builtins/Array.h
- runtime/Jakt/StringBuilder.h
- runtime/prelude.jakt
- samples/arrays/slice.jakt
- selfhost/codegen.jakt
- selfhost/parser.jakt
- selfhost/prelude.jakt
- selfhost/typechecker.jakt
- tests/typechecker/array_slice_immutable.jakt
Create an ArraySlice from an Array using `arr[start_index..end_index]`
where start_index is the first position in the slice and end_index is
one more than the last position in the slice.
> all: Implement array slices

- jakttest/jakttest.jakt
- selfhost/ide.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
Here's an assortment of cleanups that take advantage of new language features to reduce rightward drift (or simplify the code in other ways).
> Miscellaneous cleanups with new features

- bootstrap/stage0/jakt.cpp
- build.ninja
- jakttest/build.ninja
- jakttest/run-one.sh
- selfhost/main.jakt
Switch compiler to build by default rather than output source. Now use `-S` to output the source.
> bootstrap+main: Make build the default (-S for source only)

- CMakeLists.txt
- selfhost/main.jakt
- selfhost/parser.jakt
- selfhost/repl.jakt
- selfhost/typechecker.jakt
Enough said.
Make sure to use `rlwrap` or face the wrath of stdin.
> Pull in the repl as `jakt --repl`

- selfhost/main.jakt
- selfhost/repl.jakt
For faster dev cycles...when the interpreter can run your code :P
cc @jntrnr, you asked for dis.
> selfhost: Make '--run' and '-r' execute a file with the interpreter

- runtime/Jakt/String.h
- samples/compiletime_execution/bitwise.jakt
- samples/compiletime_execution/optional.jakt
- samples/compiletime_execution/string.jakt
- selfhost/codegen.jakt
- selfhost/typechecker.jakt
This PR intends to make some progress on #1053. Specifically, the remaining equality operations, most of the bitwise operations, and most of the String methods have been added.
> interpreter: Add a few operations and prelude functions

- samples/apps/json.jakt
- samples/basics/is.jakt
- samples/classes/class_with_move_only_enum_member.jakt
- samples/optional/mutable_unwrap.jakt
- selfhost/typechecker.jakt
- tests/codegen/generic_class.jakt
- tests/codegen/type_pretty_printers.jakt
This moves the constructor to being private if any of the fields in the struct are private. After this occurs, you'll need to create a static method that will handle construction for you.
> typechecker+tests: Make ctr private if field is private

- selfhost/typechecker.jakt
- tests/typechecker/none_assign_to_non_optional_built_in_type.jakt
- tests/typechecker/none_assign_to_non_optional_custom_type.jakt
- tests/typechecker/none_decl_to_non_optional_built_in_type.jakt
- tests/typechecker/none_decl_to_non_optional_custom_type.jakt
> typechecker+tests: Do not allow None assignment to non-optional types

- selfhost/typechecker.jakt
- tests/typechecker/assign_void_to_var.jakt
fix for a bug JT found in their latest jakt-nes-monster video :^)
> typechecker: Report error when assigning void

- runtime/Builtins/Array.h
- samples/arrays/slice.jakt
- samples/arrays/slice_of_slice.jakt
This allows slices to be much more useful with recursion.
> runtime: Allow a slice to be created from a slice

- selfhost/codegen.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
- selfhost/types.jakt
With the continued evolution of the compiler, several of the fixmes are able to be fixed :^)
> Fix FIXMEs

- editors/vscode/package-lock.json
I forgot to commit the package-lock.json file in #1160 yesterday. Sorry for the noise!
> editors/vscode: Update package-lock.json

- selfhost/codegen.jakt
- selfhost/typechecker.jakt
- selfhost/types.jakt
- tests/typechecker/class_field_inheritance.jakt
Co-Authored-By: JT <jt@serenityos.org>
> typechecker+codegen: Add basic support for inherited class fields

- jakttest/jakttest.jakt
- jakttest/run_one.py
- runtime/lib.h
- samples/compiletime_execution/string.jakt
- selfhost/interpreter.jakt
and support all but one string function in comptime
and fix an ide error
> Fix Jakttest on Apple Silicon

- runtime/Jakt/ControlFlow.h
- runtime/Jakt/Types.h
- runtime/lib.h
Move some stuff to places where they seem to fit better.
These are changes I made while implementing #1195 where they were used. With the new direction I'm going with this I won't need those changes anymore, but I guess they are still cleaning up the lib.h a little :)
> Cleanup lib.h

- editors/vscode/server/src/server.ts
This PR does not introduce any new features, it only makes the logging in the "Output" terminal in VsCode nicer:
Before the `console.time` calls did not give expected results since they were used in an async setting — it did not include the awaited time, which tells how long the compiler actually uses on the different actions.
This patch also adds a `durationLogWrapper` which also takes all the different return paths into account (would be nicer if TypeScript had a `defer` keyword! :^) ).
Lastly, a `getClickableFilePosition` is added which servers two purposes.
1. It makes it to see where the current action is called since you can `CMD + click` on the file path (at least on macOS).
2. Differentiate between multiple calls of the same action since the `console.time` requires that the last …
> editors/vscode: Add durationLogWrapper

- CMakeLists.txt
- selfhost/build.jakt
- selfhost/compiler.jakt
- selfhost/interpreter.jakt
- selfhost/main.jakt
- selfhost/path.jakt
- selfhost/repl.jakt
- selfhost/typechecker.jakt
> Everywhere: Tiny random fixes

- editors/vscode/server/src/server.ts
Previously when the compiler barfed on the input while formatting, the file would get truncated. This commit allows the formatting to fail without truncating the file
This commit was cherry picked from #1195 as requested :)
> edotor/vscode: Allow formatting to fail gracefully

- jakttest/README.md
Correct the executable's location on the README.
> Correct jakttest's build instructions

- .github/workflows/ci.yml
- CMakeLists.txt
- cmake/install-rules.cmake
- selfhost/main.jakt
- selfhost/posix_fs.jakt
- selfhost/project.jakt
- selfhost/unknown_fs.jakt
- selfhost/utility.jakt
- selfhost/windows_fs.jakt
...and CI for the same.
This should help make sure we don't break external projects when updating CMake and the build steps jakt uses internally.
> selfhost: Add project creator with simple example project

- selfhost/interpreter.jakt
Fix a few spelling errors in the interpreter
> interpreter: Fix some spelling errors

- samples/compiletime_execution/dict.jakt
- selfhost/interpreter.jakt
- selfhost/utility.jakt
- tests/typechecker/comptime_format.jakt
This makes it possible to print out all values in comptime, given any format string.
> interpreter: Fully implement comptime format

- runtime/Jakt/ControlFlow.h
- runtime/Jakt/DeprecatedStringBuilder.cpp
Error and ErrorOr are no longer copyable.
> runtime: Fix build after recent Serenity Error/ErrorOr changes

- selfhost/interpreter.jakt
- selfhost/typechecker.jakt
- tests/typechecker/sizeof_comptime.jakt
For when you _actually_ need the size at compile time :P
Also adds a test to make sure the sizes are accurate.
> interpreter: Implement sizeof T

- selfhost/parser.jakt
- tests/parser/invalid_attribute_identifier.jakt
> parser: Don't get stuck on invalid attribute identifiers

- jakttest/error.jakt
- jakttest/jakttest.jakt
- jakttest/lexer.jakt
- jakttest/parser.jakt
- runtime/jaktlib/arguments.jakt
- runtime/jaktlib/file_iterator.jakt
- runtime/jaktlib/path.jakt
- runtime/jaktlib/platform.jakt
- selfhost/build.jakt
- selfhost/codegen.jakt
- selfhost/compiler.jakt
- selfhost/error.jakt
- selfhost/formatter.jakt
- selfhost/ide.jakt
- selfhost/interpreter.jakt
- selfhost/lexer.jakt
- selfhost/main.jakt
- selfhost/parser.jakt
- selfhost/project.jakt
- selfhost/repl.jakt
- selfhost/typechecker.jakt
- selfhost/types.jakt
- selfhost/utility.jakt
I think the formatter does a pretty decent job at this point. Some things might be a little awkward, but it seems mostly livable. Feedback welcome :)
> One formatter fix + run formatter on everything

- bootstrap/stage0/parser.cpp
- bootstrap/stage0/parser.h
- bootstrap/stage0/typechecker.cpp
- selfhost/parser.jakt
- selfhost/typechecker.jakt
- tests/typechecker/default_arguments_sum_enum.jakt
> Allow default arguments for sum enum variant constructors

- bootstrap/stage0/parser.cpp
- bootstrap/stage0/typechecker.cpp
- selfhost/lexer.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
This pull request fixes some typos, no functional changes intended.
> meta: fix some typos

- selfhost/typechecker.jakt
- tests/typechecker/infer_return_negative_int.jakt
> typechecker: Infer correct type for negative ints

- runtime/jaktlib/prelude/operators.jakt
- samples/classes/throwing_method.jakt
- samples/modules/subfolder/Hello.h
- samples/optional/throw_while_none_coalescing.jakt
- selfhost/codegen.jakt
> A couple fixes

- runtime/Jakt/ControlFlow.h
- selfhost/codegen.jakt
- selfhost/cpp_import/clang.jakt
- selfhost/interpreter.jakt
- selfhost/main.jakt
- selfhost/parser.jakt
- selfhost/typechecker.jakt
- selfhost/types.jakt
- tests/typechecker/main_too_many_params.jakt
- tests/typechecker/main_wrong_param_type.jakt
- tests/typechecker/main_wrong_return_type.jakt
- tests/typechecker/mismatching_return_after_generic_call.jakt
- tests/typechecker/never_return_void.jakt
Fixes https://github.com/SerenityOS/jakt/issues/1484.
Fixes https://github.com/SerenityOS/jakt/issues/1473.
Fixes https://github.com/SerenityOS/jakt/issues/1403.
> Let's fix some bugs!

- selfhost/codegen.jakt
- selfhost/utility.jakt
~10% speedup when compiling the compiler with itself in debug mode:
```
$ time build/bin/jakt_before -S selfhost/main.jakt 
real	0m15,845s
user	0m15,671s
sys	0m0,132s
$ time build/bin/jakt_after -S selfhost/main.jakt 
real	0m14,488s
user	0m14,247s
sys	0m0,232s
```
> selfhost: Use StringBuilder in codegen

- selfhost/typechecker.jakt
- tests/typechecker/multiple_generic_trait_impls.jakt
> typechecker: Actually compare trait generics when looking for impls

- samples/imports/import_namespace_name.jakt
- selfhost/typechecker.jakt
...instead of the path used to reach it.
> typechecker: Use the actual module name for ns imports

- selfhost/codegen.jakt
- selfhost/compiler.jakt
- selfhost/cpp_import/clang.jakt
- selfhost/cpp_import/clang_c.jakt
- selfhost/interpreter.jakt
- selfhost/main.jakt
- selfhost/parser.jakt
- selfhost/repl.jakt
- selfhost/typechecker.jakt
> Moar fixes

- cmake/jakt-executable.cmake
This is needed for some upcoming upstream AK changes using deducing-this
> cmake: Bump CXX version to 23
